import type { SupabaseClient } from '@supabase/supabase-js';

const PREVIEW_WRITE_ERROR = {
  message: 'Les données de cette préversion sont démonstratives et ne peuvent pas être enregistrées.',
};

type PreviewResult = { data: unknown[] | null; error: typeof PREVIEW_WRITE_ERROR | null };

const PREVIEW_ROWS: Record<string, unknown[]> = {
  people: [
    {
      id: 9301,
      user_id: null,
      first_name: 'Arthur',
      last_name: 'DEMO',
      email: 'arthur.demo@example.invalid',
      function_label: 'Capitaine',
      grade_label: 'Capitaine',
      role_label: 'Navigant',
      register_label: 'ENIM',
      sex: 'M',
      sailor_number: 'DEMO-001',
      m365_account: null,
      phone: '+33 0 00 00 00 00',
      postal_address: 'Adresse de demonstration',
      birth_date: '1988-04-12',
      birth_place: 'Brest',
      identity_document_number: 'DEMO-ID-001',
      identity_document_type: "Carte d'identite",
      contract_type: 'CDI',
      hired_on: '2021-02-15',
      departed_on: null,
      departure_reason: null,
      emergency_contact_name: 'Contact Demo',
      emergency_contact_relationship: 'Proche',
      emergency_contact_phone: '+33 0 00 00 00 01',
      emergency_contact_address: 'Adresse de demonstration',
      waist_size: null,
      chest_size: null,
      full_height_size: null,
      inseam_size: null,
      hip_size: null,
      weight_kg: null,
      shoe_size: null,
      coverall_size: null,
      pants_size: null,
      jacket_size: null,
      deck_certificate_label: 'Capitaine 500',
      engine_certificate_label: null,
      crane_training_on: null,
      crane_induction_on: null,
      active: true,
    },
  ],
  hr_documents: [
    {
      id: 9401,
      person_id: 9301,
      person_name: 'Arthur DEMO',
      person_sharepoint_item_id: null,
      category_key: 'deck',
      title: 'Arthur DEMO - Capitaine 500 - 2030.pdf',
      status: 'valid',
      issued_on: '2025-03-20',
      expires_on: '2030-03-20',
      requires_captain_validation: false,
      source_label: 'preview',
      notes: null,
      file_url: null,
      storage_bucket: 'hr-documents',
      storage_path: 'preview/arthur-demo-capitaine-500.pdf',
      file_size_bytes: 245760,
      mime_type: 'application/pdf',
    },
    {
      id: 9402,
      person_id: 9301,
      person_name: 'Arthur DEMO',
      person_sharepoint_item_id: null,
      category_key: 'safety_training',
      title: 'Arthur DEMO - CFBS - 2029.pdf',
      status: 'valid',
      issued_on: '2024-01-17',
      expires_on: '2029-01-17',
      requires_captain_validation: false,
      source_label: 'preview',
      notes: null,
      file_url: null,
      storage_bucket: 'hr-documents',
      storage_path: 'preview/arthur-demo-cfbs.pdf',
      file_size_bytes: 184320,
      mime_type: 'application/pdf',
    },
    {
      id: 9403,
      person_id: 9301,
      person_name: 'Arthur DEMO',
      person_sharepoint_item_id: null,
      category_key: 'safety_training',
      title: 'Arthur DEMO - CGO - 2030.pdf',
      status: 'valid',
      issued_on: '2025-04-17',
      expires_on: '2030-04-17',
      requires_captain_validation: false,
      source_label: 'preview',
      notes: null,
      file_url: null,
      storage_bucket: 'hr-documents',
      storage_path: 'preview/arthur-demo-cgo.pdf',
      file_size_bytes: 163840,
      mime_type: 'application/pdf',
    },
    {
      id: 9404,
      person_id: 9301,
      person_name: 'Arthur DEMO',
      person_sharepoint_item_id: null,
      category_key: 'medical_visit',
      title: 'Arthur DEMO - Visite Medicale - 2027.pdf',
      status: 'valid',
      issued_on: '2025-11-08',
      expires_on: '2027-11-08',
      requires_captain_validation: false,
      medical_restriction: null,
      medical_bridge_watch: true,
      medical_unfit: false,
      source_label: 'preview',
      notes: null,
      file_url: null,
      storage_bucket: 'hr-documents',
      storage_path: 'preview/arthur-demo-visite-medicale.pdf',
      file_size_bytes: 204800,
      mime_type: 'application/pdf',
    },
  ],
  hr_visibility_rules: [],
  projects: [
    {
      id: 9001,
      title: 'Campagne Atlantique — démonstration',
      project_code: 'P901',
      client_id: 9101,
      client_sharepoint_item_id: 'preview-client-1',
      client_name: 'Affréteur Démonstration',
      primary_vessel_id: 9201,
      primary_vessel_sharepoint_item_id: 'preview-vessel-1',
      primary_vessel_name: 'M/V Démonstration',
      secondary_vessel_id: null,
      secondary_vessel_sharepoint_item_id: null,
      secondary_vessel_name: null,
      starts_on: '2026-08-03',
      ends_on: '2026-08-21',
      delivery_at: '2026-08-03T08:00:00+02:00',
      redelivery_at: '2026-08-21T18:00:00+02:00',
      charter_starts_at: '2026-08-03T08:00:00+02:00',
      charter_ends_at: '2026-08-21T18:00:00+02:00',
      delivery_port: 'Brest',
      redelivery_port: 'Brest',
      contract_type: 'SUPPLYTIME 2017',
      operation_area: 'Atlantique Nord',
      is_rov_support: true,
      is_diving_support: false,
      status: 'Contrat signé',
      description: 'Données entièrement synthétiques pour la recette de préversion.',
      source_label: 'sharepoint',
      sharepoint_list_title: 'BBTM - Projets',
      sharepoint_item_id: 'preview-project-1',
      source_modified_at: '2026-07-15T10:00:00Z',
      archived_at: null,
      updated_at: '2026-07-15T10:00:00Z',
    },
    {
      id: 9002,
      title: 'Inspection côtière — démonstration',
      project_code: 'P902',
      client_id: 9102,
      client_sharepoint_item_id: null,
      client_name: 'Client SeaPilot Démonstration',
      primary_vessel_id: 9202,
      primary_vessel_sharepoint_item_id: null,
      primary_vessel_name: 'Support Démonstration',
      secondary_vessel_id: null,
      secondary_vessel_sharepoint_item_id: null,
      secondary_vessel_name: null,
      starts_on: '2026-09-07',
      ends_on: '2026-09-12',
      delivery_at: null,
      redelivery_at: null,
      charter_starts_at: null,
      charter_ends_at: null,
      delivery_port: 'Cherbourg',
      redelivery_port: 'Cherbourg',
      contract_type: 'Prestation',
      operation_area: 'Manche',
      is_rov_support: false,
      is_diving_support: true,
      status: 'Offre transmise',
      description: 'Projet synthétique créé dans SeaPilot pour tester les filtres.',
      source_label: 'seapilot',
      sharepoint_list_title: null,
      sharepoint_item_id: null,
      source_modified_at: null,
      archived_at: null,
      updated_at: '2026-07-15T11:00:00Z',
    },
  ],
  planning_projects: [
    {
      id: 9601,
      catalog_project_id: 9001,
      title: 'P901 - Campagne Atlantique — démonstration',
      starts_on: '2026-08-03',
      ends_on: '2026-08-08',
      description: 'Première rotation synthétique.',
      client_name: 'Affréteur Démonstration',
      primary_vessel_id: 9201,
      primary_vessel_name: 'M/V Démonstration',
      secondary_vessel_id: null,
      secondary_vessel_name: null,
      event_type: 'operation',
      responsible_name: null,
      status: 'Validé',
      source_label: 'seapilot-projects',
      created_at: '2026-07-15T12:00:00Z',
    },
    {
      id: 9602,
      catalog_project_id: 9001,
      title: 'P901 - Campagne Atlantique — démonstration',
      starts_on: '2026-08-14',
      ends_on: '2026-08-21',
      description: 'Seconde rotation synthétique du même projet.',
      client_name: 'Affréteur Démonstration',
      primary_vessel_id: 9201,
      primary_vessel_name: 'M/V Démonstration',
      secondary_vessel_id: null,
      secondary_vessel_name: null,
      event_type: 'operation',
      responsible_name: null,
      status: 'A planifier',
      source_label: 'seapilot-projects',
      created_at: '2026-07-15T12:05:00Z',
    },
    {
      id: 9603,
      catalog_project_id: 9002,
      title: 'P902 - Inspection côtière — démonstration',
      starts_on: '2026-09-07',
      ends_on: '2026-09-12',
      description: 'Occurrence synthétique.',
      client_name: 'Client SeaPilot Démonstration',
      primary_vessel_id: 9202,
      primary_vessel_name: 'Support Démonstration',
      secondary_vessel_id: null,
      secondary_vessel_name: null,
      event_type: 'operation',
      responsible_name: null,
      status: 'A planifier',
      source_label: 'seapilot-projects',
      created_at: '2026-07-15T12:10:00Z',
    },
  ],
  project_contracts: [
    {
      id: 9301,
      project_id: 9001,
      owner_identity: 'Armateur Démonstration',
      vessel_assignment_limit: 'Navire de remplacement soumis à accord',
      extension_count: 1,
      extension_duration: 5,
      extension_unit: 'jours',
      auto_extension_period: null,
      max_extension_days: 5,
      mobilisation_fee: 15000,
      demobilisation_fee: 12500,
      fee_currency: 'EUR',
      charter_hire: 18000,
      extension_hire: 18000,
      hire_currency: 'EUR',
      hire_unit: 'jour',
      max_audit_period: '30 jours',
      supplytime_schema_version: 'supplytime-2017-v1',
      supplytime_data: {
        box05_cancelling_date: '3 août 2026 à 12:00',
        box22_invoice_remittance: 'Facturation mensuelle — démonstration',
        box33_dispute_resolution: 'Droit français — démonstration',
      },
      source_label: 'sharepoint',
      sharepoint_list_title: 'BBTM - Projets',
      sharepoint_item_id: 'preview-project-1',
      source_modified_at: '2026-07-15T10:00:00Z',
      archived_at: null,
    },
  ],
  project_documents: [
    {
      id: 9401,
      project_id: 9001,
      project_sharepoint_item_id: 'preview-project-1',
      project_code: 'P901',
      project_title: 'Campagne Atlantique — démonstration',
      category_key: 'project_document',
      title: 'Plan de mobilisation — démonstration.pdf',
      source_label: 'sharepoint',
      source_sharepoint_id: 'preview-project-document-1',
      file_url: 'https://bbtm668.sharepoint.com/sites/QHSE/Documents%20Projets/Preview-Projet.pdf',
      notes: 'Référence synthétique de préversion ; aucun fichier n’est copié dans SeaPilot.',
      sharepoint_list_id: 'preview-project-library',
      sharepoint_list_title: 'Documents Projets',
      sharepoint_item_id: 'preview-project-document-1',
      sharepoint_drive_id: 'preview-project-drive',
      sharepoint_drive_item_id: 'preview-project-drive-item-1',
      file_name: 'Preview-Projet.pdf',
      folder_path: '/Documents Projets/Démonstration',
      mime_type: 'application/pdf',
      file_extension: 'pdf',
      file_size_bytes: 245760,
      source_modified_at: '2026-07-15T09:00:00Z',
      is_folder: false,
    },
  ],
  contract_documents: [
    {
      id: 9501,
      project_id: 9001,
      project_sharepoint_item_id: 'preview-project-1',
      project_code: 'P901',
      project_title: 'Campagne Atlantique — démonstration',
      category_key: 'contract_document',
      title: 'SUPPLYTIME signé — démonstration.pdf',
      source_label: 'sharepoint',
      source_sharepoint_id: 'preview-contract-document-1',
      file_url: 'https://bbtm668.sharepoint.com/sites/QHSE/Documents%20Contractuels/Preview-Contrat.pdf',
      notes: 'Référence synthétique de préversion.',
      sharepoint_list_id: 'preview-contract-library',
      sharepoint_list_title: 'Documents Contractuels',
      sharepoint_item_id: 'preview-contract-document-1',
      sharepoint_drive_id: 'preview-contract-drive',
      sharepoint_drive_item_id: 'preview-contract-drive-item-1',
      file_name: 'Preview-Contrat.pdf',
      folder_path: '/Documents Contractuels/Démonstration',
      mime_type: 'application/pdf',
      file_extension: 'pdf',
      file_size_bytes: 368640,
      source_modified_at: '2026-07-15T09:30:00Z',
      is_folder: false,
    },
  ],
  clients: [
    {
      id: 9101,
      name: 'Affréteur Démonstration',
      code: 'DEMO-SP',
      email: '',
      phone: '',
      address: '',
      city: 'Brest',
      country: 'France',
      active: true,
      source_label: 'sharepoint',
      sharepoint_list_title: 'BBTM - Clients',
      sharepoint_item_id: 'preview-client-1',
      source_modified_at: '2026-07-15T08:00:00Z',
      archived_at: null,
      updated_at: '2026-07-15T08:00:00Z',
    },
    {
      id: 9102,
      name: 'Client SeaPilot Démonstration',
      code: 'DEMO-SPT',
      email: '',
      phone: '',
      address: '',
      city: 'Cherbourg',
      country: 'France',
      active: true,
      source_label: 'seapilot',
      sharepoint_list_title: null,
      sharepoint_item_id: null,
      source_modified_at: null,
      archived_at: null,
      updated_at: '2026-07-15T11:00:00Z',
    },
  ],
  vessels: [
    { id: 9201, name: 'M/V Démonstration', acronym: 'MVD', active: true, fleet_exit_on: null, sharepoint_item_id: 'preview-vessel-1' },
    { id: 9202, name: 'Support Démonstration', acronym: 'SD', active: true, fleet_exit_on: null, sharepoint_item_id: 'preview-vessel-2' },
  ],
  planning_rotation_series: [],
  planning_rotation_occurrences: [],
  planning_templates: [],
  planning_manning_matrices: [],
  planning_manning_requirements: [],
  stcw_certificates: [
    { id: 1, source_item_id: 1, name: 'Capitaine 500', category: 'Pont', stcw_rules: ['II/3'] },
    { id: 2, source_item_id: 2, name: 'Chef de quart 500', category: 'Pont', stcw_rules: ['II/3'] },
    { id: 3, source_item_id: 3, name: 'Chef mécanicien 750 kW', category: 'Machine', stcw_rules: ['III/3'] },
    { id: 4, source_item_id: 4, name: 'Mécanicien 250 kW', category: 'Machine', stcw_rules: ['III/4'] },
    { id: 5, source_item_id: 5, name: 'Formation de base à la sécurité', category: 'Formation de Sécurité', stcw_rules: ['VI/1'] },
    { id: 6, source_item_id: 6, name: 'Sensibilisation à la sûreté', category: 'Formation de Sécurité', stcw_rules: ['VI/6'] },
    { id: 7, source_item_id: 7, name: 'Qualification navires-citernes', category: 'Navires-citernes', stcw_rules: ['V/1'] },
    { id: 8, source_item_id: 8, name: 'Opérateur SMDSM', category: 'Radiocommunications', stcw_rules: ['IV/2'] },
  ],
};

function createPreviewQuery(result: PreviewResult): object {
  const query: object = new Proxy({}, {
    get(_target, property) {
      if (property === 'then') {
        return (resolve: (value: PreviewResult) => unknown, reject?: (reason: unknown) => unknown) =>
          Promise.resolve(result).then(resolve, reject);
      }

      return () => query;
    },
  });

  return query;
}

export const previewSupabaseClient = {
  from: (table: string) => table in PREVIEW_ROWS
    ? createPreviewQuery({ data: PREVIEW_ROWS[table], error: null })
    : createPreviewQuery({ data: null, error: PREVIEW_WRITE_ERROR }),
  rpc: () => createPreviewQuery({ data: null, error: PREVIEW_WRITE_ERROR }),
} as unknown as SupabaseClient;
