-- Isolated authenticated accounts and notifications; everything is rolled back.
begin;
do $$
declare
 company bigint; person bigint; target_case_id uuid:=gen_random_uuid();
 emitter uuid:=gen_random_uuid(); reviewer uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid(); actor uuid;
 c jsonb; stale_version timestamptz; proposal uuid; proposal2 uuid; role_name text;
 form jsonb:='{"employeeName":"Fixture COLLABORATION","address":"Adresse de test","fault":"simple","sanction":"avertissement","reason":"impregnation_presumee","facts":"Faits datés","evidence":"Témoin","rules":"Consigne","factsOn":"2026-09-15","knownOn":"2026-09-15"}';
 letter jsonb;
begin
 select id into strict company from public.companies where code='bbtm';
 foreach actor in array array[emitter,reviewer,outsider] loop
   role_name:=case when actor=emitter then 'direction' when actor=reviewer then 'admin' else 'marin' end;
   insert into auth.users(id,email) values(actor,actor::text || '@example.invalid');
   insert into public.profiles(id,email,display_name,active_company_id) values(actor,actor::text || '@example.invalid','Fixture ' || role_name,company);
   insert into public.company_memberships(company_id,user_id,active) values(company,actor,true) on conflict(company_id,user_id) do update set active=true;
   insert into public.user_roles(user_id,company_id,role_key) values(actor,company,role_name);
 end loop;
 insert into public.people(company_id,first_name,last_name,function_label,hired_on,active)
 values(company,'Fixture','COLLABORATION','Matelot',current_date-365,true) returning id into person;
 perform set_config('request.jwt.claim.sub',emitter::text,true);
 execute 'set local role authenticated';
 c:=public.disciplinary_mutate('create',target_case_id,null,jsonb_build_object('company_id',company,'person_id',person,'data',form));
 assert c->>'issuer_id'=emitter::text and c->>'workflow_status'='draft', 'Default issuer/draft incorrect';
 begin
   perform public.disciplinary_mutate('share',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('recipients',jsonb_build_array(reviewer)));
   raise exception 'Shared nonexistent letter';
 exception when check_violation then null; end;
 letter:=jsonb_build_object('kind','notification','date','2026-09-15','subject','Objet initial','body','<p>Texte initial</p>',
   'employeeName','Fixture COLLABORATION','address','Adresse de test','emitterName','Faux nom','emitterFunction','Direction','signatureDataUrl','data:image/png;base64,AA==','reviewedForm',form::text);
 c:=public.disciplinary_mutate('save',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('data',form,'letter',letter));
 assert c->'letter'->>'emitterName'='Fixture direction', 'Issuer identity was spoofed';
 begin
   perform public.disciplinary_mutate('share',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('recipients',jsonb_build_array(reviewer,outsider)));
   raise exception 'Shared to forbidden role';
 exception when insufficient_privilege then null; end;
 assert not exists(select 1 from public.disciplinary_participants p where p.case_id=target_case_id), 'Invalid recipient partially shared';
 c:=public.disciplinary_mutate('share',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('recipients',jsonb_build_array(reviewer)));
 assert c->>'workflow_status'='in_review', 'Share state wrong';
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',reviewer::text,true);
 execute 'set local role authenticated';
 assert (select count(*)=1 from public.disciplinary_bell_notifications() n where n.case_id=target_case_id), 'No recipient bell notification';
 update public.disciplinary_notifications n set read_at=clock_timestamp() where n.case_id=target_case_id;
 assert not exists(select 1 from public.disciplinary_bell_notifications() n where n.case_id=target_case_id), 'Read notification remains unread';
 begin update public.disciplinary_cases set letter='{}' where id=target_case_id; raise exception 'Direct write bypassed review'; exception when insufficient_privilege then null; end;
 begin update public.disciplinary_notifications n set title='tampered' where n.case_id=target_case_id; raise exception 'Notification mutable'; exception when insufficient_privilege then null; end;
 c:=public.disciplinary_mutate('save',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('data',form,'letter',(c->'letter') || '{"subject":"Objet proposé","body":"<p><b>Texte proposé</b></p>"}'));
 assert c->'letter'->>'subject'='Objet initial', 'Reviewer overwrote canonical letter';
 select id into strict proposal from public.disciplinary_reviews r where r.case_id=target_case_id and field='subject';
 select id into strict proposal2 from public.disciplinary_reviews r where r.case_id=target_case_id and field='body';
 begin perform public.disciplinary_mutate('resolve',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('review_id',proposal,'decision','accepted')); raise exception 'Reviewer accepted own change'; exception when insufficient_privilege then null; end;
 begin perform public.disciplinary_mutate('validate',target_case_id,(c->>'updated_at')::timestamptz); raise exception 'Reviewer validated'; exception when insufficient_privilege then null; end;
 c:=public.disciplinary_mutate('comment',target_case_id,null,'{"comment":"Commentaire de test"}');
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',emitter::text,true);
 execute 'set local role authenticated';
 assert (select count(*)>=2 from public.disciplinary_bell_notifications() n where n.case_id=target_case_id), 'Emitter not notified of comment/proposals';
 begin perform public.disciplinary_mutate('validate',target_case_id,(c->>'updated_at')::timestamptz); raise exception 'Pending changes ignored'; exception when check_violation then null; end;
 c:=public.disciplinary_mutate('resolve',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('review_id',proposal,'decision','accepted'));
 assert c->'letter'->>'subject'='Objet proposé', 'Accepted field not applied';
 assert c->'letter'->>'body'='<p>Texte initial</p>', 'Unaccepted field applied';
 c:=public.disciplinary_mutate('resolve',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('review_id',proposal2,'decision','rejected'));
 assert c->'letter'->>'body'='<p>Texte initial</p>', 'Rejected field applied';
 begin perform public.disciplinary_mutate('resolve',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('review_id',proposal2,'decision','accepted')); raise exception 'Decision replay allowed'; exception when check_violation then null; end;
 stale_version:=(c->>'updated_at')::timestamptz;
 c:=public.disciplinary_mutate('save',target_case_id,stale_version,jsonb_build_object('data',form,'letter',(c->'letter') || '{"body":"<p>Correction émetteur</p>"}'));
 begin perform public.disciplinary_mutate('save',target_case_id,stale_version,jsonb_build_object('data',form,'letter',letter)); raise exception 'Stale write applied'; exception when serialization_failure then null; end;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',reviewer::text,true);
 execute 'set local role authenticated';
 c:=public.disciplinary_mutate('save',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('data',form,'letter',(c->'letter') || '{"subject":"Proposition concurrente"}'));
 select id into strict proposal from public.disciplinary_reviews r where r.case_id=target_case_id and status='pending' and kind='change';
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',emitter::text,true);
 execute 'set local role authenticated';
 c:=public.disciplinary_mutate('save',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('data',form,'letter',(c->'letter') || '{"subject":"Nouvel objet émetteur"}'));
 begin perform public.disciplinary_mutate('resolve',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('review_id',proposal,'decision','accepted')); raise exception 'Conflicting field overwritten'; exception when serialization_failure then null; end;
 c:=public.disciplinary_mutate('resolve',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('review_id',proposal,'decision','rejected'));
 begin perform public.disciplinary_mutate('issuer',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('issuer_id',outsider)); raise exception 'Marin became issuer'; exception when insufficient_privilege then null; end;
 c:=public.disciplinary_mutate('issuer',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('issuer_id',reviewer));
 assert c->'letter'->>'signatureDataUrl'='' and c->'letter'->>'emitterName'='Fixture admin', 'Transfer retained former identity/signature';
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',reviewer::text,true);
 execute 'set local role authenticated';
 begin perform public.disciplinary_mutate('validate',target_case_id,(c->>'updated_at')::timestamptz); raise exception 'Unsigned validation allowed'; exception when check_violation then null; end;
 c:=public.disciplinary_mutate('save',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('data',form,'letter',(c->'letter') || '{"emitterFunction":"Administration","signatureDataUrl":"data:image/png;base64,AA=="}'));
 begin insert into public.disciplinary_documents(case_id,file_name,drive_path,document_date,kind,letter_snapshot) values(target_case_id,'draft.docx','fixture/draft.docx',current_date,'letter',c->'letter'); raise exception 'Unvalidated final archive allowed'; exception when check_violation then null; end;
 c:=public.disciplinary_mutate('validate',target_case_id,(c->>'updated_at')::timestamptz);
 assert c->>'workflow_status'='validated' and c->>'validated_by'=reviewer::text, 'Validation not recorded';
 begin perform public.disciplinary_mutate('save',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('data',form,'letter',letter)); raise exception 'Validated letter editable'; exception when check_violation then null; end;
 begin perform public.disciplinary_mutate('issuer',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('issuer_id',emitter)); raise exception 'Validated issuer changed'; exception when check_violation then null; end;
 insert into public.disciplinary_documents(case_id,file_name,drive_path,document_date,kind,letter_snapshot) values(target_case_id,'final.docx','fixture/final.docx',current_date,'letter',c->'letter');
 insert into public.disciplinary_documents(case_id,file_name,drive_path,document_date,kind) values(target_case_id,'piece.pdf','fixture/piece.pdf',current_date,'attachment');
 begin insert into public.disciplinary_documents(case_id,file_name,drive_path,document_date,kind,letter_snapshot) values(target_case_id,'altered.docx','fixture/altered.docx',current_date,'letter',letter); raise exception 'Altered archive allowed'; exception when check_violation then null; end;
 perform public.disciplinary_mutate('procedure',target_case_id,null,'{"step":"notification_sent","date":"2026-09-15","note":"Remise de test"}');
 assert exists(select 1 from public.disciplinary_events e where e.case_id=target_case_id and kind='procedure'), 'Postvalidation follow-up denied';
 assert (select count(*)=1 from public.disciplinary_validated_letters l where l.case_id=target_case_id), 'Validated history not stored';
 begin update public.disciplinary_validated_letters l set letter='{}' where l.case_id=target_case_id; raise exception 'Validated history mutable'; exception when insufficient_privilege then null; end;
 c:=public.disciplinary_start_letter(target_case_id,(c->>'updated_at')::timestamptz);
 assert c->>'workflow_status'='draft' and c->'letter'='null'::jsonb, 'Next letter not started';
 assert (select count(*)=1 from public.disciplinary_validated_letters l where l.case_id=target_case_id), 'Next draft erased validation history';
 insert into public.disciplinary_documents(case_id,file_name,drive_path,document_date,kind,letter_snapshot)
 select target_case_id,'previous.docx','fixture/previous.docx',current_date,'letter',l.letter from public.disciplinary_validated_letters l where l.case_id=target_case_id;
 c:=public.disciplinary_mutate('save',target_case_id,(c->>'updated_at')::timestamptz,jsonb_build_object('data',form,'letter',letter));
 assert (select l.letter->>'subject'='Nouvel objet émetteur' from public.disciplinary_validated_letters l where l.case_id=target_case_id), 'Next draft changed previous letter';
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',outsider::text,true);
 execute 'set local role authenticated';
 assert not exists(select 1 from public.disciplinary_reviews r where r.case_id=target_case_id), 'Reviews leaked to Marin';
 assert not exists(select 1 from public.disciplinary_events e where e.case_id=target_case_id), 'Events leaked to Marin';
 assert not exists(select 1 from public.disciplinary_notifications n where n.case_id=target_case_id), 'Notifications leaked to Marin';
 begin perform public.disciplinary_mutate('comment',target_case_id,null,'{"comment":"Forbidden"}'); raise exception 'Marin commented'; exception when insufficient_privilege then null; end;
 begin perform public.disciplinary_reviewers(company); raise exception 'Directory leaked'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 update public.company_memberships set active=false where user_id=emitter and company_id=company;
 perform set_config('request.jwt.claim.sub',emitter::text,true);
 execute 'set local role authenticated';
 assert not exists(select 1 from public.disciplinary_bell_notifications() n where n.case_id=target_case_id), 'Inactive account notifications leaked';
 begin perform public.disciplinary_mutate('comment',target_case_id,null,'{"comment":"Revoked"}'); raise exception 'Inactive account wrote'; exception when insufficient_privilege then null; end;
 execute 'reset role';
end $$;
select 'PASS: atomic proposals, emitter decisions, conflicts, private notifications, transfer, validation lock, final archive and procedure follow-up' as result;
rollback;
