export type SharePointSourceType = 'list' | 'library' | 'lookup' | 'external_link';

export interface SharePointMigrationSource {
  key: string;
  title: string;
  sourceType: SharePointSourceType;
  moduleKey: string;
  relatedModuleKeys?: string[];
  siteUrl: string;
  driveId?: string;
  listId?: string;
  serverRelativeUrl?: string;
  browserUrl?: string;
  targetTable?: string;
  importPriority: number;
  notes?: string;
}

export interface SharePointImportStep {
  key: string;
  label: string;
  targetTables: string[];
}

export const SHAREPOINT_SITE_URL = 'https://bbtm668.sharepoint.com/sites/QHSE';

export const SHAREPOINT_RECONCILIATION_COLUMNS = [
  'sharepoint_site_url',
  'sharepoint_list_id',
  'sharepoint_list_title',
  'sharepoint_item_id',
  'sharepoint_unique_id',
  'sharepoint_file_ref',
  'sharepoint_encoded_abs_url',
  'source_modified_at',
] as const;

const DOCUMENT_LIBRARY_SOURCES: SharePointMigrationSource[] = [
  {
    key: 'library-logos-systeme',
    title: 'Logos_Systeme',
    sourceType: 'library',
    moduleKey: 'assets',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_OpWjZZ3tZsSZsJCs7hACGw',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Logos_Systeme',
    targetTable: 'document_assets',
    importPriority: 10,
  },
  {
    key: 'library-qsms',
    title: 'QSMS',
    sourceType: 'library',
    moduleKey: 'procedures',
    relatedModuleKeys: ['dpr'],
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_ML9YyVmncCQIEcDti7Qfe1',
    listId: '958cf50b-779a-4002-811c-0ed8bb41f7b5',
    serverRelativeUrl: '/sites/QHSE/QSMS',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/QSMS',
    targetTable: 'procedures',
    importPriority: 50,
  },
  {
    key: 'library-vehicules',
    title: 'Vehicules',
    sourceType: 'library',
    moduleKey: 'fleet',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_MVOaWxW3m4TaRaHxYv5oSN',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Vhicules',
    targetTable: 'fleet_documents',
    importPriority: 70,
  },
  {
    key: 'library-permis-travail',
    title: 'Permis de Travail',
    sourceType: 'library',
    moduleKey: 'qhse',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_Ps3Dtm4LyKR6K4I4H7P9e_',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Permis%20de%20Travail',
    targetTable: 'work_permits',
    importPriority: 80,
  },
  {
    key: 'library-dpr',
    title: 'DPR',
    sourceType: 'library',
    moduleKey: 'dpr',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_PdxO_2G3U9Qp6tLqHQRY59',
    listId: 'f6efc4dd-751b-423d-9ead-2ea1d0458e7d',
    serverRelativeUrl: '/sites/QHSE/DPR',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/DPR',
    targetTable: 'dpr_archives',
    importPriority: 60,
  },
  {
    key: 'library-certificats-flotte',
    title: 'Certificats Flotte BBTM',
    sourceType: 'library',
    moduleKey: 'certificates',
    relatedModuleKeys: ['planning'],
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_PaPPP_2iCbSotVRmMO5eiw',
    listId: 'fff33cda-20da-4a9b-8b55-46630ee5e8b0',
    serverRelativeUrl: '/sites/QHSE/Certificats%20Flotte%20BBTM',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Certificats%20Flotte%20BBTM',
    targetTable: 'fleet_certificates',
    importPriority: 50,
  },
  {
    key: 'library-fiche-progres',
    title: 'Fiche de Progres',
    sourceType: 'library',
    moduleKey: 'actionPlan',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_Mj5CrSdglTRb4MaXXyMXJH',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Fiche%20de%20Progrs',
    targetTable: 'action_documents',
    importPriority: 90,
  },
  {
    key: 'library-suivi-temps-travail',
    title: 'Suivi du Temps de Travail',
    sourceType: 'library',
    moduleKey: 'humanResources',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_Ou6ZoCxQsvRqr8gJTNvSGV',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Suivi%20du%20Temps%20de%20Travail',
    targetTable: 'work_time_documents',
    importPriority: 95,
  },
  {
    key: 'library-archive-documentaire',
    title: 'Archive Documentaire',
    sourceType: 'library',
    moduleKey: 'documents',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_NwHhKNAtGiS5T4iB5KLSdP',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Archive%20Documentaire',
    targetTable: 'document_archive',
    importPriority: 120,
  },
  {
    key: 'library-documents-projets',
    title: 'Documents Projets',
    sourceType: 'library',
    moduleKey: 'projects',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFywFKhPc9dkTkf_Ou31l1uVoWRrtjl4GcYGNl',
    listId: '7559dfae-5ab9-4616-bb63-97819c606365',
    serverRelativeUrl: '/sites/QHSE/Documents%20Projets',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Documents%20Projets',
    targetTable: 'project_documents',
    importPriority: 100,
  },
  {
    key: 'library-brevets-visites-medicales',
    title: 'Brevets et Visites Medicales',
    sourceType: 'library',
    moduleKey: 'humanResources',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_MxKjjFptv3QpsTtkjX4xBr',
    listId: 'c5382a31-dba6-42f7-9b13-b648d7e3106b',
    serverRelativeUrl: '/sites/QHSE/Brevets%20et%20Visites%20Mdicales',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Brevets%20et%20Visites%20Mdicales',
    targetTable: 'hr_documents',
    importPriority: 40,
  },
  {
    key: 'library-documents-contractuels',
    title: 'Documents Contractuels',
    sourceType: 'library',
    moduleKey: 'projects',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFywFKhPc9dkTkf_OWUUcnVo9hTIk_y0nRfdyl',
    listId: '27475196-8f56-4c61-893f-cb49d17ddca5',
    serverRelativeUrl: '/sites/QHSE/Documents Contractuels',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Documents%20Contractuels',
    targetTable: 'contract_documents',
    importPriority: 100,
  },
  {
    key: 'library-notes-service',
    title: 'Notes de Service',
    sourceType: 'library',
    moduleKey: 'documents',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_PzEaXMIXBnQac4z9Bfn0AS',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Notes%20de%20Service',
    targetTable: 'service_notes',
    importPriority: 115,
  },
  {
    key: 'library-qsms-pdf',
    title: 'QSMS - PDF',
    sourceType: 'library',
    moduleKey: 'procedures',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_P51Zwapnf8RYcF01AFcpd0',
    listId: '1a9cd5f9-77a6-45fc-8705-d35005729774',
    serverRelativeUrl: '/sites/QHSE/QSMS%20%20PDF',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/QSMS%20%20PDF',
    targetTable: 'published_procedures',
    importPriority: 55,
  },
  {
    key: 'library-alerte-securite',
    title: 'Alerte Securite',
    sourceType: 'library',
    moduleKey: 'qhse',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_PrBPRtCQLYTZnX40aQXEEw',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Alerte%20Scurit',
    targetTable: 'safety_alerts',
    importPriority: 85,
  },
  {
    key: 'library-documentation-technique',
    title: 'Documentation Technique',
    sourceType: 'library',
    moduleKey: 'maintenance',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_N1vCc4AjvBTp0F6ucDchlT',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Documentation%20Technique',
    targetTable: 'technical_documents',
    importPriority: 100,
  },
  {
    key: 'library-fiche-navire-equipement',
    title: 'Fiche Navire / Equipement',
    sourceType: 'library',
    moduleKey: 'maintenance',
    relatedModuleKeys: ['fleet'],
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_OQ_OYJbt-iQIXI7zbswTBI',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Fiche%20Navire%20%20Equipement',
    targetTable: 'vessel_equipment_documents',
    importPriority: 90,
  },
  {
    key: 'library-registre-apparaux-levage',
    title: 'Registre des Apparaux de Levage - Rapports',
    sourceType: 'library',
    moduleKey: 'lifting',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_ObdT_qMKkoToMJ-tmxTuel',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Registre%20des%20Apparaux%20de%20Levage%20%20Rapports',
    targetTable: 'lifting_reports',
    importPriority: 90,
  },
  {
    key: 'library-documents-partages',
    title: 'Documents',
    sourceType: 'library',
    moduleKey: 'documents',
    siteUrl: SHAREPOINT_SITE_URL,
    driveId: 'b!j0eX05ggd0iS7a1x5WccnspY9pQFKhPc9dkTkf_NP6M6l0cHfTa_D_bfxAB9T',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Documents%20partages',
    targetTable: 'shared_documents',
    importPriority: 120,
  },
];

const CRITICAL_APPLICATION_SOURCES: SharePointMigrationSource[] = [
  {
    key: 'list-administration-prestataires-fournisseurs',
    title: 'Administration - Prestataires - Fournisseurs',
    sourceType: 'list',
    moduleKey: 'planning',
    relatedModuleKeys: ['administration'],
    siteUrl: SHAREPOINT_SITE_URL,
    listId: '5e29f7db-a85e-4147-9c54-b00f0e588f7e',
    serverRelativeUrl: '/sites/QHSE/Lists/Fournisseurs',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Lists/Fournisseurs/AllItems.aspx',
    targetTable: 'service_providers',
    importPriority: 12,
    notes: 'Source IQY vérifiée le 23/07/2026 ; importer toutes les lignes, y compris les catégories non renseignées.',
  },
  {
    key: 'list-kpi-definitions',
    title: 'Dashboard - KPI Definitions',
    sourceType: 'list',
    moduleKey: 'kpi',
    siteUrl: SHAREPOINT_SITE_URL,
    targetTable: 'kpi_definitions',
    importPriority: 180,
    notes: 'List ID must be exported live.',
  },
  {
    key: 'list-indicateurs-projet-p144emdt',
    title: 'Indicateurs Projet P144EMDT',
    sourceType: 'list',
    moduleKey: 'dpr',
    siteUrl: SHAREPOINT_SITE_URL,
    listId: '3c26ee87-5f55-4018-a93e-634080cfc55e',
    serverRelativeUrl: '/sites/QHSE/Lists/Indicateurs Projet  P144EMDT',
    targetTable: 'dpr_items',
    importPriority: 120,
  },
  {
    key: 'list-demande-achat',
    title: "Demande d'Achat",
    sourceType: 'list',
    moduleKey: 'purchaseRequests',
    siteUrl: SHAREPOINT_SITE_URL,
    targetTable: 'purchase_requests',
    importPriority: 140,
    notes: 'List ID and exact choice values must be exported live.',
  },
  {
    key: 'list-audit',
    title: 'Audit',
    sourceType: 'list',
    moduleKey: 'actionPlan',
    relatedModuleKeys: ['qhse'],
    siteUrl: SHAREPOINT_SITE_URL,
    serverRelativeUrl: '/sites/QHSE/Lists/Audit',
    targetTable: 'action_items',
    importPriority: 140,
    notes: 'List ID and choice values must be exported live.',
  },
  {
    key: 'list-rh-personnel-bbtm',
    title: 'RH - Personnel BBTM',
    sourceType: 'list',
    moduleKey: 'humanResources',
    relatedModuleKeys: ['planning', 'dpr'],
    siteUrl: SHAREPOINT_SITE_URL,
    listId: '3b6f504c-908a-4d3e-8319-a595acb54efe',
    serverRelativeUrl: '/sites/QHSE/Lists/RH%20%20Personnel%20BBTM',
    browserUrl: 'https://bbtm668.sharepoint.com/sites/QHSE/Lists/RH Personnel BBTM/Personnel Actif.aspx',
    targetTable: 'people',
    importPriority: 20,
  },
  {
    key: 'lookup-brevet',
    title: 'Brevet',
    sourceType: 'lookup',
    moduleKey: 'humanResources',
    siteUrl: SHAREPOINT_SITE_URL,
    targetTable: 'stcw_certificates',
    importPriority: 10,
    notes: 'Lookup target must be exported from BrevetPont field metadata.',
  },
  {
    key: 'list-bbtm-flotte',
    title: 'BBTM - Flotte',
    sourceType: 'list',
    moduleKey: 'fleet',
    relatedModuleKeys: ['planning', 'certificates', 'actionPlan', 'projects'],
    siteUrl: SHAREPOINT_SITE_URL,
    listId: '543b9f00-aed2-489a-808a-7b64cc835a83',
    serverRelativeUrl: '/sites/QHSE/Lists/BBTM%20%20Flotte',
    targetTable: 'vessels',
    importPriority: 10,
  },
  {
    key: 'list-kpi-projets-planning',
    title: 'KPI - Projets-Planning',
    sourceType: 'list',
    moduleKey: 'planning',
    relatedModuleKeys: ['projects'],
    siteUrl: SHAREPOINT_SITE_URL,
    listId: 'e1c7e91f-8fb3-4b2e-9c9a-015396cf49c9',
    serverRelativeUrl: '/sites/QHSE/Lists/KPI ProjetsPlanning',
    targetTable: 'planning_projects',
    importPriority: 30,
  },
  {
    key: 'list-bbtm-projets',
    title: 'BBTM - Projets',
    sourceType: 'list',
    moduleKey: 'projects',
    relatedModuleKeys: ['dpr', 'planning'],
    siteUrl: SHAREPOINT_SITE_URL,
    listId: '6abf8928-acfd-47ec-a848-29e4071249fc',
    serverRelativeUrl: '/sites/QHSE/Lists/BBTM  Projets',
    targetTable: 'projects',
    importPriority: 130,
    notes: 'List ID and all editable fields must be exported live.',
  },
  {
    key: 'list-bbtm-clients',
    title: 'BBTM Clients / BBTM - Clients',
    sourceType: 'list',
    moduleKey: 'projects',
    siteUrl: SHAREPOINT_SITE_URL,
    listId: 'eacbc0c3-1028-44bf-975b-ed50f762943d',
    serverRelativeUrl: '/sites/QHSE/Lists/BBTM Clients',
    targetTable: 'clients',
    importPriority: 10,
    notes: 'Historic alias: /sites/QHSE/Lists/BBTM  Clients.',
  },
  {
    key: 'list-remorque',
    title: 'Remorque',
    sourceType: 'list',
    moduleKey: 'projects',
    siteUrl: SHAREPOINT_SITE_URL,
    listId: '585151b0-190c-4634-b534-74aac6cd8400',
    serverRelativeUrl: '/sites/QHSE/Lists/Remorqu',
    targetTable: 'towage_options',
    importPriority: 15,
  },
  {
    key: 'list-smtr-journees-planning',
    title: 'SMTR - Journees - Planning',
    sourceType: 'list',
    moduleKey: 'planning',
    siteUrl: SHAREPOINT_SITE_URL,
    listId: 'e711a664-6c52-4e4e-95cc-0843ac7c5253',
    targetTable: 'planning_days',
    importPriority: 40,
  },
  {
    key: 'list-smtr-planning-periodes',
    title: 'SMTR - Planning Periodes',
    sourceType: 'list',
    moduleKey: 'planning',
    siteUrl: SHAREPOINT_SITE_URL,
    listId: 'c03eb1f4-1d24-4d86-b91e-9afaaa45870b',
    targetTable: 'planning_periods',
    importPriority: 41,
  },
  {
    key: 'list-mgo',
    title: 'MGO',
    sourceType: 'list',
    moduleKey: 'dpr',
    siteUrl: SHAREPOINT_SITE_URL,
    targetTable: 'mgo_prices',
    importPriority: 10,
    notes: 'List ID must be exported live.',
  },
];

export const SHAREPOINT_MIGRATION_SOURCES = [
  ...CRITICAL_APPLICATION_SOURCES,
  ...DOCUMENT_LIBRARY_SOURCES,
] as const satisfies readonly SharePointMigrationSource[];

export const SHAREPOINT_IMPORT_ORDER: readonly SharePointImportStep[] = [
  {
    key: 'catalogs',
    label: 'Catalogues',
    targetTables: ['roles', 'modules', 'vessels', 'clients', 'stcw_certificates'],
  },
  {
    key: 'personnel',
    label: 'Personnel',
    targetTables: ['people'],
  },
  {
    key: 'planning',
    label: 'Planning',
    targetTables: ['service_providers', 'planning_assignments', 'planning_days', 'planning_periods', 'planning_projects'],
  },
  {
    key: 'hr-documents-certificates',
    label: 'Documents RH et certificats',
    targetTables: ['hr_documents', 'fleet_certificates'],
  },
  {
    key: 'procedures',
    label: 'Procedures QHSE',
    targetTables: ['procedures', 'published_procedures'],
  },
  {
    key: 'dpr',
    label: 'Daily Progress Report',
    targetTables: ['dpr_items', 'dpr_archives', 'mgo_prices'],
  },
  {
    key: 'operations',
    label: 'Achats, audit, projets et contrats',
    targetTables: ['purchase_requests', 'action_items', 'projects', 'contract_documents'],
  },
  {
    key: 'kpi-definitions',
    label: 'Definitions KPI',
    targetTables: ['kpi_definitions'],
  },
];

export function getSharePointSourceByKey(key: string): SharePointMigrationSource | undefined {
  return SHAREPOINT_MIGRATION_SOURCES.find((source) => source.key === key);
}

export function getSharePointSourcesByModule(moduleKey: string): SharePointMigrationSource[] {
  return SHAREPOINT_MIGRATION_SOURCES.filter(
    (source) => source.moduleKey === moduleKey || source.relatedModuleKeys?.includes(moduleKey),
  ).sort((left, right) => left.importPriority - right.importPriority || left.key.localeCompare(right.key));
}

export function getSharePointImportOrder(): readonly SharePointImportStep[] {
  return SHAREPOINT_IMPORT_ORDER;
}
