// Generated by scripts/prepare-bbtm-fleet-thumbnails.py. Edit the source JSON.
// Originals live in private fleet-media; only these small thumbnails are public.
export const BBTM_FLEET_PHOTOS = [
  {
    "name": "GOURY",
    "acronym": "GRY",
    "file": "GOURY.png",
    "slug": "goury",
    "width": 256,
    "height": 171,
    "thumbnail": "goury-16db2dd97c49c0d1.webp",
    "thumbnailBytes": 3900,
    "thumbnailSha256": "16db2dd97c49c0d1f588d120b22dfa59e4ab21afd955c6a41ae4f7b4d30c6d7b",
    "originalSha256": "14680d2f35fe1ac9bb49d5d1b5f3043836b887ca2fdfc2c63ad2ad84e333fca0"
  },
  {
    "name": "HIRONDELLE DE LA MANCHE",
    "acronym": "HIR",
    "file": "HIRONDELLE DE LA MANCHE.png",
    "slug": "hirondelle-de-la-manche",
    "width": 256,
    "height": 171,
    "thumbnail": "hirondelle-de-la-manche-e008f84bdc79613d.webp",
    "thumbnailBytes": 4640,
    "thumbnailSha256": "e008f84bdc79613df4762840f5eddaaba0636043d516a0a1734f903ebfc8e1ed",
    "originalSha256": "37c0a9505d6d5ff1f4b2d9204b3f685d98637c28040114649e9bfc151e99314f"
  },
  {
    "name": "HOLENN EUSA",
    "acronym": "HE",
    "file": "HOLENN EUSA.png",
    "slug": "holenn-eusa",
    "width": 256,
    "height": 171,
    "thumbnail": "holenn-eusa-a58479314da86f33.webp",
    "thumbnailBytes": 3468,
    "thumbnailSha256": "a58479314da86f33219f6c3891177cf88f624032c5bf6352171c2e85a88cd430",
    "originalSha256": "d950a44236614b3fb3ed3ae1c45b3b72be6c883998ea2cc9d2c9244a4a2dd79c"
  },
  {
    "name": "KROKDUR",
    "acronym": "KDR",
    "file": "KROKDUR.png",
    "slug": "krokdur",
    "width": 256,
    "height": 171,
    "thumbnail": "krokdur-83f6595800a0f5a2.webp",
    "thumbnailBytes": 4046,
    "thumbnailSha256": "83f6595800a0f5a20c2670025b2b0b4768849b5bb4b9eb5c3771b0f73f2a2523",
    "originalSha256": "978a66cf8d091b32ad772dd615b5512e99a67383dbba0878cd198d1f0209682a"
  },
  {
    "name": "LANDEMER",
    "acronym": "LDM",
    "file": "LANDEMER.png",
    "slug": "landemer",
    "width": 256,
    "height": 171,
    "thumbnail": "landemer-b94b581eb9aa6963.webp",
    "thumbnailBytes": 4622,
    "thumbnailSha256": "b94b581eb9aa6963f5707e2800a4561c5cb8ee2efc1dbcda2259a293f0e2c71e",
    "originalSha256": "a0bbe566c9dbb524d0816c4594c925494700376d3877aa766e4462e4bda199ce"
  },
  {
    "name": "LE ROZEL",
    "acronym": "RZL",
    "file": "LE ROZEL.PNG",
    "slug": "le-rozel",
    "width": 256,
    "height": 171,
    "thumbnail": "le-rozel-3c8091c52b07b31c.webp",
    "thumbnailBytes": 4128,
    "thumbnailSha256": "3c8091c52b07b31c4ea3b78e97992531f5f909f48c195443a3c95959ed090e27",
    "originalSha256": "1dca05bb04b44aa1df374505e7eb04ae812c1fd616df1b83ef96b72b1371c820"
  },
  {
    "name": "SUROIT",
    "acronym": "SUR",
    "file": "SUROIT.png",
    "slug": "suroit",
    "width": 256,
    "height": 171,
    "thumbnail": "suroit-317a5af7fe92dcf5.webp",
    "thumbnailBytes": 4806,
    "thumbnailSha256": "317a5af7fe92dcf5f6696d9ded45330cf5d73f5636e3de09393a8973ef3a5d3b",
    "originalSha256": "13ffa6ebf761175a80fb9fd8595d7d94c48d1c136011a2225672c64f9beee4e5"
  },
  {
    "name": "BBTM TENDER 1",
    "acronym": "TND",
    "file": "Tender 1.png",
    "slug": "tender-1",
    "width": 256,
    "height": 171,
    "thumbnail": "tender-1-5d06af9f41f3c235.webp",
    "thumbnailBytes": 3944,
    "thumbnailSha256": "5d06af9f41f3c235660b8c335f990bf30992545577c8454445e490240dd6bdc0",
    "originalSha256": "7c49e13a038c3c438588cc3e415079ca4be6da427d148514fbe8cdc194758e76"
  },
  {
    "name": "YARD - Le Havre",
    "acronym": "YRD",
    "file": "Yard - LE HAVRE.png",
    "slug": "yard-le-havre",
    "width": 256,
    "height": 171,
    "thumbnail": "yard-le-havre-fceb33d96f9e6529.webp",
    "thumbnailBytes": 6374,
    "thumbnailSha256": "fceb33d96f9e6529c266331c35ebd5825d3dfb2d8c7893772e9be1980dbeb1b0",
    "originalSha256": "8983f2bb031561aaa43db30a2a3c6250566a2bbae63539b7ebb3c5e6c5b5082f"
  }
] as const;

export function fleetCatalogThumbnailPath(photo: { thumbnail: string }): string {
  return `/vessels/bbtm/${photo.thumbnail}`;
}
