import { addPlanningDays } from './planningDates';
import type { PlanningOverview, PlanningPerson } from './planningQueries';

function previewPerson(
  id: number,
  firstName: string,
  lastName: string,
  functionLabel: string,
  options: { departedOn?: string; active?: boolean; contractType?: string } = {},
): PlanningPerson {
  return {
    id,
    firstName,
    lastName,
    functionLabel,
    gradeLabel: functionLabel,
    roleLabel: 'Marin',
    sailorNumber: `20${String(id).padStart(6, '0')}`,
    contractType: options.contractType || 'CDI',
    hiredOn: '2024-01-01',
    departedOn: options.departedOn || '',
    birthDate: '1990-01-15',
    deckCertificateLabel: /capitaine|matelot/i.test(functionLabel) ? 'Capitaine 200' : '',
    engineCertificateLabel: /mecan/i.test(functionLabel) ? 'Mécanicien 250 kW' : '',
    active: options.active ?? true,
  };
}

export function createPlanningPreviewOverview(anchorDate: string): PlanningOverview {
  const people = [
    previewPerson(101, 'Pierre', 'LEPRETRE', 'Capitaine'),
    previewPerson(102, 'Pierre', 'HARACHE', 'Chef Mécanicien'),
    previewPerson(103, 'Boris', 'BROT', '2nd Capitaine', { contractType: 'CDD', departedOn: '2026-12-31' }),
    previewPerson(104, 'Emilien', 'LAFFAITEUR', 'Matelot polyvalent'),
    previewPerson(105, 'Alexandre', 'ROUPSARD', 'Matelot Qualifié'),
    previewPerson(106, 'David', 'FIDELIN', 'Capitaine'),
    previewPerson(107, 'Mathieu', 'RIDARD', 'Chef Mécanicien'),
    previewPerson(108, 'Nicolas', 'BOUVILLE', 'Matelot polyvalent'),
    previewPerson(109, 'Adrien', 'BOIS', 'Capitaine'),
    previewPerson(110, 'Matthieu', 'DURAND', "Maître d'Equipage"),
    previewPerson(111, 'Sophie', 'HAMEL', 'Directrice Administrative et Financière'),
    previewPerson(112, 'Christophe', 'MINASSIAN', 'Directeur QHSE / Chef de Projet'),
    previewPerson(113, 'Alain', 'ANCIEN', 'Stagiaire', { active: false }),
    previewPerson(114, 'Camille', 'FUTURE', 'Président', { departedOn: '2099-12-31', active: false }),
    previewPerson(115, 'Étienne', 'PASSÉ', 'Matelot', { departedOn: '2000-01-01', active: false }),
    previewPerson(116, 'Benjamin', 'BON', 'Président'),
    previewPerson(117, 'Adam', 'DEBORDEAUX', 'Stagiaire'),
    previewPerson(118, 'Équipages', 'GOURY', ''),
  ];
  const firstWatchStart = addPlanningDays(anchorDate, -14);
  const firstWatchEnd = addPlanningDays(anchorDate, 14);
  const secondWatchStart = addPlanningDays(anchorDate, 15);
  const secondWatchEnd = addPlanningDays(anchorDate, 43);
  const officeStart = addPlanningDays(anchorDate, -10);
  const officeEnd = addPlanningDays(anchorDate, 10);

  return {
    vessels: [
      { id: 1, name: 'GOURY', acronym: 'GY', registrationNumber: '934968', active: true },
      { id: 2, name: 'ARMEMENT - CHERBOURG', acronym: 'ARM', active: true },
      { id: 3, name: 'NAVIRES SANS EQUIPAGE', acronym: 'VIDE', active: true },
    ],
    people,
    boardRows: [{
      id: 1201,
      vesselId: 1,
      personId: 113,
      watchGroup: 'Bordée 2',
      functionLabel: 'Matelot',
      createdAt: `${anchorDate}T08:00:00Z`,
    }],
    assignments: [
      ...[101, 102, 103, 104, 105].map((personId, index) => ({
        id: 1000 + index,
        vesselId: 1,
        vesselName: 'GOURY',
        captainPersonId: 101,
        captainName: 'Pierre LEPRETRE',
        crewPersonId: personId,
        crewName: `${people.find((person) => person.id === personId)?.firstName} ${people.find((person) => person.id === personId)?.lastName}`,
        startsOn: firstWatchStart,
        endsOn: firstWatchEnd,
        startsAt: `${firstWatchStart}T08:00:00Z`,
        endsAt: `${firstWatchEnd}T18:00:00Z`,
        assignmentRole: people.find((person) => person.id === personId)?.functionLabel || 'Équipage',
        statusLabel: 'En Mer',
        confirmationStatus: 'confirmed' as const,
        watchGroup: 'Bordée 1',
        comments: 'Embarqué',
        sourceLabel: 'preview',
      })),
      ...[106, 107, 108, 109, 110].map((personId, index) => ({
        id: 1100 + index,
        vesselId: 1,
        vesselName: 'GOURY',
        captainPersonId: 106,
        captainName: 'David FIDELIN',
        crewPersonId: personId,
        crewName: `${people.find((person) => person.id === personId)?.firstName} ${people.find((person) => person.id === personId)?.lastName}`,
        startsOn: secondWatchStart,
        endsOn: secondWatchEnd,
        startsAt: `${secondWatchStart}T08:00:00Z`,
        endsAt: `${secondWatchEnd}T18:00:00Z`,
        assignmentRole: personId === 109
          ? '2nd Capitaine'
          : people.find((person) => person.id === personId)?.functionLabel || 'Équipage',
        statusLabel: 'En Mer',
        confirmationStatus: 'confirmed' as const,
        watchGroup: 'Bordée 2',
        comments: 'Embarqué',
        sourceLabel: 'preview',
      })),
      {
        id: 1200,
        vesselId: 2,
        vesselName: 'ARMEMENT - CHERBOURG',
        captainPersonId: null,
        captainName: '',
        crewPersonId: 103,
        crewName: 'Boris BROT',
        startsOn: officeStart,
        endsOn: officeEnd,
        startsAt: `${officeStart}T08:00:00Z`,
        endsAt: `${officeEnd}T18:00:00Z`,
        assignmentRole: 'Opération spéciale',
        statusLabel: 'À Terre',
        confirmationStatus: 'provisional',
        watchGroup: 'Équipe bureau',
        comments: 'Opération spéciale',
        sourceLabel: 'preview',
      },
    ],
    days: [
      {
        id: 5001,
        personId: 101,
        vesselId: 1,
        crewName: 'Pierre LEPRETRE',
        captainName: 'Pierre LEPRETRE',
        vesselName: 'GOURY',
        workDate: addPlanningDays(anchorDate, -2),
        disembarkOn: '',
        yearNumber: Number(addPlanningDays(anchorDate, -2).slice(0, 4)),
        monthNumber: Number(addPlanningDays(anchorDate, -2).slice(5, 7)),
        monthLabel: '',
        dayNumber: Number(addPlanningDays(anchorDate, -2).slice(8, 10)),
        functionLabel: 'Capitaine',
        sailorStatus: 'En mer',
        dayStatus: 'Travail',
        rhythmLabel: 'Bordée 1',
        watchGroup: 'Bordée 1',
        slot365: '',
        departureOn: '',
        workedHours: 12,
        rest24h: 12,
        cumulative7d: 68,
        consecutiveRestHours: 8,
        restPeriodCount: 2,
        nightWorkHours: 4,
        comments: '',
        sourceLabel: 'preview',
      },
      {
        id: 5002,
        personId: 104,
        vesselId: 1,
        crewName: 'Emilien LAFFAITEUR',
        captainName: 'Pierre LEPRETRE',
        vesselName: 'GOURY',
        workDate: addPlanningDays(anchorDate, -1),
        disembarkOn: '',
        yearNumber: Number(addPlanningDays(anchorDate, -1).slice(0, 4)),
        monthNumber: Number(addPlanningDays(anchorDate, -1).slice(5, 7)),
        monthLabel: '',
        dayNumber: Number(addPlanningDays(anchorDate, -1).slice(8, 10)),
        functionLabel: 'Matelot',
        sailorStatus: 'En mer',
        dayStatus: 'Travail',
        rhythmLabel: 'Bordée 1',
        watchGroup: 'Bordée 1',
        slot365: '',
        departureOn: '',
        workedHours: 14,
        rest24h: 10,
        cumulative7d: 78,
        consecutiveRestHours: 5,
        restPeriodCount: 3,
        nightWorkHours: 9,
        comments: 'Donnée de démonstration non conforme.',
        sourceLabel: 'preview',
      },
    ],
    periods: [],
    projects: [
      {
        id: 2001,
        title: 'AFFECTATION NAVIRE GOURY',
        startsOn: addPlanningDays(anchorDate, -14),
        endsOn: addPlanningDays(anchorDate, 43),
        description: 'Projet de démonstration de la vue flotte.',
        clientName: 'BBTM',
        primaryVesselId: 1,
        primaryVesselName: 'GOURY',
        secondaryVesselId: null,
        secondaryVesselName: '',
        eventType: 'operation',
        responsibleName: 'Christophe Admin',
        status: 'Validé',
        sourceLabel: 'preview',
      },
      {
        id: 9601,
        title: 'P901 - Campagne Atlantique — première rotation',
        startsOn: addPlanningDays(anchorDate, 5),
        endsOn: addPlanningDays(anchorDate, 10),
        description: 'Première rotation synthétique.',
        clientName: 'Affréteur Démonstration',
        primaryVesselId: 1,
        primaryVesselName: 'GOURY',
        secondaryVesselId: null,
        secondaryVesselName: '',
        eventType: 'operation',
        responsibleName: 'Christophe Admin',
        status: 'Validé',
        sourceLabel: 'seapilot-projects',
      },
      {
        id: 9602,
        title: 'P901 - Campagne Atlantique — seconde rotation',
        startsOn: addPlanningDays(anchorDate, 16),
        endsOn: addPlanningDays(anchorDate, 23),
        description: 'Seconde rotation synthétique du même projet.',
        clientName: 'Affréteur Démonstration',
        primaryVesselId: 1,
        primaryVesselName: 'GOURY',
        secondaryVesselId: null,
        secondaryVesselName: '',
        eventType: 'operation',
        responsibleName: 'Christophe Admin',
        status: 'Non validé',
        sourceLabel: 'seapilot-projects',
      },
    ],
    certificates: [],
    hrDocuments: [{
      id: 4001,
      personId: 101,
      personName: 'Pierre LEPRETRE',
      categoryKey: 'medical_visit',
      title: 'Visite médicale',
      status: 'expired',
      expiresOn: addPlanningDays(anchorDate, -2),
      requiresCaptainValidation: false,
      medicalRestriction: '',
      medicalUnfit: false,
      fileUrl: '',
    }],
    rules: [],
    publications: [],
    versions: [],
    history: [
      {
        id: 3001,
        entityKind: 'preview',
        entityId: 2001,
        action: 'created',
        payload: {},
        changedBy: 'preview',
        changedByName: 'Préversion SeaPilot',
        changedAt: `${anchorDate}T08:00:00Z`,
        vesselId: 1,
        startsOn: firstWatchStart,
        endsOn: secondWatchEnd,
        summary: 'Jeu de données de démonstration chargé.',
      },
    ],
    handovers: [],
    derogations: [],
    derogationHistory: [],
  };
}
