"""Build small, content-addressed WebP thumbnails; never modify the supplied PNGs.

Run with Python + Pillow 12.3.0. Generated assets are committed, so neither Python
nor Pillow is required by the application build or in production.
"""
import argparse
import hashlib
import io
import json
from pathlib import Path

from PIL import Image, ImageOps


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", required=True, type=Path)
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    catalog = json.loads((root / "scripts/bbtm-fleet-photo-sources.json").read_text(encoding="utf-8"))
    target = root / "public/vessels/bbtm"
    target.mkdir(parents=True, exist_ok=True)
    originals_total = thumbnails_total = 0
    for photo in catalog:
        source = args.source_dir / photo["file"]
        original = source.read_bytes()
        with Image.open(source) as image:
            image = ImageOps.exif_transpose(image).convert("RGB")
            image.thumbnail((256, 171), Image.Resampling.LANCZOS)
            output = io.BytesIO()
            image.save(output, format="WEBP", quality=70, method=6)
            data = output.getvalue()
            if len(data) > 20_000:
                raise ValueError(f'{photo["file"]}: exceeds the 20 KB thumbnail budget')
            photo["width"], photo["height"] = image.size
        digest = hashlib.sha256(data).hexdigest()
        photo["thumbnail"] = f'{photo["slug"]}-{digest[:16]}.webp'
        photo["thumbnailBytes"] = len(data)
        photo["thumbnailSha256"] = digest
        photo["originalSha256"] = hashlib.sha256(original).hexdigest()
        (target / photo["thumbnail"]).write_bytes(data)
        originals_total += len(original)
        thumbnails_total += len(data)
    if thumbnails_total > 120_000:
        raise ValueError("Fleet thumbnails exceed the 120 KB total budget")
    generated = "// Generated by scripts/prepare-bbtm-fleet-thumbnails.py. Edit the source JSON.\n"
    generated += "// Originals live in private fleet-media; only these small thumbnails are public.\n"
    generated += "export const BBTM_FLEET_PHOTOS = " + json.dumps(catalog, ensure_ascii=False, indent=2) + " as const;\n\n"
    generated += "export function fleetCatalogThumbnailPath(photo: { thumbnail: string }): string {\n"
    generated += "  return `/vessels/bbtm/${photo.thumbnail}`;\n}\n"
    (root / "src/features/fleet/fleetPhotoCatalog.ts").write_text(generated, encoding="utf-8")
    print(json.dumps({"originalBytes": originals_total, "thumbnailBytes": thumbnails_total,
                      "reductionPercent": round(100 * (1 - thumbnails_total / originals_total), 2)}, indent=2))


if __name__ == "__main__":
    main()
