-- Inventory is editable; annual inspections retain independent equipment/vessel snapshots.
create table public.lifting_inventory (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  vessel_id bigint not null references public.vessels(id),
  kind text not null check (kind in ('lifting', 'towing')),
  reference text not null check (length(btrim(reference)) between 1 and 100),
  material_type text not null check (length(btrim(material_type)) between 1 and 100),
  description text not null check (length(btrim(description)) between 1 and 2000),
  swl_tonnes numeric check (swl_tonnes > 0),
  serial_number text not null default '', location text not null default '', notes text not null default '',
  active boolean not null default true,
  source_label text not null default 'SeaPilot',
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(company_id, vessel_id, reference),
  check ((kind = 'towing') = (lower(btrim(material_type)) in ('remorque', 'remorques')))
);
create index lifting_inventory_vessel_idx on public.lifting_inventory(company_id, vessel_id, kind, active);
create table public.lifting_inspections (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  vessel_id bigint not null references public.vessels(id),
  kind text not null check (kind in ('lifting', 'towing')),
  inspection_year integer not null,
  issued_on date not null, expires_on date not null check (expires_on > issued_on),
  inspector_name text not null default 'Antoine MONCEAUX' check (inspector_name = 'Antoine MONCEAUX'),
  status text not null default 'draft' check (status in ('draft', 'published')),
  vessel_snapshot jsonb not null,
  revision integer not null default 1,
  notes text not null default '',
  source_label text not null default 'SeaPilot',
  certificate_id bigint references public.fleet_certificates(id) on delete restrict,
  storage_path text, published_at timestamptz,
  created_by uuid references auth.users(id), published_by uuid references auth.users(id),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(company_id, vessel_id, kind, inspection_year),
  check (inspection_year = extract(year from issued_on)),
  check ((status = 'published') = (certificate_id is not null and storage_path is not null and published_at is not null))
);
create index lifting_inspections_vessel_idx on public.lifting_inspections(company_id, vessel_id, kind);
create table public.lifting_inspection_entries (
  id bigint generated by default as identity primary key,
  inspection_id bigint not null references public.lifting_inspections(id) on delete restrict,
  item_id bigint not null references public.lifting_inventory(id) on delete restrict,
  item_snapshot jsonb not null,
  condition text not null default 'pending' check (condition in ('pending','good','repair','withdrawn','not_present')),
  checks jsonb not null default '{"EG":"pending","NID":"pending","V1":"pending","V2":"pending","V3":"pending","V4":"pending","V5":"pending"}'::jsonb,
  observations text not null default '',
  updated_by uuid references auth.users(id), updated_at timestamptz not null default now(),
  unique(inspection_id, item_id)
);
create index lifting_entries_item_idx on public.lifting_inspection_entries(item_id);

create function public.lifting_can_access(p_company_id bigint, p_vessel_id bigint) returns boolean
language sql stable security definer set search_path = '' as $$
  select p_company_id = public.current_planning_company_id()
    and public.has_any_role(array['admin','direction','armement','capitaine','marin'])
    and coalesce(public.planning_can_read_row(p_company_id, p_vessel_id, null, current_date, current_date),false);
$$;
alter table public.lifting_inventory enable row level security;
alter table public.lifting_inspections enable row level security;
alter table public.lifting_inspection_entries enable row level security;
revoke all on public.lifting_inventory, public.lifting_inspections, public.lifting_inspection_entries from anon, authenticated;
grant select on public.lifting_inventory, public.lifting_inspections, public.lifting_inspection_entries to authenticated;
create policy lifting_inventory_read on public.lifting_inventory for select to authenticated
  using ((select public.lifting_can_access(company_id, vessel_id)));
create policy lifting_inspections_read on public.lifting_inspections for select to authenticated
  using ((select public.lifting_can_access(company_id, vessel_id)));
create policy lifting_entries_read on public.lifting_inspection_entries for select to authenticated
  using (exists(select 1 from public.lifting_inspections r where r.id = inspection_id));

create function public.lifting_available_vessels() returns setof public.vessels
language sql stable security definer set search_path = '' as $$
  select v.* from public.vessels v where v.active and v.asset_kind = 'vessel'
    and public.lifting_can_access(v.company_id, v.id) order by v.name;
$$;

create function public.save_lifting_item(p_vessel_id bigint, p_kind text, p_item jsonb, p_id bigint default null)
returns bigint language plpgsql security definer set search_path = '' as $$
declare c bigint := public.current_planning_company_id(); result_id bigint;
begin
  if not public.has_any_role(array['admin','direction','armement']) or not exists(
    select 1 from public.vessels where id=p_vessel_id and company_id=c and active and asset_kind='vessel'
  ) then raise exception using errcode='42501', message='Accès refusé à cet inventaire.'; end if;
  if p_id is null then
    insert into public.lifting_inventory(company_id,vessel_id,kind,reference,material_type,description,swl_tonnes,serial_number,location,notes,created_by,updated_by)
    values(c,p_vessel_id,p_kind,btrim(p_item->>'reference'),btrim(p_item->>'material_type'),btrim(p_item->>'description'),
      nullif(p_item->>'swl_tonnes','')::numeric,coalesce(p_item->>'serial_number',''),coalesce(p_item->>'location',''),coalesce(p_item->>'notes',''),auth.uid(),auth.uid())
    returning id into result_id;
  else
    update public.lifting_inventory set reference=btrim(p_item->>'reference'),material_type=btrim(p_item->>'material_type'),description=btrim(p_item->>'description'),
      swl_tonnes=nullif(p_item->>'swl_tonnes','')::numeric,serial_number=coalesce(p_item->>'serial_number',''),location=coalesce(p_item->>'location',''),notes=coalesce(p_item->>'notes',''),
      updated_by=auth.uid(),updated_at=clock_timestamp()
    where id=p_id and company_id=c and vessel_id=p_vessel_id and kind=p_kind returning id into result_id;
    if result_id is null then raise exception 'Matériel introuvable.'; end if;
  end if;
  return result_id;
end $$;

create function public.set_lifting_item_active(p_id bigint, p_active boolean) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not public.has_any_role(array['admin','direction','armement']) then raise exception using errcode='42501',message='Accès refusé.'; end if;
  update public.lifting_inventory set active=p_active,updated_at=clock_timestamp(),updated_by=auth.uid()
    where id=p_id and company_id=public.current_planning_company_id();
  if not found then raise exception 'Matériel introuvable.'; end if;
end $$;

create function public.start_lifting_inspection(p_vessel_id bigint,p_kind text,p_issued_on date,p_expires_on date) returns bigint
language plpgsql security definer set search_path = '' as $$
declare v public.vessels%rowtype; result_id bigint;
begin
  select * into v from public.vessels where id=p_vessel_id and active and asset_kind='vessel';
  if v.id is null or not public.lifting_can_access(v.company_id,v.id) then raise exception using errcode='42501',message='Accès refusé à ce navire.'; end if;
  if p_issued_on is null or p_expires_on is null or p_expires_on<=p_issued_on then raise exception 'Dates du contrôle invalides.'; end if;
  if not exists(select 1 from public.lifting_inventory where vessel_id=v.id and kind=p_kind and active) then raise exception 'Ajoutez du matériel avant de démarrer un contrôle.'; end if;
  insert into public.lifting_inspections(company_id,vessel_id,kind,inspection_year,issued_on,expires_on,vessel_snapshot,created_by)
    values(v.company_id,v.id,p_kind,extract(year from p_issued_on),p_issued_on,p_expires_on,
      jsonb_build_object('id',v.id,'company_id',v.company_id,'name',v.name,'acronym',v.acronym,'registration_number',v.registration_number,'call_sign',v.call_sign,'registration_port',v.registration_port),auth.uid())
    returning id into result_id;
  insert into public.lifting_inspection_entries(inspection_id,item_id,item_snapshot)
    select result_id,i.id,to_jsonb(i) from public.lifting_inventory i where i.vessel_id=v.id and i.kind=p_kind and i.active order by i.material_type,i.reference;
  return result_id;
exception when unique_violation then raise exception 'Un contrôle existe déjà pour ce navire, cette section et cette année. Reprenez-le dans les rapports.';
end $$;

create function public.save_lifting_inspection_entry(p_inspection_id bigint,p_entry_id bigint,p_revision integer,p_condition text,p_checks jsonb,p_observations text)
returns integer language plpgsql security definer set search_path = '' as $$
declare r public.lifting_inspections%rowtype; k text;
begin
  select * into r from public.lifting_inspections where id=p_inspection_id for update;
  if r.id is null or not public.lifting_can_access(r.company_id,r.vessel_id) then raise exception using errcode='42501',message='Accès refusé.'; end if;
  if r.status <> 'draft' then raise exception 'Ce rapport est finalisé et ne peut plus être modifié.'; end if;
  if r.revision <> p_revision then raise exception 'Ce contrôle a été modifié depuis un autre appareil. Rechargez-le avant de continuer.'; end if;
  if p_checks is null or jsonb_typeof(p_checks)<>'object' then raise exception 'Points de contrôle invalides.'; end if;
  foreach k in array array['EG','NID','V1','V2','V3','V4','V5'] loop
    if coalesce(p_checks->>k,'') not in ('pending','ok','defect','na') then raise exception 'Renseignez chaque point de contrôle.'; end if;
  end loop;
  if p_condition='good' and exists(select 1 from jsonb_each_text(p_checks) where value='defect') then raise exception 'Un matériel présentant un défaut ne peut pas être maintenu en service sans réserve.'; end if;
  update public.lifting_inspection_entries set condition=p_condition,checks=p_checks,observations=coalesce(p_observations,''),updated_by=auth.uid(),updated_at=clock_timestamp()
    where id=p_entry_id and inspection_id=r.id;
  if not found then raise exception 'Matériel absent de ce contrôle.'; end if;
  update public.lifting_inspections set revision=revision+1,updated_at=clock_timestamp() where id=r.id returning revision into p_revision;
  return p_revision;
end $$;

create function public.publish_lifting_inspection(p_id bigint,p_revision integer,p_storage_path text,p_file_name text,p_file_size bigint)
returns bigint language plpgsql security definer set search_path = '' as $$
declare r public.lifting_inspections%rowtype; cert bigint; category text; label text; title_text text;
begin
  select * into r from public.lifting_inspections where id=p_id for update;
  if r.id is null or r.company_id<>public.current_planning_company_id() or not public.has_any_role(array['admin','direction','armement'])
    then raise exception using errcode='42501',message='La finalisation est réservée à la Direction, à l’Armement et aux administrateurs.'; end if;
  if r.status='published' then return r.certificate_id; end if;
  if r.revision<>p_revision then raise exception 'Le contrôle a changé. Rechargez-le pour générer le rapport à jour.'; end if;
  if not exists(select 1 from public.lifting_inspection_entries where inspection_id=r.id) or exists(
    select 1 from public.lifting_inspection_entries e where e.inspection_id=r.id and (
      e.condition='pending'
      or (e.condition<>'good' and btrim(e.observations)='')
      or (e.condition<>'not_present' and exists(select 1 from unnest(array['EG','NID','V1','V2','V3','V4','V5']) k where coalesce(e.checks->>k,'pending')='pending'))
      or (e.condition='good' and exists(select 1 from jsonb_each_text(e.checks) where value='defect'))
    )
  ) then raise exception 'Terminez tous les contrôles et renseignez les observations pour chaque réserve.'; end if;
  if p_file_size is null or p_file_size<=0 or p_file_size>52428800 or nullif(btrim(p_file_name),'') is null
    or p_storage_path not like r.company_id::text||'/'||coalesce(nullif(r.vessel_snapshot->>'acronym',''),r.vessel_id::text)||'/lifting/'||r.id::text||'/'||r.revision::text||'-%'
    or not exists(select 1 from storage.objects where bucket_id='fleet-certificates' and name=p_storage_path and metadata->>'mimetype'='application/pdf')
  then raise exception 'Le PDF doit être stocké sous le navire et la version de ce contrôle.'; end if;
  category := case r.kind when 'towing' then '08-5-remorques' else '08-3-accessoires-levage' end;
  label := case r.kind when 'towing' then '08.5 - Remorques' else '08.3 - Accessoires de levage' end;
  title_text := case r.kind when 'towing' then 'Registre de suivi des remorques' else 'Registre des Apparaux de Levage' end;
  cert := public.create_fleet_certificate_document(r.vessel_id,category,label,title_text,p_file_name,p_file_name,p_storage_path,'application/pdf',p_file_size,r.issued_on,r.expires_on);
  update public.fleet_certificates set provider_name=r.inspector_name,notes='Rapport annuel Levage n° '||r.id||'. Consulter les conclusions et réserves du PDF.' where id=cert;
  update public.lifting_inspections set status='published',certificate_id=cert,storage_path=p_storage_path,published_at=clock_timestamp(),published_by=auth.uid(),updated_at=clock_timestamp() where id=r.id;
  return cert;
end $$;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('lifting-assets','lifting-assets',false,5242880,array['image/png']) on conflict(id) do nothing;
create policy lifting_stamp_read on storage.objects for select to authenticated using(
  bucket_id='lifting-assets' and name=public.current_planning_company_id()::text||'/antoine-monceaux.png'
  and public.has_any_role(array['admin','direction','armement'])
);

-- All mutations are through guarded RPCs; no browser can bypass snapshots or publication rules.
revoke all on function public.lifting_can_access(bigint,bigint),public.lifting_available_vessels(),
  public.save_lifting_item(bigint,text,jsonb,bigint),public.set_lifting_item_active(bigint,boolean),
  public.start_lifting_inspection(bigint,text,date,date),public.save_lifting_inspection_entry(bigint,bigint,integer,text,jsonb,text),
  public.publish_lifting_inspection(bigint,integer,text,text,bigint) from public,anon;
grant execute on function public.lifting_can_access(bigint,bigint),public.lifting_available_vessels(),
  public.save_lifting_item(bigint,text,jsonb,bigint),public.set_lifting_item_active(bigint,boolean),
  public.start_lifting_inspection(bigint,text,date,date),public.save_lifting_inspection_entry(bigint,bigint,integer,text,jsonb,text),
  public.publish_lifting_inspection(bigint,integer,text,text,bigint) to authenticated;
