-- Project document factory: reusable field profiles and SharePoint generation history.

create table if not exists public.project_document_profiles (
  id bigint generated by default as identity primary key,
  company_id bigint not null default public.current_planning_company_id()
    references public.companies(id) on delete restrict,
  project_id bigint not null,
  document_type text not null,
  revision integer not null default 1,
  field_data jsonb not null default '{}'::jsonb,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  updated_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_document_profiles_project_company_fkey
    foreign key (project_id, company_id) references public.projects(id, company_id) on delete cascade,
  constraint project_document_profiles_type_check check (
    document_type in (
      'offer',
      'bimco_supplytime',
      'towage_contract',
      'bareboat_charter',
      'intellectual_service'
    )
  ),
  constraint project_document_profiles_revision_check check (revision > 0),
  constraint project_document_profiles_field_data_check check (jsonb_typeof(field_data) = 'object'),
  unique (company_id, project_id, document_type)
);

create table if not exists public.project_generated_documents (
  id bigint generated by default as identity primary key,
  company_id bigint not null default public.current_planning_company_id()
    references public.companies(id) on delete restrict,
  project_id bigint not null,
  planning_occurrence_id bigint references public.planning_projects(id) on delete set null,
  document_type text not null,
  revision integer not null default 1,
  file_name text not null,
  mime_type text not null,
  file_size_bytes bigint not null,
  sha256 text,
  sharepoint_drive_id text not null,
  sharepoint_drive_item_id text not null,
  sharepoint_web_url text not null,
  sharepoint_folder_path text not null,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint project_generated_documents_project_company_fkey
    foreign key (project_id, company_id) references public.projects(id, company_id) on delete restrict,
  constraint project_generated_documents_type_check check (
    document_type in (
      'offer',
      'bimco_supplytime',
      'towage_contract',
      'bareboat_charter',
      'intellectual_service'
    )
  ),
  constraint project_generated_documents_revision_check check (revision > 0),
  constraint project_generated_documents_file_name_check check (btrim(file_name) <> ''),
  constraint project_generated_documents_mime_type_check check (btrim(mime_type) <> ''),
  constraint project_generated_documents_size_check check (file_size_bytes > 0),
  constraint project_generated_documents_sha256_check check (sha256 is null or sha256 ~ '^[a-f0-9]{64}$'),
  unique (company_id, sharepoint_drive_id, sharepoint_drive_item_id)
);

create index if not exists project_document_profiles_project_idx
  on public.project_document_profiles (company_id, project_id, document_type);
create index if not exists project_generated_documents_project_created_idx
  on public.project_generated_documents (company_id, project_id, created_at desc);
create index if not exists project_generated_documents_occurrence_idx
  on public.project_generated_documents (company_id, planning_occurrence_id)
  where planning_occurrence_id is not null;

alter table public.project_document_profiles enable row level security;
alter table public.project_generated_documents enable row level security;

revoke all on table public.project_document_profiles from public, anon, authenticated;
revoke all on table public.project_generated_documents from public, anon, authenticated;
grant select, insert, update on table public.project_document_profiles to authenticated;
grant select on table public.project_generated_documents to authenticated;
grant usage, select on sequence public.project_document_profiles_id_seq to authenticated;

drop policy if exists project_document_profiles_company_read on public.project_document_profiles;
create policy project_document_profiles_company_read on public.project_document_profiles
  for select to authenticated
  using (public.user_belongs_to_company(company_id));

drop policy if exists project_document_profiles_company_write on public.project_document_profiles;
create policy project_document_profiles_company_write on public.project_document_profiles
  for all to authenticated
  using (
    public.user_belongs_to_company(company_id)
    and public.has_any_role(array['admin', 'direction'])
  )
  with check (
    public.user_belongs_to_company(company_id)
    and public.has_any_role(array['admin', 'direction'])
  );

drop policy if exists project_generated_documents_company_read on public.project_generated_documents;
create policy project_generated_documents_company_read on public.project_generated_documents
  for select to authenticated
  using (public.user_belongs_to_company(company_id));

create or replace function public.projects_peek_next_code(target_prefix text default 'P')
returns text
language plpgsql
security definer
set search_path = public, pg_temp
stable
as $$
declare
  target_company_id bigint := public.current_planning_company_id();
  normalized_prefix text := upper(btrim(target_prefix));
  candidate_number integer;
  candidate_code text;
begin
  if target_company_id is null or not public.user_belongs_to_company(target_company_id) then
    raise exception 'No active SeaPilot company' using errcode = '42501';
  end if;
  if not public.has_any_role(array['admin', 'direction']) then
    raise exception 'Insufficient permission to preview project numbering' using errcode = '42501';
  end if;
  if normalized_prefix !~ '^[A-Z][A-Z0-9_-]{0,7}$' then
    raise exception 'Invalid project code prefix' using errcode = '22023';
  end if;

  select counter.next_number
  into candidate_number
  from public.project_number_counters counter
  where counter.company_id = target_company_id
    and counter.prefix = normalized_prefix;

  candidate_number := coalesce(candidate_number, 265);
  loop
    candidate_code := normalized_prefix || candidate_number::text;
    exit when not exists (
      select 1
      from public.projects project
      where project.company_id = target_company_id
        and public.normalize_project_code(project.project_code) = public.normalize_project_code(candidate_code)
    );
    candidate_number := candidate_number + 1;
  end loop;

  return candidate_code;
end;
$$;

revoke all on function public.projects_peek_next_code(text) from public, anon, authenticated;
grant execute on function public.projects_peek_next_code(text) to authenticated;

comment on table public.project_document_profiles is
  'Per-project editable fields for offer, BIMCO, towage and future contract templates.';
comment on table public.project_generated_documents is
  'Immutable metadata for project documents generated by SeaPilot and stored in SharePoint.';
comment on function public.projects_peek_next_code(text) is
  'Read-only numbering preview. The projects insert trigger remains the atomic allocation authority.';
