-- Live organization chart: no copy of sensitive HR dossiers or planning statuses.
insert into public.role_module_permissions(role_key, module_key, is_visible)
select key, 'organigramme', key in ('admin', 'direction') from public.roles
on conflict (role_key, module_key) do nothing;
alter table public.role_module_permissions add constraint organigramme_roles_restricted
check (module_key <> 'organigramme' or not is_visible or role_key in ('admin', 'direction'));

create function public.organigramme_has_access(target_company_id bigint)
returns boolean language sql stable security invoker set search_path = '' as $$
  select auth.uid() is not null and target_company_id = public.current_planning_company_id()
    and public.user_belongs_to_company(target_company_id)
    and exists (select 1 from public.user_roles r
      join public.role_module_permissions p on p.role_key = r.role_key
      where r.user_id = auth.uid() and r.company_id = target_company_id
      and r.role_key in ('admin', 'direction') and p.module_key = 'organigramme' and p.is_visible);
$$;
revoke all on function public.organigramme_has_access(bigint) from public, anon;
grant execute on function public.organigramme_has_access(bigint) to authenticated;

create table public.organigramme_support (
  id bigint generated by default as identity primary key,
  company_id bigint not null default public.current_planning_company_id() references public.companies(id),
  person_id bigint references public.people(id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 160),
  function_label text not null check (length(trim(function_label)) between 1 and 300),
  category text not null check (category in ('office', 'external')),
  position integer not null default 0 check (position between 0 and 9999),
  check (category <> 'external' or person_id is null)
);
create index organigramme_support_company_idx on public.organigramme_support(company_id);
create index organigramme_support_person_idx on public.organigramme_support(person_id);
alter table public.organigramme_support enable row level security;
grant select, insert, update, delete on public.organigramme_support to authenticated;
grant usage on sequence public.organigramme_support_id_seq to authenticated;
create policy organigramme_support_read on public.organigramme_support for select to authenticated
using (public.organigramme_has_access(company_id));
create policy organigramme_support_insert on public.organigramme_support for insert to authenticated
with check (public.organigramme_has_access(company_id) and (person_id is null or exists (
  select 1 from public.people p where p.id = person_id and p.company_id = organigramme_support.company_id)));
create policy organigramme_support_update on public.organigramme_support for update to authenticated
using (public.organigramme_has_access(company_id))
with check (public.organigramme_has_access(company_id) and (person_id is null or exists (
  select 1 from public.people p where p.id = person_id and p.company_id = organigramme_support.company_id)));
create policy organigramme_support_delete on public.organigramme_support for delete to authenticated
using (public.organigramme_has_access(company_id));

-- User-supplied reference 87-Organigramme.docx / REP 03-B, explicitly including external parties.
insert into public.organigramme_support(company_id, name, function_label, category, position)
select c.id, s.name, s.function_label, 'external', s.position from public.companies c
cross join (values ('IN EXTENSO', 'RH / Comptabilité', 1),
  ('Marine Assistance', 'Accompagnement technique & décisionnel', 2),
  ('RICHEMONT AVOCATS', 'Accompagnement légal et contrats', 3)) s(name,function_label,position)
where c.code = 'bbtm';
insert into public.organigramme_support(company_id,person_id,name,function_label,category,position)
select p.company_id,p.id,concat_ws(' ',p.first_name,p.last_name),s.function_label,'office',s.position
from public.people p join public.companies c on c.id=p.company_id
join (values ('Benjamin','BON','Président · RH & Gestion commerciale',1),
  ('Sophie','HAMEL','Directrice Administrative et Financière',2),
  ('Christophe','MINASSIAN','Directeur QHSE / RSE · Responsable projets EMR · DPA',3),
  ('Antoine','MONCEAUX','Responsable Yard du Havre · Vérificateur équipements levage',4),
  ('Julien','LECOCQ','Centralisation de la maintenance de la flotte',5)) s(first_name,last_name,function_label,position)
on lower(trim(p.first_name))=lower(s.first_name) and lower(trim(p.last_name))=lower(s.last_name)
where c.code='bbtm' and p.active and (p.departed_on is null or p.departed_on>current_date)
and (select count(*) from public.people other where other.company_id=p.company_id
  and lower(trim(other.first_name))=lower(s.first_name) and lower(trim(other.last_name))=lower(s.last_name))=1;

create function public.save_organigramme_support(p_id bigint, p_person_id bigint, p_name text,
  p_function_label text, p_category text, p_position integer)
returns bigint language plpgsql security invoker set search_path = '' as $$
declare company bigint := public.current_planning_company_id(); saved bigint;
begin
  if not public.organigramme_has_access(company) then raise exception 'Accès refusé à l’organigramme.' using errcode='42501'; end if;
  if p_id is null then
    insert into public.organigramme_support(company_id,person_id,name,function_label,category,position)
    values(company,p_person_id,trim(p_name),trim(p_function_label),p_category,p_position) returning id into saved;
  else
    update public.organigramme_support set person_id=p_person_id,name=trim(p_name),function_label=trim(p_function_label),category=p_category,position=p_position
    where id=p_id and company_id=company returning id into saved;
    if saved is null then raise exception 'Intervenant introuvable.' using errcode='P0002'; end if;
  end if;
  return saved;
end;
$$;
revoke all on function public.save_organigramme_support(bigint,bigint,text,text,text,integer) from public, anon;
grant execute on function public.save_organigramme_support(bigint,bigint,text,text,text,integer) to authenticated;

create function public.organigramme_snapshot(p_as_of date default current_date)
returns jsonb language plpgsql stable security invoker set search_path = '' as $$
declare company bigint := public.current_planning_company_id(); result jsonb;
begin
  if not public.organigramme_has_access(company) then raise exception 'Accès refusé à l’organigramme.' using errcode='42501'; end if;
  if p_as_of is null then raise exception 'Date de situation obligatoire.' using errcode='22023'; end if;
  with staff as (
    select p.id, concat_ws(' ',p.first_name,p.last_name) as name,
      coalesce(nullif(trim(p.function_label),''),p.grade_label,'') as function_label, p.employment_population
    from public.people p where p.company_id=company
      and (p.hired_on<=p_as_of or (p.hired_on is null and p.active))
      and (p.departed_on is null or p.departed_on>p_as_of)
      and (p.active or p.departed_on>p_as_of)
  ), ships as (
    select v.id,v.name,v.length_overall from public.vessels v where v.company_id=company
      and v.asset_kind='vessel' and (v.active or v.fleet_exit_on>p_as_of)
      and (v.fleet_exit_on is null or v.fleet_exit_on>p_as_of)
  ), membership as (
    select b.person_id,b.vessel_id,b.watch_group,b.function_label,'board'::text as source
      from public.planning_board_rows b where b.company_id=company
    union all
    select a.crew_person_id,a.vessel_id,a.watch_group,a.assignment_role,'assignment'
      from public.planning_assignments a where a.company_id=company
      and a.starts_on<=p_as_of and coalesce(a.ends_on,p_as_of)>=p_as_of
      and a.confirmation_status<>'cancelled'
    union all
    select p.person_id,p.vessel_id,p.watch_group,p.function_label,'period'
      from public.planning_periods p where p.company_id=company
      and p.starts_on<=p_as_of and coalesce(p.ends_on,p_as_of)>=p_as_of
    union all
    select d.person_id,d.vessel_id,d.watch_group,d.function_label,'day'
      from public.planning_days d where d.company_id=company and d.work_date=p_as_of
  )
  select jsonb_build_object(
    'people',coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'name',s.name,'functionLabel',s.function_label,'population',s.employment_population) order by s.name) from staff s),'[]'::jsonb),
    'vessels',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'name',v.name,'lengthOverall',v.length_overall) order by v.id) from ships v),'[]'::jsonb),
    'memberships',coalesce((select jsonb_agg(jsonb_build_object('personId',m.person_id,'vesselId',m.vessel_id,'watchGroup',coalesce(m.watch_group,''),'functionLabel',coalesce(nullif(trim(m.function_label),''),s.function_label),'source',m.source) order by m.person_id,m.vessel_id,m.watch_group,m.function_label) from membership m join staff s on s.id=m.person_id join ships v on v.id=m.vessel_id),'[]'::jsonb),
    'support',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'personId',e.person_id,'name',coalesce(s.name,e.name),'functionLabel',e.function_label,'category',e.category,'position',e.position) order by e.position,e.id) from public.organigramme_support e left join staff s on s.id=e.person_id where e.company_id=company and (e.person_id is null or s.id is not null)),'[]'::jsonb)
  ) into result;
  return result;
end;
$$;
revoke all on function public.organigramme_snapshot(date) from public, anon;
grant execute on function public.organigramme_snapshot(date) to authenticated;
comment on function public.organigramme_snapshot(date) is 'Company-scoped Admin/Direction organization chart. Live dated memberships take precedence over permanent board rows in the client; no availability or sensitive HR fields are returned.';
