-- Commercial offers and categorized, expiring project attachments.

update public.projects
set contract_type = 'Offre commerciale',
    updated_at = now()
where lower(btrim(contract_type)) = 'autre';

create table public.project_document_categories (
  id bigint generated by default as identity primary key,
  company_id bigint not null default public.current_planning_company_id()
    references public.companies(id) on delete cascade,
  category_key text not null,
  parent_key text,
  label text not null,
  display_order integer not null default 0,
  active boolean not null default true,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  updated_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_document_categories_key_check
    check (category_key ~ '^[a-z0-9][a-z0-9_-]{2,63}$'),
  constraint project_document_categories_parent_key_check
    check (parent_key is null or parent_key ~ '^[a-z0-9][a-z0-9_-]{2,63}$'),
  constraint project_document_categories_label_check
    check (btrim(label) <> ''),
  constraint project_document_categories_not_self_parent_check
    check (parent_key is null or parent_key <> category_key),
  unique (company_id, category_key),
  constraint project_document_categories_parent_fkey
    foreign key (company_id, parent_key)
    references public.project_document_categories(company_id, category_key)
    on delete restrict
    deferrable initially deferred
);

create index project_document_categories_company_order_idx
  on public.project_document_categories (company_id, active, display_order, label);
create index project_document_categories_parent_idx
  on public.project_document_categories (company_id, parent_key, active, display_order);

alter table public.project_document_categories enable row level security;

insert into public.project_document_categories (
  company_id,
  category_key,
  parent_key,
  label,
  display_order
)
select
  company.id,
  seed.category_key,
  seed.parent_key,
  seed.label,
  seed.display_order
from public.companies company
cross join (
  values
    ('commercial_offer', null::text, 'Offre Commerciale', 10),
    ('commercial_contract', 'commercial_offer', 'Contrat', 11),
    ('commercial_appendix', 'commercial_offer', 'Prestation annexe', 12),
    ('hse', null::text, 'HSE', 20),
    ('hse_procedure', 'hse', 'Procédure', 21),
    ('hse_minutes', 'hse', 'Comptes Rendus', 22),
    ('hse_kpi', 'hse', 'KPI', 23),
    ('hse_audits', 'hse', 'Audits', 24),
    ('billing', null::text, 'Facturation', 30)
) as seed(category_key, parent_key, label, display_order)
on conflict (company_id, category_key) do nothing;

revoke all on table public.project_document_categories from public, anon, authenticated;
grant select on table public.project_document_categories to authenticated;
grant usage, select on sequence public.project_document_categories_id_seq to authenticated;

create policy project_document_categories_company_read
  on public.project_document_categories
  for select to authenticated
  using (public.user_belongs_to_company(company_id));

create policy project_document_categories_company_write
  on public.project_document_categories
  for all to authenticated
  using (
    public.user_belongs_to_company(company_id)
    and public.has_any_role(array['admin', 'direction'])
  )
  with check (
    public.user_belongs_to_company(company_id)
    and public.has_any_role(array['admin', 'direction'])
  );

create or replace function public.projects_save_document_categories(target_categories jsonb)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_company_id bigint := public.current_planning_company_id();
begin
  if target_company_id is null
     or not public.user_belongs_to_company(target_company_id)
     or not public.has_any_role(array['admin', 'direction']) then
    raise exception 'Insufficient permission to manage project document categories' using errcode = '42501';
  end if;
  if jsonb_typeof(coalesce(target_categories, '[]'::jsonb)) <> 'array'
     or jsonb_array_length(coalesce(target_categories, '[]'::jsonb)) = 0 then
    raise exception 'Document categories must be a non-empty JSON array' using errcode = '22023';
  end if;
  if exists (
    select 1
    from jsonb_to_recordset(target_categories) as item(
      category_key text,
      parent_key text,
      label text,
      display_order integer,
      active boolean
    )
    where item.category_key !~ '^[a-z0-9][a-z0-9_-]{2,63}$'
       or nullif(btrim(item.label), '') is null
       or item.parent_key = item.category_key
  ) then
    raise exception 'Invalid document category payload' using errcode = '22023';
  end if;
  if exists (
    select 1
    from jsonb_to_recordset(target_categories) as item(
      category_key text,
      parent_key text,
      label text,
      display_order integer,
      active boolean
    )
    where item.parent_key is not null
      and coalesce(item.active, true)
      and not exists (
        select 1
        from jsonb_to_recordset(target_categories) as parent(
          category_key text,
          parent_key text,
          label text,
          display_order integer,
          active boolean
        )
        where parent.category_key = item.parent_key
          and parent.parent_key is null
          and coalesce(parent.active, true)
      )
  ) then
    raise exception 'Every subcategory requires an active root category' using errcode = '22023';
  end if;

  update public.project_document_categories category
  set active = false,
      updated_at = now(),
      updated_by = auth.uid()
  where category.company_id = target_company_id
    and not exists (
      select 1
      from jsonb_to_recordset(target_categories) as item(
        category_key text,
        parent_key text,
        label text,
        display_order integer,
        active boolean
      )
      where item.category_key = category.category_key
    );

  insert into public.project_document_categories (
    company_id,
    category_key,
    parent_key,
    label,
    display_order,
    active,
    created_by,
    updated_by
  )
  select
    target_company_id,
    item.category_key,
    null,
    btrim(item.label),
    coalesce(item.display_order, 0),
    coalesce(item.active, true),
    auth.uid(),
    auth.uid()
  from jsonb_to_recordset(target_categories) as item(
    category_key text,
    parent_key text,
    label text,
    display_order integer,
    active boolean
  )
  where item.parent_key is null
  on conflict (company_id, category_key) do update
  set parent_key = null,
      label = excluded.label,
      display_order = excluded.display_order,
      active = excluded.active,
      updated_at = now(),
      updated_by = auth.uid();

  insert into public.project_document_categories (
    company_id,
    category_key,
    parent_key,
    label,
    display_order,
    active,
    created_by,
    updated_by
  )
  select
    target_company_id,
    item.category_key,
    item.parent_key,
    btrim(item.label),
    coalesce(item.display_order, 0),
    coalesce(item.active, true),
    auth.uid(),
    auth.uid()
  from jsonb_to_recordset(target_categories) as item(
    category_key text,
    parent_key text,
    label text,
    display_order integer,
    active boolean
  )
  where item.parent_key is not null
  on conflict (company_id, category_key) do update
  set parent_key = excluded.parent_key,
      label = excluded.label,
      display_order = excluded.display_order,
      active = excluded.active,
      updated_at = now(),
      updated_by = auth.uid();
end;
$$;

revoke all on function public.projects_save_document_categories(jsonb)
  from public, anon, authenticated;
grant execute on function public.projects_save_document_categories(jsonb)
  to authenticated;

alter table public.project_generated_documents
  add column category_key text,
  add column subcategory_key text,
  add column expires_on date;

alter table public.project_generated_documents
  add constraint project_generated_documents_category_fkey
    foreign key (company_id, category_key)
    references public.project_document_categories(company_id, category_key)
    on delete restrict,
  add constraint project_generated_documents_subcategory_fkey
    foreign key (company_id, subcategory_key)
    references public.project_document_categories(company_id, category_key)
    on delete restrict,
  add constraint project_generated_documents_attachment_category_check
    check (document_type <> 'project_attachment' or category_key is not null);

alter table public.project_generated_documents
  drop constraint project_generated_documents_type_check;

alter table public.project_generated_documents
  add constraint project_generated_documents_type_check check (
    document_type in (
      'offer',
      'bimco_supplytime',
      'towage_contract',
      'bareboat_charter',
      'intellectual_service',
      'operation_attachment',
      'project_attachment'
    )
  );

create index project_generated_documents_category_expiry_idx
  on public.project_generated_documents (
    company_id,
    project_id,
    category_key,
    subcategory_key,
    expires_on
  )
  where document_type = 'project_attachment';

comment on table public.project_document_categories is
  'Editable project attachment categories and subcategories, scoped by company.';
comment on column public.project_generated_documents.expires_on is
  'Optional validity end date. NULL means that the attachment has no expiry.';
comment on function public.projects_save_document_categories(jsonb) is
  'Replaces the editable project attachment category catalog for the active company.';
