insert into public.sharepoint_field_mappings (
  source_key,
  field_label,
  internal_name,
  data_type,
  target_table,
  target_column,
  required,
  notes
)
values
  ('list-rh-personnel-bbtm', 'Telephone', 'N_x00b0_T_x00e9_l_x00e9_phone', 'Text', 'people', 'phone', false, null),
  ('list-rh-personnel-bbtm', 'Adresse postale', 'AdressePostale', 'Note', 'people', 'postal_address', false, null),
  ('list-rh-personnel-bbtm', 'Date de naissance', 'DatedeNaissance', 'DateTime', 'people', 'birth_date', false, null),
  ('list-rh-personnel-bbtm', 'Lieu de naissance', 'LieudeNaissance', 'Text', 'people', 'birth_place', false, null),
  ('list-rh-personnel-bbtm', 'Numero document identite', 'Num_x00e9_roIdentit_x00e9_', 'Text', 'people', 'identity_document_number', false, null),
  ('list-rh-personnel-bbtm', 'Type document identite', 'TypedeDocumentdIdentit_x00e9_', 'Choice', 'people', 'identity_document_type', false, null),
  ('list-rh-personnel-bbtm', 'Type contrat', 'TypedeContrat', 'Choice', 'people', 'contract_type', false, null),
  ('list-rh-personnel-bbtm', 'Date embauche', 'DatedEmbauche', 'DateTime', 'people', 'hired_on', false, null),
  ('list-rh-personnel-bbtm', 'Date depart', 'Dateded_x00e9_part', 'DateTime', 'people', 'departed_on', false, null),
  ('list-rh-personnel-bbtm', 'Cause depart', 'Causedud_x00e9_part', 'Text/Choice', 'people', 'departure_reason', false, null),
  ('list-rh-personnel-bbtm', 'Contact urgence', 'Pr_x00e9_nometNOMContactdUrgence', 'Text', 'people', 'emergency_contact_name', false, null),
  ('list-rh-personnel-bbtm', 'Lien parente urgence', 'LienParent_x00e9_ContactdUrgence', 'Text', 'people', 'emergency_contact_relationship', false, null),
  ('list-rh-personnel-bbtm', 'Telephone urgence', 'Num_x00e9_rodet_x00e9_l_x00e9_ph', 'Text', 'people', 'emergency_contact_phone', false, null),
  ('list-rh-personnel-bbtm', 'Adresse urgence', 'Adressecompl_x00e8_teContactdUrg', 'Note', 'people', 'emergency_contact_address', false, null),
  ('list-rh-personnel-bbtm', 'Tour de taille', 'A_x002d_TourdeTaille', 'Number', 'people', 'waist_size', false, null),
  ('list-rh-personnel-bbtm', 'Poitrine', 'B_x002d_Poitrine', 'Number', 'people', 'chest_size', false, null),
  ('list-rh-personnel-bbtm', 'Taille totale', 'C_x002d_Tailletotale', 'Number', 'people', 'full_height_size', false, null),
  ('list-rh-personnel-bbtm', 'Longueur entrejambe', 'DLongueurEntrejambe', 'Number', 'people', 'inseam_size', false, null),
  ('list-rh-personnel-bbtm', 'Tour de hanche', 'E_x002d_TourdeHanche', 'Number', 'people', 'hip_size', false, null),
  ('list-rh-personnel-bbtm', 'Poids', 'Poids', 'Number', 'people', 'weight_kg', false, null),
  ('list-rh-personnel-bbtm', 'Pointure', 'Pointure', 'Number', 'people', 'shoe_size', false, null),
  ('list-rh-personnel-bbtm', 'Taille combinaison', 'TailleCombinaison', 'Choice', 'people', 'coverall_size', false, null),
  ('list-rh-personnel-bbtm', 'Taille pantalon', 'TaillePantalon', 'Choice', 'people', 'pants_size', false, 'Alias import: TaillePantalonHomme, TaillePantalonFemme.'),
  ('list-rh-personnel-bbtm', 'Taille veste', 'TailleVesteHomme', 'Choice', 'people', 'jacket_size', false, 'Alias import: TailleVesteFemme, TailleVeste.'),
  ('list-rh-personnel-bbtm', 'Brevet pont', 'BrevetPont', 'Lookup', 'people', 'deck_certificate_label', false, null),
  ('list-rh-personnel-bbtm', 'Brevet machine', 'BrevetMachine', 'Lookup', 'people', 'engine_certificate_label', false, null),
  ('list-rh-personnel-bbtm', 'Formation grutage', 'FormationGrutage', 'DateTime', 'people', 'crane_training_on', false, null),
  ('list-rh-personnel-bbtm', 'Induction grutage', 'InductionGrutage', 'DateTime', 'people', 'crane_induction_on', false, null)
on conflict (source_key, internal_name, target_table, target_column) do update
set field_label = excluded.field_label,
    data_type = excluded.data_type,
    required = excluded.required,
    notes = excluded.notes,
    updated_at = now();
