alter table public.fleet_certificates
  add column if not exists document_title text,
  add column if not exists category_label text,
  add column if not exists original_file_name text,
  add column if not exists file_name text,
  add column if not exists planned_on date,
  add column if not exists alarm_on date,
  add column if not exists provider_name text,
  add column if not exists visit_location text,
  add column if not exists workflow_status text not null default 'not_started',
  add column if not exists renewal_notes text,
  add column if not exists renaming_rule_key text not null default 'vessel-title-expiry-year',
  add column if not exists storage_bucket text,
  add column if not exists storage_path text,
  add column if not exists mime_type text,
  add column if not exists file_size_bytes bigint,
  add column if not exists sharepoint_drive_id text,
  add column if not exists sharepoint_drive_item_id text,
  add column if not exists source_created_at timestamptz,
  add column if not exists renewed_at timestamptz,
  add column if not exists current_version_no integer not null default 1,
  add column if not exists is_active_fleet boolean not null default true;

update public.fleet_certificates
set alarm_on = expires_on - 90
where expires_on is not null
  and alarm_on is null;

alter table public.fleet_certificates
  drop constraint if exists fleet_certificates_workflow_status_check;
alter table public.fleet_certificates
  add constraint fleet_certificates_workflow_status_check
  check (workflow_status in (
    'not_started', 'due', 'planned', 'requested', 'document_received',
    'pending_validation', 'validated', 'cancelled'
  ));

create index if not exists fleet_certificates_company_expiry_idx
  on public.fleet_certificates (company_id, expires_on, vessel_name);
create index if not exists fleet_certificates_company_planned_idx
  on public.fleet_certificates (company_id, planned_on)
  where planned_on is not null;
create unique index if not exists fleet_certificates_company_original_name_idx
  on public.fleet_certificates (company_id, original_file_name)
  where original_file_name is not null;
create unique index if not exists fleet_certificates_storage_object_idx
  on public.fleet_certificates (storage_bucket, storage_path)
  where storage_bucket is not null and storage_path is not null;

create table if not exists public.fleet_certificate_versions (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete restrict,
  certificate_id bigint not null references public.fleet_certificates(id) on delete cascade,
  version_no integer not null check (version_no > 0),
  status text not null default 'active'
    check (status in ('active', 'archived', 'pending_validation', 'rejected')),
  original_file_name text not null,
  normalized_file_name text not null,
  storage_bucket text not null default 'fleet-certificates',
  storage_path text not null,
  mime_type text,
  file_size_bytes bigint,
  issued_on date,
  expires_on date,
  is_current boolean not null default false,
  source_label text not null default 'seapilot',
  uploaded_by uuid references auth.users(id) on delete set null,
  validated_by uuid references auth.users(id) on delete set null,
  validated_at timestamptz,
  created_at timestamptz not null default now(),
  unique (certificate_id, version_no),
  unique (storage_bucket, storage_path)
);

create unique index if not exists fleet_certificate_versions_one_current_idx
  on public.fleet_certificate_versions (certificate_id)
  where is_current;
create index if not exists fleet_certificate_versions_company_certificate_idx
  on public.fleet_certificate_versions (company_id, certificate_id, version_no desc);

create table if not exists public.fleet_certificate_renewal_events (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete restrict,
  certificate_id bigint not null references public.fleet_certificates(id) on delete cascade,
  version_id bigint references public.fleet_certificate_versions(id) on delete set null,
  event_type text not null
    check (event_type in ('planned', 'requested', 'document_received', 'submitted', 'validated', 'rejected', 'cancelled')),
  planned_on date,
  provider_name text,
  visit_location text,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists fleet_certificate_renewal_events_history_idx
  on public.fleet_certificate_renewal_events (company_id, certificate_id, created_at desc);

alter table public.fleet_certificate_versions enable row level security;
alter table public.fleet_certificate_renewal_events enable row level security;

drop policy if exists fleet_certificate_versions_company_read on public.fleet_certificate_versions;
create policy fleet_certificate_versions_company_read
on public.fleet_certificate_versions for select to authenticated
using (
  company_id = public.current_planning_company_id()
  and public.has_any_role(array['admin', 'direction', 'armement', 'capitaine', 'marin'])
);

drop policy if exists fleet_certificate_versions_office_write on public.fleet_certificate_versions;
create policy fleet_certificate_versions_office_write
on public.fleet_certificate_versions for all to authenticated
using (
  company_id = public.current_planning_company_id()
  and public.has_any_role(array['admin', 'direction', 'armement'])
)
with check (
  company_id = public.current_planning_company_id()
  and public.has_any_role(array['admin', 'direction', 'armement'])
);

drop policy if exists fleet_certificate_renewal_events_company_read on public.fleet_certificate_renewal_events;
create policy fleet_certificate_renewal_events_company_read
on public.fleet_certificate_renewal_events for select to authenticated
using (
  company_id = public.current_planning_company_id()
  and public.has_any_role(array['admin', 'direction', 'armement', 'capitaine', 'marin'])
);

drop policy if exists fleet_certificate_renewal_events_office_write on public.fleet_certificate_renewal_events;
create policy fleet_certificate_renewal_events_office_write
on public.fleet_certificate_renewal_events for all to authenticated
using (
  company_id = public.current_planning_company_id()
  and public.has_any_role(array['admin', 'direction', 'armement'])
)
with check (
  company_id = public.current_planning_company_id()
  and public.has_any_role(array['admin', 'direction', 'armement'])
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'fleet-certificates',
  'fleet-certificates',
  false,
  52428800,
  array[
    'application/pdf',
    'image/png',
    'image/jpeg',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  ]::text[]
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists fleet_certificates_storage_read on storage.objects;
create policy fleet_certificates_storage_read
on storage.objects for select to authenticated
using (
  bucket_id = 'fleet-certificates'
  and split_part(name, '/', 1) = public.current_planning_company_id()::text
  and public.has_any_role(array['admin', 'direction', 'armement', 'capitaine', 'marin'])
);

drop policy if exists fleet_certificates_storage_insert on storage.objects;
create policy fleet_certificates_storage_insert
on storage.objects for insert to authenticated
with check (
  bucket_id = 'fleet-certificates'
  and split_part(name, '/', 1) = public.current_planning_company_id()::text
  and public.has_any_role(array['admin', 'direction', 'armement'])
);

drop policy if exists fleet_certificates_storage_update on storage.objects;
create policy fleet_certificates_storage_update
on storage.objects for update to authenticated
using (
  bucket_id = 'fleet-certificates'
  and split_part(name, '/', 1) = public.current_planning_company_id()::text
  and public.has_any_role(array['admin', 'direction', 'armement'])
)
with check (
  bucket_id = 'fleet-certificates'
  and split_part(name, '/', 1) = public.current_planning_company_id()::text
  and public.has_any_role(array['admin', 'direction', 'armement'])
);

drop policy if exists fleet_certificates_storage_delete on storage.objects;
create policy fleet_certificates_storage_delete
on storage.objects for delete to authenticated
using (
  bucket_id = 'fleet-certificates'
  and split_part(name, '/', 1) = public.current_planning_company_id()::text
  and public.has_any_role(array['admin', 'direction', 'armement'])
);

revoke all on table public.fleet_certificate_versions from anon, authenticated;
revoke all on table public.fleet_certificate_renewal_events from anon, authenticated;
grant select, insert, update, delete on table public.fleet_certificate_versions to authenticated;
grant select, insert, update, delete on table public.fleet_certificate_renewal_events to authenticated;
grant usage, select on sequence public.fleet_certificate_versions_id_seq to authenticated;
grant usage, select on sequence public.fleet_certificate_renewal_events_id_seq to authenticated;
