create table if not exists public.qhse_annual_reference_metrics (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  report_year integer not null check (report_year between 2000 and 2200),
  vessel_id bigint references public.vessels(id) on delete cascade,
  worked_hours numeric(14, 2) not null check (worked_hours >= 0),
  person_days numeric(14, 2) not null check (person_days >= 0),
  source_label text not null,
  source_document text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists qhse_annual_reference_metrics_scope_idx
  on public.qhse_annual_reference_metrics (company_id, report_year, coalesce(vessel_id, 0));

create table if not exists public.qhse_environment_parameters (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  parameter_key text not null,
  label text not null,
  fuel_density_tonnes_per_m3 numeric(10, 6) not null check (fuel_density_tonnes_per_m3 > 0),
  emission_factor_tco2_per_tonne numeric(10, 6) not null check (emission_factor_tco2_per_tonne > 0),
  xbee_reduction_rate numeric(8, 6) not null check (xbee_reduction_rate between 0 and 1),
  effective_from date not null,
  effective_to date,
  applies_to_all_vessels boolean not null default true,
  source_label text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, parameter_key, effective_from),
  check (effective_to is null or effective_to >= effective_from)
);

create table if not exists public.qhse_contract_targets (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  vessel_id bigint not null references public.vessels(id) on delete cascade,
  report_year integer not null check (report_year between 2000 and 2200),
  maintenance_days_limit numeric(8, 2) not null check (maintenance_days_limit >= 0),
  port_call_24h_limit integer not null check (port_call_24h_limit >= 0),
  valid_until date,
  source_label text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, project_id, vessel_id, report_year)
);

alter table public.qhse_annual_reference_metrics enable row level security;
alter table public.qhse_environment_parameters enable row level security;
alter table public.qhse_contract_targets enable row level security;

revoke all on public.qhse_annual_reference_metrics, public.qhse_environment_parameters, public.qhse_contract_targets from anon, authenticated;
grant select on public.qhse_annual_reference_metrics, public.qhse_environment_parameters, public.qhse_contract_targets to authenticated;
grant insert, update, delete on public.qhse_annual_reference_metrics, public.qhse_environment_parameters, public.qhse_contract_targets to authenticated;
grant usage, select on sequence public.qhse_annual_reference_metrics_id_seq to authenticated;
grant usage, select on sequence public.qhse_environment_parameters_id_seq to authenticated;
grant usage, select on sequence public.qhse_contract_targets_id_seq to authenticated;

drop policy if exists qhse_annual_reference_metrics_read on public.qhse_annual_reference_metrics;
create policy qhse_annual_reference_metrics_read on public.qhse_annual_reference_metrics
  for select to authenticated
  using (
    company_id = public.current_planning_company_id()
    and public.has_any_role(array['admin', 'direction', 'armement', 'capitaine'])
  );

drop policy if exists qhse_annual_reference_metrics_manage on public.qhse_annual_reference_metrics;
create policy qhse_annual_reference_metrics_manage on public.qhse_annual_reference_metrics
  for all to authenticated
  using (
    company_id = public.current_planning_company_id()
    and public.has_any_role(array['admin', 'direction'])
  )
  with check (
    company_id = public.current_planning_company_id()
    and public.has_any_role(array['admin', 'direction'])
  );

drop policy if exists qhse_environment_parameters_read on public.qhse_environment_parameters;
create policy qhse_environment_parameters_read on public.qhse_environment_parameters
  for select to authenticated
  using (
    company_id = public.current_planning_company_id()
    and public.has_any_role(array['admin', 'direction', 'armement', 'capitaine'])
  );

drop policy if exists qhse_environment_parameters_manage on public.qhse_environment_parameters;
create policy qhse_environment_parameters_manage on public.qhse_environment_parameters
  for all to authenticated
  using (
    company_id = public.current_planning_company_id()
    and public.has_any_role(array['admin', 'direction'])
  )
  with check (
    company_id = public.current_planning_company_id()
    and public.has_any_role(array['admin', 'direction'])
  );

drop policy if exists qhse_contract_targets_read on public.qhse_contract_targets;
create policy qhse_contract_targets_read on public.qhse_contract_targets
  for select to authenticated
  using (
    company_id = public.current_planning_company_id()
    and public.has_any_role(array['admin', 'direction', 'armement', 'capitaine'])
  );

drop policy if exists qhse_contract_targets_manage on public.qhse_contract_targets;
create policy qhse_contract_targets_manage on public.qhse_contract_targets
  for all to authenticated
  using (
    company_id = public.current_planning_company_id()
    and public.has_any_role(array['admin', 'direction'])
  )
  with check (
    company_id = public.current_planning_company_id()
    and public.has_any_role(array['admin', 'direction'])
  );

insert into public.port_call_reason_types (key, label, display_order, active)
values
  ('port-call-14h', '14h Port Call', 15, true),
  ('port-call-24h', '24h Port Call', 16, true)
on conflict (key) do update
set label = excluded.label,
    display_order = excluded.display_order,
    active = true;

delete from public.qhse_annual_reference_metrics
where vessel_id is null
  and report_year in (2023, 2024, 2025)
  and company_id in (select id from public.companies where name = 'BBTM');

insert into public.qhse_annual_reference_metrics (
  company_id, report_year, vessel_id, worked_hours, person_days, source_label, source_document
)
select company.id, source.report_year, null, source.worked_hours, source.person_days,
       'Historique officiel validé par la Direction', 'Rapport Général QHSE.pbix'
from public.companies company
cross join (values
  (2023, 11454::numeric, 1091::numeric),
  (2024, 25883::numeric, 2394::numeric),
  (2025, 36230::numeric, 3448::numeric)
) as source(report_year, worked_hours, person_days)
where company.name = 'BBTM';

insert into public.qhse_environment_parameters (
  company_id, parameter_key, label, fuel_density_tonnes_per_m3,
  emission_factor_tco2_per_tonne, xbee_reduction_rate, effective_from,
  effective_to, applies_to_all_vessels, source_label
)
select company.id, 'marine-gasoil-xbee', 'Gasoil marin avec additif xBee',
       0.85, 3.206, 0.15, date '1900-01-01', null, true,
       'Règle métier validée par la Direction'
from public.companies company
where company.name = 'BBTM'
on conflict (company_id, parameter_key, effective_from) do update
set label = excluded.label,
    fuel_density_tonnes_per_m3 = excluded.fuel_density_tonnes_per_m3,
    emission_factor_tco2_per_tonne = excluded.emission_factor_tco2_per_tonne,
    xbee_reduction_rate = excluded.xbee_reduction_rate,
    effective_to = excluded.effective_to,
    applies_to_all_vessels = excluded.applies_to_all_vessels,
    source_label = excluded.source_label,
    updated_at = now();

insert into public.qhse_contract_targets (
  company_id, project_id, vessel_id, report_year, maintenance_days_limit,
  port_call_24h_limit, valid_until, source_label
)
select project.company_id, project.id, vessel.id, 2026, 5, 8, date '2026-08-31',
       'Objectifs contractuels P144 / GOURY validés par la Direction'
from public.projects project
join public.vessels vessel
  on vessel.company_id = project.company_id and vessel.name = 'GOURY'
where project.project_code = 'P144'
on conflict (company_id, project_id, vessel_id, report_year) do update
set maintenance_days_limit = excluded.maintenance_days_limit,
    port_call_24h_limit = excluded.port_call_24h_limit,
    valid_until = excluded.valid_until,
    source_label = excluded.source_label,
    updated_at = now();

create or replace function public.qhse_set_employment_population_from_grade()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  normalized_grade text;
begin
  normalized_grade := translate(
    lower(coalesce(new.grade_label, '')),
    'éèêëàâäîïôöùûüç',
    'eeeeaaaiioouuuc'
  );
  new.employment_population := case
    when normalized_grade like '%sedentaire%' then 'sedentary'
    else 'offshore'
  end;
  return new;
end;
$$;

revoke all on function public.qhse_set_employment_population_from_grade() from public, anon, authenticated;

drop trigger if exists qhse_people_population_from_grade on public.people;
create trigger qhse_people_population_from_grade
before insert or update of grade_label on public.people
for each row execute function public.qhse_set_employment_population_from_grade();

update public.people
set employment_population = case
  when translate(lower(coalesce(grade_label, '')), 'éèêëàâäîïôöùûüç', 'eeeeaaaiioouuuc') like '%sedentaire%'
    then 'sedentary'
  else 'offshore'
end;

comment on table public.qhse_annual_reference_metrics is
  'Annual fleet-level QHSE exposure metrics imported from approved historical reporting. Vessel-specific reports must not allocate fleet totals.';
comment on table public.qhse_environment_parameters is
  'Versioned environmental calculation parameters used by generated QHSE reports.';
comment on table public.qhse_contract_targets is
  'Annual project and vessel contractual targets displayed in QHSE operations reports.';
