create table public.fleet_certificate_document_names (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade
    default public.current_planning_company_id(),
  name text not null check (nullif(btrim(name), '') is not null),
  normalized_name text generated always as (lower(regexp_replace(btrim(name), '\s+', ' ', 'g'))) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, normalized_name)
);

insert into public.fleet_certificate_document_names (company_id, name)
select distinct certificate.company_id, btrim(certificate.document_title)
from public.fleet_certificates certificate
where nullif(btrim(certificate.document_title), '') is not null
on conflict (company_id, normalized_name) do nothing;

alter table public.fleet_certificate_document_names enable row level security;

create policy fleet_certificate_document_names_company_read
on public.fleet_certificate_document_names for select to authenticated
using (
  company_id = (select public.current_planning_company_id())
  and (select public.has_any_role(array['admin', 'direction', 'armement', 'capitaine', 'marin']))
);

create policy fleet_certificate_document_names_company_insert
on public.fleet_certificate_document_names for insert to authenticated
with check (
  company_id = (select public.current_planning_company_id())
  and (select public.has_any_role(array['admin', 'direction', 'armement']))
);

create policy fleet_certificate_document_names_company_update
on public.fleet_certificate_document_names for update to authenticated
using (
  company_id = (select public.current_planning_company_id())
  and (select public.has_any_role(array['admin', 'direction', 'armement']))
)
with check (
  company_id = (select public.current_planning_company_id())
  and (select public.has_any_role(array['admin', 'direction', 'armement']))
);

grant select, insert, update on table public.fleet_certificate_document_names to authenticated;
grant usage, select on sequence public.fleet_certificate_document_names_id_seq to authenticated;

create or replace function public.sync_fleet_certificate_document_name()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if nullif(btrim(new.document_title), '') is not null then
    insert into public.fleet_certificate_document_names (company_id, name)
    values (new.company_id, btrim(new.document_title))
    on conflict (company_id, normalized_name)
    do update set name = excluded.name, updated_at = now();
  end if;
  return new;
end;
$$;

revoke all on function public.sync_fleet_certificate_document_name() from public, anon;

create trigger fleet_certificates_sync_document_name
after insert or update of document_title on public.fleet_certificates
for each row execute function public.sync_fleet_certificate_document_name();
