-- Daily work-time submission/approval and Planning-backed DPR scope.
--
-- A monthly register remains the durable container, but workflow state is now
-- carried by each worked day. This prevents an early approval from locking the
-- remaining days of the month. Planning statuses are normalised server-side so
-- only personnel effectively "En mer" or "A terre" are considered on duty.

create or replace function public.planning_status_is_working(p_status text)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select regexp_replace(
    translate(upper(coalesce(p_status, '')),
      'ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÑÒÓÔÕÖÙÚÛÜÝ',
      'AAAAAACEEEEIIIINOOOOOUUUUY'),
    '[^A-Z0-9]+', '', 'g'
  ) in ('ENMER', 'ATERRE', 'EMBARQUE');
$$;

create or replace function public.planning_effective_person_status(
  p_company_id bigint,
  p_person_id bigint,
  p_work_date date,
  p_vessel_id bigint,
  p_fallback_status text default null
)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (
      select nullif(trim(day_status.sailor_status), '')
      from public.planning_days day_status
      where day_status.company_id = p_company_id
        and day_status.person_id = p_person_id
        and day_status.work_date = p_work_date
        and (p_vessel_id is null or day_status.vessel_id is null or day_status.vessel_id = p_vessel_id)
      order by (day_status.vessel_id = p_vessel_id) desc, day_status.id desc
      limit 1
    ),
    (
      select nullif(trim(period_status.sailor_status), '')
      from public.planning_periods period_status
      where period_status.company_id = p_company_id
        and period_status.person_id = p_person_id
        and p_work_date between period_status.starts_on and period_status.ends_on
        and (p_vessel_id is null or period_status.vessel_id is null or period_status.vessel_id = p_vessel_id)
      order by (period_status.vessel_id = p_vessel_id) desc, period_status.id desc
      limit 1
    ),
    nullif(trim(p_fallback_status), '')
  );
$$;

revoke all on function public.planning_status_is_working(text) from public, anon, authenticated;
revoke all on function public.planning_effective_person_status(bigint, bigint, date, bigint, text) from public, anon, authenticated;

create table if not exists public.working_time_day_approvals (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  register_id bigint not null references public.working_time_registers(id) on delete cascade,
  person_id bigint not null references public.people(id) on delete restrict,
  local_work_date date not null,
  status text not null default 'draft',
  planning_assignment_id bigint references public.planning_assignments(id) on delete set null,
  vessel_id bigint references public.vessels(id) on delete set null,
  watch_group text,
  approver_person_id bigint references public.people(id) on delete restrict,
  submitted_by uuid references auth.users(id) on delete set null,
  submitted_by_person_id bigint references public.people(id) on delete set null,
  submitted_at timestamptz,
  validated_by uuid references auth.users(id) on delete set null,
  validated_by_person_id bigint references public.people(id) on delete set null,
  validated_at timestamptz,
  subject_identity_snapshot jsonb not null default '{}'::jsonb,
  approver_identity_snapshot jsonb not null default '{}'::jsonb,
  vessel_snapshot jsonb not null default '{}'::jsonb,
  watch_snapshot jsonb not null default '{}'::jsonb,
  signature_snapshot jsonb not null default '{}'::jsonb,
  interval_snapshot jsonb not null default '[]'::jsonb,
  non_compliance_snapshot jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint working_time_day_approvals_status_check
    check (status in ('draft', 'submitted', 'validated')),
  constraint working_time_day_approvals_submit_check check (
    status = 'draft'
    or (approver_person_id is not null and submitted_at is not null and submitted_by_person_id is not null)
  ),
  constraint working_time_day_approvals_validate_check check (
    status <> 'validated'
    or (validated_at is not null and validated_by_person_id is not null)
  ),
  constraint working_time_day_approvals_no_self_approval_check
    check (approver_person_id is null or approver_person_id <> person_id),
  unique (register_id, local_work_date)
);

create index if not exists working_time_day_approvals_approver_status_idx
  on public.working_time_day_approvals (approver_person_id, status, local_work_date);
create index if not exists working_time_day_approvals_person_date_idx
  on public.working_time_day_approvals (person_id, local_work_date);

create table if not exists public.working_time_day_approval_events (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  day_approval_id bigint not null references public.working_time_day_approvals(id) on delete cascade,
  register_id bigint not null references public.working_time_registers(id) on delete cascade,
  person_id bigint not null references public.people(id) on delete restrict,
  local_work_date date not null,
  event_type text not null,
  previous_status text,
  new_status text not null,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_person_id bigint references public.people(id) on delete set null,
  actor_identity_snapshot jsonb not null default '{}'::jsonb,
  interval_snapshot jsonb not null default '[]'::jsonb,
  non_compliance_snapshot jsonb not null default '[]'::jsonb,
  comment text,
  occurred_at timestamptz not null default clock_timestamp(),
  constraint working_time_day_approval_events_type_check
    check (event_type in ('submitted', 'captain_corrected', 'validated', 'legacy_validation_migrated')),
  constraint working_time_day_approval_events_status_check
    check (new_status in ('submitted', 'validated'))
);

create index if not exists working_time_day_approval_events_day_idx
  on public.working_time_day_approval_events (day_approval_id, occurred_at desc);

alter table public.working_time_day_approvals enable row level security;
alter table public.working_time_day_approval_events enable row level security;

drop policy if exists working_time_day_approvals_select on public.working_time_day_approvals;
create policy working_time_day_approvals_select
on public.working_time_day_approvals
for select to authenticated
using (
  (select public.user_belongs_to_company(company_id))
  and (
    person_id = (select public.current_person_id())
    or approver_person_id = (select public.current_person_id())
    or (select public.has_company_role(company_id, array['admin', 'armement', 'direction']))
  )
);

drop policy if exists working_time_day_approval_events_select on public.working_time_day_approval_events;
create policy working_time_day_approval_events_select
on public.working_time_day_approval_events
for select to authenticated
using (
  exists (
    select 1
    from public.working_time_day_approvals approval
    where approval.id = day_approval_id
  )
);

revoke all on table public.working_time_day_approvals from public, anon, authenticated;
revoke all on table public.working_time_day_approval_events from public, anon, authenticated;
grant select on table public.working_time_day_approvals to authenticated;
grant select on table public.working_time_day_approval_events to authenticated;

create or replace function public.working_time_day_context(
  p_person_id bigint,
  p_local_work_date date
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  target_person public.people%rowtype;
  target_assignment public.planning_assignments%rowtype;
  effective_status text;
  candidates jsonb;
  preferred_approver_id bigint;
begin
  select * into target_person from public.people person where person.id = p_person_id;
  if (select auth.uid()) is null or target_person.id is null or p_local_work_date is null
    or not public.user_belongs_to_company(target_person.company_id) then
    raise exception using errcode = '42501', message = 'WORKING_TIME_PERMISSION_DENIED: contexte planning.';
  end if;

  if public.current_person_id() <> target_person.id
    and not public.working_time_can_manage_entry_scope(target_person.company_id)
    and not public.working_time_captain_can_access_period(
      target_person.company_id, target_person.id, p_local_work_date, p_local_work_date
    ) then
    raise exception using errcode = '42501', message = 'WORKING_TIME_PERMISSION_DENIED: contexte planning.';
  end if;

  select assignment.* into target_assignment
  from public.planning_assignments assignment
  where assignment.company_id = target_person.company_id
    and p_local_work_date between assignment.starts_on and assignment.ends_on
    and coalesce(assignment.confirmation_status, '') <> 'cancelled'
    and (assignment.crew_person_id = target_person.id or assignment.captain_person_id = target_person.id)
    and public.planning_status_is_working(public.planning_effective_person_status(
      assignment.company_id, target_person.id, p_local_work_date,
      assignment.vessel_id, assignment.status_label
    ))
  order by
    case when assignment.crew_person_id = target_person.id then 0 else 1 end,
    (assignment.confirmation_status = 'confirmed') desc,
    assignment.id desc
  limit 1;

  if target_assignment.id is not null then
    effective_status := public.planning_effective_person_status(
      target_assignment.company_id, target_person.id, p_local_work_date,
      target_assignment.vessel_id, target_assignment.status_label
    );
  end if;

  if target_assignment.id is null then
    return jsonb_build_object(
      'assignment_id', null,
      'vessel_id', null,
      'watch_group', null,
      'status_label', effective_status,
      'approver_person_id', null,
      'captain_candidates', '[]'::jsonb
    );
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'person_id', candidate.id,
    'first_name', candidate.first_name,
    'last_name', candidate.last_name,
    'name', trim(candidate.first_name || ' ' || candidate.last_name)
  ) order by
    candidate.id <> target_assignment.captain_person_id,
    candidate.last_name,
    candidate.first_name), '[]'::jsonb),
    (array_agg(candidate.id order by
      candidate.id <> target_assignment.captain_person_id,
      candidate.last_name,
      candidate.first_name))[1]
  into candidates, preferred_approver_id
  from public.people candidate
  where candidate.company_id = target_person.company_id
    and candidate.id <> target_person.id
    and candidate.active
    and candidate.user_id is not null
    and exists (
      select 1 from public.user_roles candidate_role
      where candidate_role.user_id = candidate.user_id
        and candidate_role.company_id = candidate.company_id
        and candidate_role.role_key = 'capitaine'
    )
    and exists (
      select 1
      from public.planning_assignments candidate_assignment
      where candidate_assignment.company_id = target_assignment.company_id
        and candidate_assignment.vessel_id = target_assignment.vessel_id
        and lower(trim(coalesce(candidate_assignment.watch_group, '')))
          = lower(trim(coalesce(target_assignment.watch_group, '')))
        and p_local_work_date between candidate_assignment.starts_on and candidate_assignment.ends_on
        and coalesce(candidate_assignment.confirmation_status, '') <> 'cancelled'
        and (candidate_assignment.crew_person_id = candidate.id or candidate_assignment.captain_person_id = candidate.id)
        and public.planning_status_is_working(public.planning_effective_person_status(
          candidate_assignment.company_id, candidate.id, p_local_work_date,
          candidate_assignment.vessel_id, candidate_assignment.status_label
        ))
    );

  return jsonb_build_object(
    'assignment_id', target_assignment.id,
    'vessel_id', target_assignment.vessel_id,
    'watch_group', nullif(trim(coalesce(target_assignment.watch_group, '')), ''),
    'status_label', effective_status,
    'approver_person_id', preferred_approver_id,
    'captain_candidates', candidates
  );
end;
$$;

create or replace function public.working_time_captain_matches_day(
  target_company_id bigint,
  target_person_id bigint,
  target_captain_person_id bigint,
  target_local_work_date date
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select target_person_id <> target_captain_person_id
    and exists (
      select 1
      from public.people captain
      join public.user_roles captain_role
        on captain_role.user_id = captain.user_id
       and captain_role.company_id = captain.company_id
       and captain_role.role_key = 'capitaine'
      join public.planning_assignments subject_assignment
        on subject_assignment.company_id = captain.company_id
       and target_local_work_date between subject_assignment.starts_on and subject_assignment.ends_on
       and coalesce(subject_assignment.confirmation_status, '') <> 'cancelled'
       and (subject_assignment.crew_person_id = target_person_id or subject_assignment.captain_person_id = target_person_id)
      join public.planning_assignments captain_assignment
        on captain_assignment.company_id = subject_assignment.company_id
       and captain_assignment.vessel_id = subject_assignment.vessel_id
       and lower(trim(coalesce(captain_assignment.watch_group, '')))
         = lower(trim(coalesce(subject_assignment.watch_group, '')))
       and target_local_work_date between captain_assignment.starts_on and captain_assignment.ends_on
       and coalesce(captain_assignment.confirmation_status, '') <> 'cancelled'
       and (captain_assignment.crew_person_id = captain.id or captain_assignment.captain_person_id = captain.id)
      where captain.id = target_captain_person_id
        and captain.company_id = target_company_id
        and captain.active
        and public.planning_status_is_working(public.planning_effective_person_status(
          subject_assignment.company_id, target_person_id, target_local_work_date,
          subject_assignment.vessel_id, subject_assignment.status_label
        ))
        and public.planning_status_is_working(public.planning_effective_person_status(
          captain_assignment.company_id, captain.id, target_local_work_date,
          captain_assignment.vessel_id, captain_assignment.status_label
        ))
    );
$$;

create or replace function public.working_time_day_has_non_compliance(
  p_register_id bigint,
  p_local_work_date date
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.working_time_registers register
    where register.id = p_register_id
      and exists (
        select 1 from public.working_time_intervals work_interval
        where work_interval.register_id = register.id
          and work_interval.local_work_date = p_local_work_date
          and work_interval.voided_at is null
      )
      and exists (
        select 1 from public.working_time_calculation_windows calculation
        where calculation.company_id = register.company_id
          and calculation.person_id = register.person_id
          and calculation.local_window_end_date = p_local_work_date
          and calculation.is_compliant is false
      )
  );
$$;

create or replace function public.working_time_actor_can_edit_day(
  p_register_id bigint,
  p_local_work_date date
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.working_time_registers register
    left join public.working_time_day_approvals approval
      on approval.register_id = register.id
     and approval.local_work_date = p_local_work_date
    where register.id = p_register_id
      and public.user_belongs_to_company(register.company_id)
      and coalesce(approval.status, 'draft') <> 'validated'
      and (
        public.working_time_can_manage_entry_scope(register.company_id)
        or (
          approval.status = 'submitted'
          and approval.approver_person_id = public.current_person_id()
          and public.has_company_role(register.company_id, array['capitaine'])
        )
        or (
          approval.id is null
          and register.person_id = public.current_person_id()
          and public.has_company_role(register.company_id, array['marin', 'capitaine'])
        )
        or (
          approval.id is null
          and public.working_time_captain_can_access_period(
            register.company_id, register.person_id, p_local_work_date, p_local_work_date
          )
        )
      )
  );
$$;

revoke all on function public.working_time_day_context(bigint, date) from public, anon, authenticated;
revoke all on function public.working_time_captain_matches_day(bigint, bigint, bigint, date) from public, anon, authenticated;
revoke all on function public.working_time_day_has_non_compliance(bigint, date) from public, anon, authenticated;
revoke all on function public.working_time_actor_can_edit_day(bigint, date) from public, anon, authenticated;
grant execute on function public.working_time_day_context(bigint, date) to authenticated;

create or replace function public.working_time_guard_register_lock()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_register_id bigint := case when tg_op = 'DELETE' then old.register_id else new.register_id end;
  target_company_id bigint;
  target_person_id bigint;
  old_work_date date := case
    when tg_table_name = 'working_time_intervals' and tg_op <> 'INSERT' then old.local_work_date
    when tg_table_name = 'working_time_day_comments' and tg_op <> 'INSERT' then old.local_work_date
    else null
  end;
  new_work_date date := case
    when tg_op = 'DELETE' then null
    when tg_table_name = 'working_time_intervals' then new.local_work_date
    when tg_table_name = 'working_time_day_comments' then new.local_work_date
    else null
  end;
  import_batch_setting text := nullif(current_setting('seapilot.working_time_admin_import_batch_id', true), '');
  admin_import_override boolean := false;
begin
  select register.company_id, register.person_id
  into target_company_id, target_person_id
  from public.working_time_registers register
  where register.id = target_register_id;

  if import_batch_setting ~ '^[0-9]+$' then
    select exists (
      select 1
      from public.working_time_import_batches batch
      where batch.id = import_batch_setting::bigint
        and batch.company_id = target_company_id
        and batch.selected_person_id = target_person_id
        and batch.status = 'preview_ready'
        and public.working_time_can_manage_imports(batch.company_id)
    ) into admin_import_override;
  end if;
  if admin_import_override then
    return case when tg_op = 'DELETE' then old else new end;
  end if;

  if old_work_date is not null
    and not public.working_time_actor_can_edit_day(target_register_id, old_work_date) then
    raise exception using errcode = '55000', message = 'WORKING_TIME_DAY_LOCKED.';
  end if;
  if new_work_date is not null
    and new_work_date is distinct from old_work_date
    and not public.working_time_actor_can_edit_day(target_register_id, new_work_date) then
    raise exception using errcode = '55000', message = 'WORKING_TIME_DAY_LOCKED.';
  end if;
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

create or replace function public.save_working_time_interval(
  p_register_id bigint,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_timezone_name text,
  p_vessel_id bigint default null,
  p_watch_group text default null,
  p_comment text default null,
  p_interval_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_register public.working_time_registers%rowtype;
  target_interval public.working_time_intervals%rowtype;
  target_assignment public.planning_assignments%rowtype;
  actor_person_id bigint := public.current_person_id();
  target_local_date date;
  target_offset_minutes integer;
  recommendation jsonb;
  saved_id bigint;
  existing_approval public.working_time_day_approvals%rowtype;
begin
  if (select auth.uid()) is null or actor_person_id is null then
    raise exception using errcode = '42501', message = 'WORKING_TIME_PROFILE_NOT_LINKED: fiche RH requise.';
  end if;
  select * into target_register from public.working_time_registers register where register.id = p_register_id for update;
  if target_register.id is null or not public.user_belongs_to_company(target_register.company_id) then
    raise exception using errcode = '42501', message = 'WORKING_TIME_PERMISSION_DENIED: modification du registre.';
  end if;
  if p_ends_at <= p_starts_at then
    raise exception using errcode = '22023', message = 'WORKING_TIME_INTERVAL_INVALID.';
  end if;
  if not exists (select 1 from pg_catalog.pg_timezone_names zone where zone.name = p_timezone_name) then
    raise exception using errcode = '22023', message = 'WORKING_TIME_TIMEZONE_INVALID.';
  end if;

  target_local_date := (p_starts_at at time zone p_timezone_name)::date;
  target_offset_minutes := (
    extract(epoch from ((p_starts_at at time zone p_timezone_name) - (p_starts_at at time zone 'UTC'))) / 60
  )::integer;
  if target_local_date not between target_register.period_start and target_register.period_end then
    raise exception using errcode = '22023', message = 'WORKING_TIME_INTERVAL_OUTSIDE_REGISTER.';
  end if;

  if p_interval_id is not null then
    select * into target_interval
    from public.working_time_intervals work_interval
    where work_interval.id = p_interval_id
    for update;
    if target_interval.id is null or target_interval.register_id <> target_register.id or target_interval.voided_at is not null then
      raise exception using errcode = '23503', message = 'WORKING_TIME_INTERVAL_NOT_FOUND.';
    end if;
    if target_interval.local_work_date <> target_local_date
      and exists (
        select 1 from public.working_time_day_approvals approval
        where approval.register_id = target_register.id
          and approval.local_work_date = target_interval.local_work_date
          and approval.status = 'submitted'
      ) then
      raise exception using errcode = '55000', message = 'WORKING_TIME_SUBMITTED_DAY_MOVE_FORBIDDEN.';
    end if;
    if not public.working_time_actor_can_edit_day(target_register.id, target_interval.local_work_date) then
      raise exception using errcode = '42501', message = 'WORKING_TIME_PERMISSION_DENIED: intervalle d''origine.';
    end if;
  end if;
  if not public.working_time_actor_can_edit_day(target_register.id, target_local_date) then
    raise exception using errcode = '42501', message = 'WORKING_TIME_PERMISSION_DENIED: journee verrouillee.';
  end if;

  select assignment.* into target_assignment
  from public.planning_assignments assignment
  where assignment.company_id = target_register.company_id
    and target_local_date between assignment.starts_on and assignment.ends_on
    and coalesce(assignment.confirmation_status, '') <> 'cancelled'
    and (assignment.crew_person_id = target_register.person_id or assignment.captain_person_id = target_register.person_id)
    and public.planning_status_is_working(public.planning_effective_person_status(
      assignment.company_id, target_register.person_id, target_local_date,
      assignment.vessel_id, assignment.status_label
    ))
  order by case when assignment.crew_person_id = target_register.person_id then 0 else 1 end, assignment.id desc
  limit 1;
  if target_assignment.id is null then
    raise exception using errcode = '23514', message = 'WORKING_TIME_PLANNING_ASSIGNMENT_REQUIRED.';
  end if;

  select public.working_time_interval_recommendation(
    target_register.person_id, p_starts_at, p_ends_at, p_timezone_name,
    target_assignment.vessel_id, nullif(trim(coalesce(target_assignment.watch_group, '')), ''), p_interval_id
  ) into recommendation;
  if recommendation->>'status' in ('alerte', 'non_conforme')
    and nullif(trim(coalesce(p_comment, '')), '') is null then
    raise exception using errcode = '23514', message = 'WORKING_TIME_ALERT_COMMENT_REQUIRED.';
  end if;

  select * into existing_approval
  from public.working_time_day_approvals approval
  where approval.register_id = target_register.id
    and approval.local_work_date = target_local_date;

  if p_interval_id is null then
    insert into public.working_time_intervals (
      company_id, register_id, person_id, local_work_date, starts_at, ends_at,
      timezone_name, utc_offset_minutes, vessel_id, watch_group, comment,
      author_user_id, author_person_id, source_type, source_metadata
    ) values (
      target_register.company_id, target_register.id, target_register.person_id,
      target_local_date, p_starts_at, p_ends_at, p_timezone_name, target_offset_minutes,
      target_assignment.vessel_id, nullif(trim(coalesce(target_assignment.watch_group, '')), ''),
      nullif(trim(coalesce(p_comment, '')), ''), (select auth.uid()), actor_person_id, 'manual',
      jsonb_build_object('planning_assignment_id', target_assignment.id)
    ) returning id into saved_id;
  else
    update public.working_time_intervals
    set local_work_date = target_local_date,
        starts_at = p_starts_at,
        ends_at = p_ends_at,
        timezone_name = p_timezone_name,
        utc_offset_minutes = target_offset_minutes,
        vessel_id = target_assignment.vessel_id,
        watch_group = nullif(trim(coalesce(target_assignment.watch_group, '')), ''),
        comment = nullif(trim(coalesce(p_comment, '')), ''),
        source_metadata = coalesce(source_metadata, '{}'::jsonb)
          || jsonb_build_object('planning_assignment_id', target_assignment.id),
        updated_at = now()
    where id = target_interval.id
    returning id into saved_id;
  end if;

  if existing_approval.status = 'submitted' and existing_approval.approver_person_id = actor_person_id then
    insert into public.working_time_day_approval_events (
      company_id, day_approval_id, register_id, person_id, local_work_date,
      event_type, previous_status, new_status, actor_user_id, actor_person_id,
      actor_identity_snapshot, interval_snapshot
    ) values (
      target_register.company_id, existing_approval.id, target_register.id,
      target_register.person_id, target_local_date, 'captain_corrected', 'submitted', 'submitted',
      (select auth.uid()), actor_person_id,
      public.working_time_person_identity_snapshot(actor_person_id, target_register.company_id),
      (select coalesce(jsonb_agg(jsonb_build_object(
        'interval_id', work_interval.id, 'starts_at', work_interval.starts_at,
        'ends_at', work_interval.ends_at, 'vessel_id', work_interval.vessel_id,
        'watch_group', work_interval.watch_group, 'comment', work_interval.comment
      ) order by work_interval.starts_at), '[]'::jsonb)
      from public.working_time_intervals work_interval
      where work_interval.register_id = target_register.id
        and work_interval.local_work_date = target_local_date
        and work_interval.voided_at is null)
    );
  end if;
  return saved_id;
end;
$$;

create or replace function public.save_working_time_phases(
  p_register_id bigint,
  p_phases jsonb,
  p_timezone_name text,
  p_vessel_id bigint default null,
  p_watch_group text default null,
  p_comment text default null
)
returns bigint[]
language plpgsql
security definer
set search_path = ''
as $$
declare
  target public.working_time_registers%rowtype;
  phase record;
  first_start timestamptz;
  target_local_date date;
  ids bigint[] := array[]::bigint[];
begin
  select * into target from public.working_time_registers where id = p_register_id for update;
  if target.id is null then raise exception 'WORKING_TIME_REGISTER_NOT_FOUND'; end if;
  select min(item.starts_at) into first_start
  from jsonb_to_recordset(p_phases) item(starts_at timestamptz, ends_at timestamptz);
  if first_start is null then
    raise exception using errcode = '22023', message = 'WORKING_TIME_PHASES_INVALID.';
  end if;
  target_local_date := (first_start at time zone p_timezone_name)::date;
  if not public.working_time_actor_can_edit_day(target.id, target_local_date) then
    raise exception using errcode = '42501', message = 'WORKING_TIME_PERMISSION_DENIED: journee verrouillee.';
  end if;
  if exists (
    select 1
    from jsonb_to_recordset(p_phases) proposed(starts_at timestamptz, ends_at timestamptz)
    join public.working_time_intervals existing
      on existing.person_id = target.person_id
     and existing.voided_at is null
     and proposed.starts_at < existing.ends_at
     and proposed.ends_at > existing.starts_at
  ) then
    raise exception using errcode = '22023', message = 'WORKING_TIME_PHASES_EXISTING_OVERLAP';
  end if;
  for phase in
    select * from jsonb_to_recordset(p_phases) item(starts_at timestamptz, ends_at timestamptz) order by starts_at
  loop
    ids := array_append(ids, public.save_working_time_interval(
      p_register_id, phase.starts_at, phase.ends_at, p_timezone_name,
      p_vessel_id, p_watch_group, p_comment, null
    ));
  end loop;
  return ids;
end;
$$;

create or replace function public.void_working_time_interval(
  p_interval_id bigint,
  p_reason text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_interval public.working_time_intervals%rowtype;
begin
  if length(trim(coalesce(p_reason, ''))) < 2 then
    raise exception using errcode = '22023', message = 'WORKING_TIME_VOID_REASON_REQUIRED.';
  end if;
  select * into target_interval
  from public.working_time_intervals work_interval
  where work_interval.id = p_interval_id and work_interval.voided_at is null
  for update;
  if target_interval.id is null then
    raise exception using errcode = '23503', message = 'WORKING_TIME_INTERVAL_NOT_FOUND.';
  end if;
  if not public.working_time_actor_can_edit_day(target_interval.register_id, target_interval.local_work_date) then
    raise exception using errcode = '42501', message = 'WORKING_TIME_PERMISSION_DENIED: journee verrouillee.';
  end if;
  update public.working_time_intervals
  set voided_at = now(), voided_by = (select auth.uid()), void_reason = trim(p_reason)
  where id = target_interval.id;
  return target_interval.id;
end;
$$;

revoke all on function public.save_working_time_interval(bigint, timestamptz, timestamptz, text, bigint, text, text, bigint) from public, anon, authenticated;
revoke all on function public.save_working_time_phases(bigint, jsonb, text, bigint, text, text) from public, anon, authenticated;
revoke all on function public.void_working_time_interval(bigint, text) from public, anon, authenticated;
grant execute on function public.save_working_time_interval(bigint, timestamptz, timestamptz, text, bigint, text, text, bigint) to authenticated;
grant execute on function public.save_working_time_phases(bigint, jsonb, text, bigint, text, text) to authenticated;
grant execute on function public.void_working_time_interval(bigint, text) to authenticated;

create or replace function public.submit_working_time_day(
  p_register_id bigint,
  p_local_work_date date
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_register public.working_time_registers%rowtype;
  actor_person_id bigint := public.current_person_id();
  context_data jsonb;
  approver_person_id bigint;
  assignment_id bigint;
  resolved_vessel_id bigint;
  resolved_watch_group text;
  intervals_data jsonb;
  signature_data jsonb := '{}'::jsonb;
  actor_signature public.working_time_profile_signatures%rowtype;
  saved_approval public.working_time_day_approvals%rowtype;
  previous_status text;
begin
  select * into target_register
  from public.working_time_registers register
  where register.id = p_register_id
  for update;
  if (select auth.uid()) is null or actor_person_id is null
    or target_register.id is null
    or target_register.person_id <> actor_person_id
    or not public.has_company_role(target_register.company_id, array['marin', 'capitaine']) then
    raise exception using errcode = '42501', message = 'WORKING_TIME_PERMISSION_DENIED: soumission de la journee.';
  end if;
  if p_local_work_date not between target_register.period_start and target_register.period_end then
    raise exception using errcode = '22023', message = 'WORKING_TIME_SUBMISSION_DATE_INVALID.';
  end if;
  if not exists (
    select 1 from public.working_time_intervals work_interval
    where work_interval.register_id = target_register.id
      and work_interval.local_work_date = p_local_work_date
      and work_interval.voided_at is null
  ) then
    raise exception using errcode = '23514', message = 'WORKING_TIME_EMPTY_DAY.';
  end if;

  context_data := public.working_time_day_context(target_register.person_id, p_local_work_date);
  approver_person_id := nullif(context_data->>'approver_person_id', '')::bigint;
  assignment_id := nullif(context_data->>'assignment_id', '')::bigint;
  resolved_vessel_id := nullif(context_data->>'vessel_id', '')::bigint;
  resolved_watch_group := nullif(trim(coalesce(context_data->>'watch_group', '')), '');
  if assignment_id is null then
    raise exception using errcode = '23514', message = 'WORKING_TIME_PLANNING_ASSIGNMENT_REQUIRED.';
  end if;
  if approver_person_id is null
    or not public.working_time_captain_matches_day(
      target_register.company_id, target_register.person_id, approver_person_id, p_local_work_date
    ) then
    raise exception using errcode = '23514', message = 'WORKING_TIME_CAPTAIN_APPROVER_REQUIRED.';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'interval_id', work_interval.id,
    'local_work_date', work_interval.local_work_date,
    'starts_at', work_interval.starts_at,
    'ends_at', work_interval.ends_at,
    'timezone_name', work_interval.timezone_name,
    'vessel_id', work_interval.vessel_id,
    'watch_group', work_interval.watch_group,
    'comment', work_interval.comment
  ) order by work_interval.starts_at), '[]'::jsonb)
  into intervals_data
  from public.working_time_intervals work_interval
  where work_interval.register_id = target_register.id
    and work_interval.local_work_date = p_local_work_date
    and work_interval.voided_at is null;

  select * into actor_signature
  from public.working_time_profile_signatures signature
  where signature.company_id = target_register.company_id
    and signature.person_id = actor_person_id
    and signature.valid_to is null
  order by signature.version_number desc
  limit 1;
  if actor_signature.id is not null then
    signature_data := jsonb_build_object(
      'signature_id', actor_signature.id,
      'signer_person_id', actor_person_id,
      'signed_at', clock_timestamp(),
      'version_number', actor_signature.version_number,
      'storage_bucket', actor_signature.storage_bucket,
      'storage_path', actor_signature.storage_path,
      'mime_type', actor_signature.mime_type,
      'file_size_bytes', actor_signature.file_size_bytes,
      'sha256', actor_signature.sha256
    );
  end if;

  select approval.status into previous_status
  from public.working_time_day_approvals approval
  where approval.register_id = target_register.id
    and approval.local_work_date = p_local_work_date
  for update;
  if previous_status = 'validated' then
    raise exception using errcode = '55000', message = 'WORKING_TIME_DAY_LOCKED.';
  end if;

  insert into public.working_time_day_approvals (
    company_id, register_id, person_id, local_work_date, status,
    planning_assignment_id, vessel_id, watch_group, approver_person_id,
    submitted_by, submitted_by_person_id, submitted_at,
    subject_identity_snapshot, approver_identity_snapshot,
    vessel_snapshot, watch_snapshot, signature_snapshot, interval_snapshot,
    updated_at
  ) values (
    target_register.company_id, target_register.id, target_register.person_id,
    p_local_work_date, 'submitted', assignment_id, resolved_vessel_id,
    resolved_watch_group, approver_person_id, (select auth.uid()), actor_person_id,
    clock_timestamp(),
    public.working_time_person_identity_snapshot(actor_person_id, target_register.company_id),
    public.working_time_person_identity_snapshot(approver_person_id, target_register.company_id),
    coalesce((select jsonb_build_object('vessel_id', vessel.id, 'name', vessel.name, 'acronym', vessel.acronym)
      from public.vessels vessel where vessel.id = resolved_vessel_id), '{}'::jsonb),
    jsonb_build_object('watch_group', resolved_watch_group),
    signature_data, intervals_data, now()
  )
  on conflict (register_id, local_work_date) do update
  set status = 'submitted',
      planning_assignment_id = excluded.planning_assignment_id,
      vessel_id = excluded.vessel_id,
      watch_group = excluded.watch_group,
      approver_person_id = excluded.approver_person_id,
      submitted_by = excluded.submitted_by,
      submitted_by_person_id = excluded.submitted_by_person_id,
      submitted_at = excluded.submitted_at,
      validated_by = null,
      validated_by_person_id = null,
      validated_at = null,
      subject_identity_snapshot = excluded.subject_identity_snapshot,
      approver_identity_snapshot = excluded.approver_identity_snapshot,
      vessel_snapshot = excluded.vessel_snapshot,
      watch_snapshot = excluded.watch_snapshot,
      signature_snapshot = excluded.signature_snapshot,
      interval_snapshot = excluded.interval_snapshot,
      non_compliance_snapshot = '[]'::jsonb,
      updated_at = now()
  returning * into saved_approval;

  insert into public.working_time_day_approval_events (
    company_id, day_approval_id, register_id, person_id, local_work_date,
    event_type, previous_status, new_status, actor_user_id, actor_person_id,
    actor_identity_snapshot, interval_snapshot
  ) values (
    target_register.company_id, saved_approval.id, target_register.id,
    target_register.person_id, p_local_work_date, 'submitted', previous_status,
    'submitted', (select auth.uid()), actor_person_id,
    public.working_time_person_identity_snapshot(actor_person_id, target_register.company_id),
    intervals_data
  );
  return saved_approval.id;
end;
$$;

create or replace function public.validate_working_time_day(
  p_day_approval_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_approval public.working_time_day_approvals%rowtype;
  target_register public.working_time_registers%rowtype;
  actor_person_id bigint := public.current_person_id();
  actor_signature public.working_time_profile_signatures%rowtype;
  intervals_data jsonb;
  non_compliance_data jsonb;
  signature_data jsonb;
  saved_event_id bigint;
  is_management boolean;
begin
  select * into target_approval
  from public.working_time_day_approvals approval
  where approval.id = p_day_approval_id
  for update;
  select * into target_register
  from public.working_time_registers register
  where register.id = target_approval.register_id;
  is_management := public.has_company_role(target_approval.company_id, array['admin', 'armement']);

  if (select auth.uid()) is null or actor_person_id is null
    or target_approval.id is null or target_approval.status <> 'submitted'
    or actor_person_id = target_approval.person_id
    or not (
      is_management
      or (
        target_approval.approver_person_id = actor_person_id
        and public.has_company_role(target_approval.company_id, array['capitaine'])
      )
    ) then
    raise exception using errcode = '42501', message = 'WORKING_TIME_PERMISSION_DENIED: validation de la journee.';
  end if;

  if public.working_time_day_has_non_compliance(target_register.id, target_approval.local_work_date)
    and not exists (
      select 1
      from public.working_time_day_comments day_comment
      where day_comment.register_id = target_register.id
        and day_comment.local_work_date = target_approval.local_work_date
        and day_comment.cause_category is not null
        and length(trim(coalesce(day_comment.operational_context, ''))) >= 2
        and length(trim(coalesce(day_comment.immediate_action, ''))) >= 2
        and length(trim(coalesce(day_comment.compensatory_rest_plan, ''))) >= 2
        and length(trim(day_comment.comment)) >= 2
        and (day_comment.authored_by_person_id = actor_person_id or is_management)
    ) then
    raise exception using errcode = '23514', message = 'WORKING_TIME_NON_COMPLIANCE_DETAILS_REQUIRED.';
  end if;

  select * into actor_signature
  from public.working_time_profile_signatures profile_signature
  where profile_signature.company_id = target_approval.company_id
    and profile_signature.person_id = actor_person_id
    and profile_signature.valid_to is null
  order by profile_signature.version_number desc
  limit 1;
  if actor_signature.id is null then
    raise exception using errcode = '23514', message = 'WORKING_TIME_ACTIVE_SIGNATURE_REQUIRED.';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'interval_id', work_interval.id, 'local_work_date', work_interval.local_work_date,
    'starts_at', work_interval.starts_at, 'ends_at', work_interval.ends_at,
    'timezone_name', work_interval.timezone_name, 'vessel_id', work_interval.vessel_id,
    'watch_group', work_interval.watch_group, 'comment', work_interval.comment,
    'author_user_id', work_interval.author_user_id,
    'author_person_id', work_interval.author_person_id,
    'source_type', work_interval.source_type
  ) order by work_interval.starts_at), '[]'::jsonb)
  into intervals_data
  from public.working_time_intervals work_interval
  where work_interval.register_id = target_register.id
    and work_interval.local_work_date = target_approval.local_work_date
    and work_interval.voided_at is null;

  select coalesce(jsonb_agg(jsonb_build_object(
    'local_work_date', calculation.local_window_end_date,
    'violation_codes', calculation.violation_codes,
    'work_24h_seconds', calculation.work_24h_seconds,
    'rest_24h_seconds', calculation.rest_24h_seconds,
    'work_7d_seconds', calculation.work_7d_seconds,
    'rest_7d_seconds', calculation.rest_7d_seconds
  ) order by calculation.window_end), '[]'::jsonb)
  into non_compliance_data
  from public.working_time_calculation_windows calculation
  where calculation.company_id = target_register.company_id
    and calculation.person_id = target_register.person_id
    and calculation.local_window_end_date = target_approval.local_work_date
    and calculation.is_compliant is false
    and public.working_time_day_has_non_compliance(target_register.id, target_approval.local_work_date);

  signature_data := jsonb_build_object(
    'signature_id', actor_signature.id,
    'signer_person_id', actor_person_id,
    'signer_user_id', (select auth.uid()),
    'signed_at', clock_timestamp(),
    'version_number', actor_signature.version_number,
    'storage_bucket', actor_signature.storage_bucket,
    'storage_path', actor_signature.storage_path,
    'mime_type', actor_signature.mime_type,
    'file_size_bytes', actor_signature.file_size_bytes,
    'sha256', actor_signature.sha256
  );

  update public.working_time_day_approvals
  set status = 'validated',
      validated_by = (select auth.uid()),
      validated_by_person_id = actor_person_id,
      validated_at = clock_timestamp(),
      approver_identity_snapshot = public.working_time_person_identity_snapshot(actor_person_id, target_approval.company_id),
      signature_snapshot = signature_data,
      interval_snapshot = intervals_data,
      non_compliance_snapshot = non_compliance_data,
      updated_at = now()
  where id = target_approval.id;

  insert into public.working_time_day_approval_events (
    company_id, day_approval_id, register_id, person_id, local_work_date,
    event_type, previous_status, new_status, actor_user_id, actor_person_id,
    actor_identity_snapshot, interval_snapshot, non_compliance_snapshot
  ) values (
    target_approval.company_id, target_approval.id, target_approval.register_id,
    target_approval.person_id, target_approval.local_work_date, 'validated',
    'submitted', 'validated', (select auth.uid()), actor_person_id,
    public.working_time_person_identity_snapshot(actor_person_id, target_approval.company_id),
    intervals_data, non_compliance_data
  ) returning id into saved_event_id;
  return saved_event_id;
end;
$$;

create or replace function public.working_time_can_comment_register(
  target_register_id bigint,
  target_local_date date
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.working_time_registers register
    join public.working_time_day_approvals approval
      on approval.register_id = register.id
     and approval.local_work_date = target_local_date
     and approval.status = 'submitted'
    where register.id = target_register_id
      and public.user_belongs_to_company(register.company_id)
      and (
        public.working_time_can_manage_entry_scope(register.company_id)
        or (
          approval.approver_person_id = public.current_person_id()
          and public.has_company_role(register.company_id, array['capitaine'])
        )
      )
  );
$$;

create or replace function public.save_working_time_day_comment(
  p_register_id bigint,
  p_local_work_date date,
  p_cause_category text,
  p_operational_context text,
  p_immediate_action text,
  p_compensatory_rest_plan text,
  p_comment text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_register public.working_time_registers%rowtype;
  saved_id bigint;
begin
  if p_cause_category not in (
    'unexpected_operation', 'safety_emergency', 'weather', 'handover',
    'breakdown_maintenance', 'understaffing', 'other'
  )
    or length(trim(coalesce(p_operational_context, ''))) < 2
    or length(trim(coalesce(p_immediate_action, ''))) < 2
    or length(trim(coalesce(p_compensatory_rest_plan, ''))) < 2
    or length(trim(coalesce(p_comment, ''))) < 2 then
    raise exception using errcode = '22023', message = 'WORKING_TIME_NON_COMPLIANCE_DETAILS_REQUIRED.';
  end if;
  select * into target_register from public.working_time_registers where id = p_register_id for update;
  if target_register.id is null or not public.working_time_can_comment_register(p_register_id, p_local_work_date) then
    raise exception using errcode = '42501', message = 'WORKING_TIME_PERMISSION_DENIED: commentaire capitaine.';
  end if;
  if not public.working_time_day_has_non_compliance(p_register_id, p_local_work_date) then
    raise exception using errcode = '22023', message = 'WORKING_TIME_COMMENT_DAY_IS_COMPLIANT.';
  end if;
  insert into public.working_time_day_comments (
    company_id, register_id, person_id, local_work_date,
    cause_category, operational_context, immediate_action,
    compensatory_rest_plan, comment, authored_by, authored_by_person_id
  ) values (
    target_register.company_id, target_register.id, target_register.person_id,
    p_local_work_date, p_cause_category, trim(p_operational_context),
    trim(p_immediate_action), trim(p_compensatory_rest_plan), trim(p_comment),
    (select auth.uid()), public.current_person_id()
  )
  on conflict (register_id, local_work_date) do update
  set cause_category = excluded.cause_category,
      operational_context = excluded.operational_context,
      immediate_action = excluded.immediate_action,
      compensatory_rest_plan = excluded.compensatory_rest_plan,
      comment = excluded.comment,
      authored_by = excluded.authored_by,
      authored_by_person_id = excluded.authored_by_person_id,
      updated_at = now()
  returning id into saved_id;
  return saved_id;
end;
$$;

revoke all on function public.submit_working_time_day(bigint, date) from public, anon, authenticated;
revoke all on function public.validate_working_time_day(bigint) from public, anon, authenticated;
revoke all on function public.working_time_can_comment_register(bigint, date) from public, anon, authenticated;
revoke all on function public.save_working_time_day_comment(bigint, date, text, text, text, text, text) from public, anon, authenticated;
grant execute on function public.submit_working_time_day(bigint, date) to authenticated;
grant execute on function public.validate_working_time_day(bigint) to authenticated;
grant execute on function public.save_working_time_day_comment(bigint, date, text, text, text, text, text) to authenticated;

-- The former month-level actions are retained only for historical function
-- dependencies. Authenticated clients must use the daily workflow above.
revoke execute on function public.request_working_time_captain_signature(bigint, bigint, date) from authenticated;
revoke execute on function public.validate_working_time_register(bigint) from authenticated;
revoke execute on function public.approve_own_working_time_register(bigint, date) from authenticated;
revoke execute on function public.transition_working_time_register(bigint, text, text) from authenticated;

-- Preserve already approved history while releasing future, empty days in old
-- month-level validated registers.
insert into public.working_time_day_approvals (
  company_id, register_id, person_id, local_work_date, status,
  planning_assignment_id, vessel_id, watch_group, approver_person_id,
  submitted_by, submitted_by_person_id, submitted_at,
  validated_by, validated_by_person_id, validated_at,
  subject_identity_snapshot, approver_identity_snapshot,
  vessel_snapshot, watch_snapshot, signature_snapshot,
  interval_snapshot, non_compliance_snapshot
)
select
  register.company_id,
  register.id,
  register.person_id,
  worked_day.local_work_date,
  'validated',
  worked_day.planning_assignment_id,
  worked_day.vessel_id,
  worked_day.watch_group,
  validation.actor_person_id,
  validation.actor_user_id,
  register.person_id,
  coalesce(validation.occurred_at, register.updated_at),
  validation.actor_user_id,
  validation.actor_person_id,
  coalesce(validation.occurred_at, register.updated_at),
  coalesce(validation.subject_identity_snapshot, '{}'::jsonb),
  coalesce(validation.actor_identity_snapshot, '{}'::jsonb),
  coalesce(validation.vessel_snapshot, '{}'::jsonb),
  coalesce(validation.watch_snapshot, '{}'::jsonb),
  coalesce(validation.signature_snapshot, '{}'::jsonb),
  worked_day.intervals,
  coalesce(validation.non_compliance_snapshot, '[]'::jsonb)
from public.working_time_registers register
join lateral (
  select
    work_interval.local_work_date,
    max(case when coalesce(work_interval.source_metadata->>'planning_assignment_id', '') ~ '^[0-9]+$'
      then (work_interval.source_metadata->>'planning_assignment_id')::bigint end) as planning_assignment_id,
    max(work_interval.vessel_id) as vessel_id,
    max(work_interval.watch_group) as watch_group,
    jsonb_agg(jsonb_build_object(
      'interval_id', work_interval.id,
      'local_work_date', work_interval.local_work_date,
      'starts_at', work_interval.starts_at,
      'ends_at', work_interval.ends_at,
      'timezone_name', work_interval.timezone_name,
      'vessel_id', work_interval.vessel_id,
      'watch_group', work_interval.watch_group,
      'comment', work_interval.comment,
      'source_type', work_interval.source_type
    ) order by work_interval.starts_at) as intervals
  from public.working_time_intervals work_interval
  where work_interval.register_id = register.id
    and work_interval.voided_at is null
  group by work_interval.local_work_date
) worked_day on true
join lateral (
  select validation_event.*
  from public.working_time_validations validation_event
  where validation_event.register_id = register.id
    and validation_event.event_type in ('captain_validated', 'approved_import')
    and validation_event.actor_person_id is not null
    and validation_event.actor_person_id <> register.person_id
  order by validation_event.occurred_at desc, validation_event.id desc
  limit 1
) validation on true
where register.status = 'validated'
on conflict (register_id, local_work_date) do nothing;

insert into public.working_time_day_approval_events (
  company_id, day_approval_id, register_id, person_id, local_work_date,
  event_type, previous_status, new_status, actor_user_id, actor_person_id,
  actor_identity_snapshot, interval_snapshot, non_compliance_snapshot,
  comment, occurred_at
)
select
  approval.company_id, approval.id, approval.register_id, approval.person_id,
  approval.local_work_date, 'legacy_validation_migrated', 'validated', 'validated',
  approval.validated_by, approval.validated_by_person_id,
  approval.approver_identity_snapshot, approval.interval_snapshot,
  approval.non_compliance_snapshot,
  'Migration de la validation mensuelle vers une cloture par jour.',
  coalesce(approval.validated_at, approval.updated_at)
from public.working_time_day_approvals approval
where approval.status = 'validated'
  and not exists (
    select 1 from public.working_time_day_approval_events approval_event
    where approval_event.day_approval_id = approval.id
  );

-- DPR context: an explicit vessel makes the project and crew independent from
-- the emitter, while Planning work statuses remain the sole crew filter.
drop function if exists public.dpr_entry_context(date);

create function public.dpr_entry_context(
  target_date date default current_date,
  target_vessel_id bigint default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  target_company_id bigint;
  actor_person_id bigint;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  target_company_id := public.current_planning_company_id();
  actor_person_id := public.current_person_id();
  if target_company_id is null or not public.user_belongs_to_company(target_company_id) then
    raise exception 'Active company membership required' using errcode = '42501';
  end if;
  if not exists (
    select 1
    from public.user_roles user_role
    join public.role_module_permissions permission
      on permission.role_key = user_role.role_key
     and permission.module_key = 'dpr'
     and permission.is_visible
    where user_role.user_id = (select auth.uid())
      and user_role.company_id = target_company_id
  ) then
    raise exception 'DPR module access required' using errcode = '42501';
  end if;

  return (
    with actor as (
      select person.id, person.first_name, person.last_name
      from public.people person
      where person.company_id = target_company_id and person.id = actor_person_id
      limit 1
    ),
    actor_assignment as (
      select assignment.vessel_id,
        nullif(trim(assignment.watch_group), '') as watch_group,
        assignment.captain_person_id
      from public.planning_assignments assignment
      where assignment.company_id = target_company_id
        and target_date between assignment.starts_on and assignment.ends_on
        and coalesce(assignment.confirmation_status, 'confirmed') <> 'cancelled'
        and (assignment.crew_person_id = actor_person_id or assignment.captain_person_id = actor_person_id)
        and public.planning_status_is_working(public.planning_effective_person_status(
          assignment.company_id, actor_person_id, target_date,
          assignment.vessel_id, assignment.status_label
        ))
      order by (assignment.crew_person_id = actor_person_id) desc,
        (assignment.confirmation_status = 'confirmed') desc,
        assignment.starts_on desc, assignment.id desc
      limit 1
    ),
    selected_scope as (
      select coalesce(target_vessel_id, (select vessel_id from actor_assignment)) as vessel_id,
        case when target_vessel_id is null then (select watch_group from actor_assignment) else null end as watch_group
    ),
    active_people as (
      select person.id, person.first_name, person.last_name,
        coalesce(nullif(trim(person.function_label), ''), nullif(trim(person.grade_label), ''), 'Sans fonction') as function_label,
        coalesce(person.grade_label, '') as grade_label,
        coalesce(person.role_label, '') as role_label
      from public.people person
      where person.company_id = target_company_id
        and person.active
        and (person.hired_on is null or person.hired_on <= target_date)
        and (person.departed_on is null or person.departed_on >= target_date)
    ),
    selected_crew as (
      select distinct assignment.crew_person_id as person_id,
        coalesce(assignment.watch_group, '') as watch_group
      from public.planning_assignments assignment
      cross join selected_scope scope
      where assignment.company_id = target_company_id
        and scope.vessel_id is not null
        and assignment.vessel_id = scope.vessel_id
        and target_date between assignment.starts_on and assignment.ends_on
        and coalesce(assignment.confirmation_status, 'confirmed') <> 'cancelled'
        and (scope.watch_group is null
          or lower(trim(coalesce(assignment.watch_group, ''))) = lower(trim(scope.watch_group)))
        and assignment.crew_person_id is not null
        and public.planning_status_is_working(public.planning_effective_person_status(
          assignment.company_id, assignment.crew_person_id, target_date,
          assignment.vessel_id, assignment.status_label
        ))
      union
      select distinct assignment.captain_person_id,
        coalesce(assignment.watch_group, '')
      from public.planning_assignments assignment
      cross join selected_scope scope
      where assignment.company_id = target_company_id
        and scope.vessel_id is not null
        and assignment.vessel_id = scope.vessel_id
        and target_date between assignment.starts_on and assignment.ends_on
        and coalesce(assignment.confirmation_status, 'confirmed') <> 'cancelled'
        and (scope.watch_group is null
          or lower(trim(coalesce(assignment.watch_group, ''))) = lower(trim(scope.watch_group)))
        and assignment.captain_person_id is not null
        and public.planning_status_is_working(public.planning_effective_person_status(
          assignment.company_id, assignment.captain_person_id, target_date,
          assignment.vessel_id, assignment.status_label
        ))
    ),
    matching_project as (
      select occurrence.catalog_project_id
      from public.planning_projects occurrence
      cross join selected_scope scope
      where occurrence.company_id = target_company_id
        and occurrence.catalog_project_id is not null
        and occurrence.cancelled_at is null
        and target_date between coalesce(occurrence.starts_on, target_date)
          and coalesce(occurrence.ends_on, occurrence.starts_on, target_date)
        and scope.vessel_id in (occurrence.primary_vessel_id, occurrence.secondary_vessel_id)
      order by (occurrence.primary_vessel_id = scope.vessel_id) desc,
        occurrence.starts_on desc nulls last, occurrence.id desc
      limit 1
    )
    select jsonb_build_object(
      'issuerPersonId', actor_person_id,
      'issuerName', coalesce(
        (select concat_ws(' ', actor.first_name, upper(actor.last_name)) from actor),
        (select coalesce(nullif(trim(profile.display_name), ''), profile.email)
          from public.profiles profile where profile.id = (select auth.uid())),
        'Utilisateur'
      ),
      'vesselId', (select vessel_id from selected_scope),
      'projectId', (select catalog_project_id from matching_project),
      'watchGroup', coalesce((select watch_group from selected_scope), ''),
      'people', coalesce((
        select jsonb_agg(jsonb_build_object(
          'id', person.id, 'firstName', person.first_name, 'lastName', person.last_name,
          'functionLabel', person.function_label, 'gradeLabel', person.grade_label,
          'roleLabel', person.role_label
        ) order by person.function_label, person.last_name, person.first_name)
        from active_people person
      ), '[]'::jsonb),
      'crewPersonIds', coalesce((
        select jsonb_agg(crew.person_id order by crew.person_id)
        from (select distinct selected.person_id from selected_crew selected where selected.person_id is not null) crew
        join active_people person on person.id = crew.person_id
      ), '[]'::jsonb)
    )
  );
end;
$$;

revoke all on function public.dpr_entry_context(date, bigint) from public, anon, authenticated;
grant execute on function public.dpr_entry_context(date, bigint) to authenticated;

comment on table public.working_time_day_approvals is
  'Current submission and approval state for one worked day inside a monthly register.';
comment on table public.working_time_day_approval_events is
  'Immutable audit events and frozen interval/compliance snapshots for daily approvals.';
comment on function public.submit_working_time_day(bigint, date) is
  'Submits one worked day to the non-self Capitaine resolved from an eligible Planning watch.';
comment on function public.validate_working_time_day(bigint) is
  'Validates and locks one submitted day without changing the enclosing monthly register status.';
comment on function public.dpr_entry_context(date, bigint) is
  'Returns DPR Planning defaults and only En mer/A terre crew for the selected date and optional vessel.';
