-- Persistent company-scoped display names and explicit relationships, independent of assignments.
create table public.organigramme_categories (
  company_id bigint not null default public.current_planning_company_id() references public.companies(id),
  key text not null check (key in ('office','external','functions','unassigned')),
  label text not null check (length(trim(label)) between 1 and 100),
  primary key(company_id,key)
);
create table public.organigramme_links (
  id bigint generated by default as identity primary key,
  company_id bigint not null default public.current_planning_company_id() references public.companies(id),
  source_category text not null check (source_category in ('office','external','functions','unassigned')),
  target_kind text not null check (target_kind in ('category','group','person')),
  target_key text not null check (length(trim(target_key)) between 1 and 300),
  target_section text not null default '' check (length(target_section)<=100),
  label text not null default '' check (length(label)<=100),
  check (target_kind <> 'category' or target_key <> source_category),
  check ((target_kind='group' and target_section<>'') or (target_kind<>'group' and target_section='')),
  unique(company_id,source_category,target_kind,target_key,target_section)
);
alter table public.organigramme_categories enable row level security;
alter table public.organigramme_links enable row level security;
grant select,insert,update,delete on public.organigramme_categories,public.organigramme_links to authenticated;
grant usage on sequence public.organigramme_links_id_seq to authenticated;

-- Validate referenced entities in the same company even when writing through PostgREST directly.
-- Empty/historical groups can retain their identity; only displayed groups are offered by the UI.
create function public.organigramme_target_allowed(company bigint, kind text, key text, section text)
returns boolean language plpgsql stable security invoker set search_path='' as $$
declare section_key text;
begin
  if not public.organigramme_has_access(company) then return false; end if;
  if kind='person' then
    if key !~ '^-?[1-9][0-9]{0,17}$' then return false; end if;
    if key::bigint>0 then return exists(select 1 from public.people p where p.id=key::bigint and p.company_id=company); end if;
    return exists(select 1 from public.organigramme_support s where s.id=-(key::bigint) and s.company_id=company and s.person_id is null);
  end if;
  section_key:=case when kind='category' then key else section end;
  if kind='category' and section_key in ('office','external','functions','unassigned') then return true; end if;
  if kind='group' and section_key in ('functions','unassigned') then return true; end if;
  if section_key ~ '^vessel-[1-9][0-9]{0,17}$' then
    return exists(select 1 from public.vessels v where v.id=substring(section_key from 8)::bigint and v.company_id=company and v.asset_kind='vessel');
  end if;
  return false;
end;
$$;
revoke all on function public.organigramme_target_allowed(bigint,text,text,text) from public,anon;
grant execute on function public.organigramme_target_allowed(bigint,text,text,text) to authenticated;

create policy organigramme_categories_read on public.organigramme_categories for select to authenticated using(public.organigramme_has_access(company_id));
create policy organigramme_categories_insert on public.organigramme_categories for insert to authenticated with check(public.organigramme_has_access(company_id));
create policy organigramme_categories_update on public.organigramme_categories for update to authenticated using(public.organigramme_has_access(company_id)) with check(public.organigramme_has_access(company_id));
create policy organigramme_categories_delete on public.organigramme_categories for delete to authenticated using(public.organigramme_has_access(company_id));
create policy organigramme_links_read on public.organigramme_links for select to authenticated using(public.organigramme_has_access(company_id));
create policy organigramme_links_insert on public.organigramme_links for insert to authenticated with check(public.organigramme_target_allowed(company_id,target_kind,target_key,target_section));
create policy organigramme_links_update on public.organigramme_links for update to authenticated using(public.organigramme_has_access(company_id)) with check(public.organigramme_target_allowed(company_id,target_kind,target_key,target_section));
create policy organigramme_links_delete on public.organigramme_links for delete to authenticated using(public.organigramme_has_access(company_id));

create function public.save_organigramme_category(p_key text,p_label text)
returns void language plpgsql security invoker set search_path='' as $$
declare company bigint:=public.current_planning_company_id();
begin
  if not public.organigramme_has_access(company) then raise exception 'Accès refusé à l’organigramme.' using errcode='42501'; end if;
  insert into public.organigramme_categories(company_id,key,label) values(company,p_key,trim(p_label))
  on conflict(company_id,key) do update set label=excluded.label;
end;
$$;
create function public.save_organigramme_link(p_id bigint,p_source text,p_kind text,p_key text,p_section text,p_label text)
returns bigint language plpgsql security invoker set search_path='' as $$
declare company bigint:=public.current_planning_company_id(); saved bigint;
begin
  if not public.organigramme_has_access(company) then raise exception 'Accès refusé à l’organigramme.' using errcode='42501'; end if;
  if p_id is null then
    insert into public.organigramme_links(company_id,source_category,target_kind,target_key,target_section,label)
    values(company,p_source,p_kind,p_key,p_section,trim(p_label)) returning id into saved;
  else
    update public.organigramme_links set source_category=p_source,target_kind=p_kind,target_key=p_key,target_section=p_section,label=trim(p_label)
    where id=p_id and company_id=company returning id into saved;
    if saved is null then raise exception 'Lien introuvable.' using errcode='P0002'; end if;
  end if;
  return saved;
end;
$$;
revoke all on function public.save_organigramme_category(text,text) from public,anon;
revoke all on function public.save_organigramme_link(bigint,text,text,text,text,text) from public,anon;
grant execute on function public.save_organigramme_category(text,text) to authenticated;
grant execute on function public.save_organigramme_link(bigint,text,text,text,text,text) to authenticated;

create or replace function public.organigramme_snapshot(p_as_of date default current_date)
returns jsonb language plpgsql stable security invoker set search_path = '' as $$
declare company bigint := public.current_planning_company_id(); result jsonb;
begin
  if not public.organigramme_has_access(company) then raise exception 'Accès refusé à l’organigramme.' using errcode='42501'; end if;
  if p_as_of is null then raise exception 'Date de situation obligatoire.' using errcode='22023'; end if;
  with staff as (
    select p.id, concat_ws(' ',p.first_name,p.last_name) as name,
      coalesce(nullif(trim(p.function_label),''),p.grade_label,'') as function_label, p.employment_population
    from public.people p where p.company_id=company
      and (p.hired_on<=p_as_of or (p.hired_on is null and p.active))
      and (p.departed_on is null or p.departed_on>p_as_of)
      and (p.active or p.departed_on>p_as_of)
  ), ships as (
    select v.id,v.name,v.length_overall from public.vessels v where v.company_id=company
      and v.asset_kind='vessel' and (v.active or v.fleet_exit_on>p_as_of)
      and (v.fleet_exit_on is null or v.fleet_exit_on>p_as_of)
  ), membership as (
    select b.person_id,b.vessel_id,b.watch_group,b.function_label,'board'::text as source
      from public.planning_board_rows b where b.company_id=company
    union all
    select a.crew_person_id,a.vessel_id,a.watch_group,a.assignment_role,'assignment'
      from public.planning_assignments a where a.company_id=company
      and a.starts_on<=p_as_of and coalesce(a.ends_on,p_as_of)>=p_as_of
      and a.confirmation_status<>'cancelled'
    union all
    select p.person_id,p.vessel_id,p.watch_group,p.function_label,'period'
      from public.planning_periods p where p.company_id=company
      and p.starts_on<=p_as_of and coalesce(p.ends_on,p_as_of)>=p_as_of
    union all
    select d.person_id,d.vessel_id,d.watch_group,d.function_label,'day'
      from public.planning_days d where d.company_id=company and d.work_date=p_as_of
  )
  select jsonb_build_object(
    'people',coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'name',s.name,'functionLabel',s.function_label,'population',s.employment_population) order by s.name) from staff s),'[]'::jsonb),
    'vessels',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'name',v.name,'lengthOverall',v.length_overall) order by v.id) from ships v),'[]'::jsonb),
    'memberships',coalesce((select jsonb_agg(jsonb_build_object('personId',m.person_id,'vesselId',m.vessel_id,'watchGroup',coalesce(m.watch_group,''),'functionLabel',coalesce(nullif(trim(m.function_label),''),s.function_label),'source',m.source) order by m.person_id,m.vessel_id,m.watch_group,m.function_label) from membership m join staff s on s.id=m.person_id join ships v on v.id=m.vessel_id),'[]'::jsonb),
    'support',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'personId',e.person_id,'name',coalesce(s.name,e.name),'functionLabel',e.function_label,'category',e.category,'position',e.position) order by e.position,e.id) from public.organigramme_support e left join staff s on s.id=e.person_id where e.company_id=company and (e.person_id is null or s.id is not null)),'[]'::jsonb)
  ) into result;
  return result || jsonb_build_object(
    'categoryLabels',coalesce((select jsonb_object_agg(c.key,c.label) from public.organigramme_categories c where c.company_id=company),'{}'::jsonb),
    'links',coalesce((select jsonb_agg(jsonb_build_object('id',l.id,'sourceCategory',l.source_category,'targetKind',l.target_kind,'targetKey',l.target_key,'targetSection',l.target_section,'label',l.label) order by l.id) from public.organigramme_links l where l.company_id=company),'[]'::jsonb)
  );
end;
$$;
revoke all on function public.organigramme_snapshot(date) from public, anon;
grant execute on function public.organigramme_snapshot(date) to authenticated;
comment on function public.organigramme_snapshot(date) is 'Company-scoped Admin/Direction organization chart. Live dated memberships take precedence over permanent board rows in the client; no availability or sensitive HR fields are returned.';

