-- Commercial-offer service descriptions live in the versioned contract
-- payload. Keep the validator strict while allowing the three new text keys.
create or replace function public.is_valid_supplytime_data(value jsonb)
returns boolean
language sql
immutable
set search_path = public, pg_temp
as $$
  select value is not null
    and jsonb_typeof(value) = 'object'
    and octet_length(value::text) <= 1048576
    and not exists (
      select 1
      from jsonb_each(value) entry
      where entry.key <> all (array[
        'box01_owners',
        'box02_charterers',
        'box03_vessel',
        'box04_delivery_date',
        'box05_cancelling_date',
        'box06_port_delivery',
        'box07_delivery_range',
        'box08_notice_delivery',
        'box09_period',
        'box10_extension',
        'box11_continuation',
        'box12_mobilisation',
        'box13_early_termination',
        'box14_bunker_delivery',
        'box15_declaration',
        'box16_area_operation',
        'box17_employment',
        'box18_delivery_hour',
        'box19_special_fuel',
        'box20_charter_hire',
        'box21_extension_hire',
        'box22_invoice_remittance',
        'box23_payment',
        'box24_account_group',
        'box25_internal_price',
        'box26_max_price',
        'box27_war_risk',
        'box28_terror',
        'box29_notice_money',
        'box30_cancellation_clause',
        'box31_taxes',
        'box32_other_law',
        'box33_dispute_resolution',
        'box34_additional_clauses',
        'signature_owners',
        'signature_charterers',
        'commercial_reserve_availability',
        'commercial_reserve_weather',
        'commercial_reserve_other',
        'commercial_charter_hire_service_description',
        'commercial_mobilisation_service_description',
        'commercial_demobilisation_service_description',
        'towed_conditions',
        'departure_window',
        'arrival_window',
        'connection_time',
        'disconnection_time',
        'optional_costs',
        'additional_charges',
        'special_conditions',
        'charterer_signatory',
        'owner_signatory',
        'bareboat_contract_date',
        'bareboat_contract_place',
        'bareboat_charterer_identity',
        'bareboat_refit_details',
        'bareboat_operating_limits',
        'bareboat_last_admin_visit',
        'bareboat_navigation_permit',
        'bareboat_manning_permit',
        'bareboat_delivery_by_truck',
        'bareboat_minimum_duration',
        'bareboat_extension_options',
        'bareboat_early_termination_indemnity',
        'bareboat_insured_value',
        'bareboat_insurance_payer',
        'bareboat_applicable_law',
        'bareboat_jurisdiction',
        'bareboat_charterer_signatory',
        'bareboat_owner_signatory',
        'bareboat_owner_signatory_function',
        'p144_box01_place_date',
        'p144_box02_owners',
        'p144_box03_charterers',
        'p144_box04_vessel_imo',
        'p144_box05_delivery_date',
        'p144_box06_cancelling_date',
        'p144_box07_delivery_place',
        'p144_box08_redelivery',
        'p144_box09_hire_period',
        'p144_box10_extensions',
        'p144_box11_automatic_extension',
        'p144_box12_mobilisation',
        'p144_box13_early_termination',
        'p144_box14_termination_notice',
        'p144_box15_demobilisation',
        'p144_box16_operation_area',
        'p144_box17_employment',
        'p144_box18_specialist_operations',
        'p144_box19_fuel',
        'p144_box20_charter_hire',
        'p144_box21_extension_hire',
        'p144_box22_invoicing',
        'p144_box23_payments',
        'p144_box24_payment_deadline',
        'p144_box25_interest',
        'p144_box26_audit_period',
        'p144_box27_meals',
        'p144_box28_accommodation',
        'p144_box29_sublet',
        'p144_box30_war_cancellation',
        'p144_box31_taxes',
        'p144_box32_off_hire',
        'p144_box33_dispute_resolution',
        'p144_box34_additional_clauses',
        'p144_signature_owners',
        'p144_signature_charterers',
        'p144_annexes'
      ]::text[])
        or jsonb_typeof(entry.value) not in ('string', 'null')
    );
$$;

comment on function public.is_valid_supplytime_data(jsonb) is
  'Validates the versioned Projects contract payload: known offer, towage, bareboat and BIMCO P144 fields only; values are text or JSON null; no nested value; maximum 1 MiB.';
