-- Hierarchical responsibilities and independently maintained default watches.
alter table public.organigramme_support add column hierarchy_rank text
  check (hierarchy_rank in ('1','2','3','4','5','6','7','8','9','support'));

-- Preserve existing responsibilities, changing only the ranks explicitly requested.
with requested(first_name,last_name,rank) as (values
  ('Benjamin','BON','1'), ('Sophie','HAMEL','support'), ('Antoine','MONCEAUX','support'),
  ('Christophe','MINASSIAN','2'), ('Julien','LECOCQ','2'), ('Adam','DEBORDEAUX','4'))
update public.organigramme_support s set hierarchy_rank=r.rank
from requested r, public.people p, public.companies c
where s.person_id=p.id and s.company_id=c.id and c.code='bbtm' and s.category='office'
  and lower(trim(p.first_name))=lower(r.first_name) and lower(trim(p.last_name))=lower(r.last_name);
insert into public.organigramme_support(company_id,person_id,name,function_label,category,position,hierarchy_rank)
select p.company_id,p.id,concat_ws(' ',p.first_name,p.last_name),coalesce(nullif(trim(p.function_label),''),'Stagiaire'),'office',4,'4'
from public.people p join public.companies c on c.id=p.company_id
where c.code='bbtm' and lower(trim(p.first_name))='adam' and lower(trim(p.last_name))='debordeaux'
  and p.active and not exists(select 1 from public.organigramme_support s where s.person_id=p.id and s.category='office');

-- Keep the old RPC for clients already open during deployment.
create function public.save_organigramme_responsibility(p_id bigint,p_person_id bigint,p_name text,
  p_function_label text,p_category text,p_position integer,p_rank text)
returns bigint language plpgsql security invoker set search_path='' as $$
declare saved bigint;
begin
  saved:=public.save_organigramme_support(p_id,p_person_id,p_name,p_function_label,p_category,p_position);
  update public.organigramme_support set hierarchy_rank=case when p_category='office' then nullif(p_rank,'') else null end where id=saved;
  return saved;
end;
$$;
revoke all on function public.save_organigramme_responsibility(bigint,bigint,text,text,text,integer,text) from public,anon;
grant execute on function public.save_organigramme_responsibility(bigint,bigint,text,text,text,integer,text) to authenticated;

create table public.organigramme_watches (
  id bigint generated by default as identity primary key,
  company_id bigint not null default public.current_planning_company_id() references public.companies(id),
  vessel_id bigint not null references public.vessels(id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 80),
  unique(id,company_id)
);
create unique index organigramme_watches_name_idx on public.organigramme_watches(company_id,vessel_id,lower(trim(name)));
create index organigramme_watches_vessel_idx on public.organigramme_watches(vessel_id);
create table public.organigramme_watch_members (
  company_id bigint not null default public.current_planning_company_id() references public.companies(id),
  watch_id bigint not null,
  person_id bigint not null references public.people(id) on delete cascade,
  function_label text not null default '' check(length(function_label)<=300),
  primary key(watch_id,person_id),
  foreign key(watch_id,company_id) references public.organigramme_watches(id,company_id) on delete cascade
);
create index organigramme_watch_members_company_idx on public.organigramme_watch_members(company_id);
create index organigramme_watch_members_person_idx on public.organigramme_watch_members(person_id);
alter table public.organigramme_watches enable row level security;
alter table public.organigramme_watch_members enable row level security;
grant select,insert,update,delete on public.organigramme_watches,public.organigramme_watch_members to authenticated;
grant usage on sequence public.organigramme_watches_id_seq to authenticated;
create policy org_watches_read on public.organigramme_watches for select to authenticated using(public.organigramme_has_access(company_id));
create policy org_watches_insert on public.organigramme_watches for insert to authenticated with check(
  public.organigramme_has_access(company_id) and exists(select 1 from public.vessels v where v.id=vessel_id and v.company_id=organigramme_watches.company_id and v.asset_kind='vessel'));
create policy org_watches_update on public.organigramme_watches for update to authenticated using(public.organigramme_has_access(company_id)) with check(
  public.organigramme_has_access(company_id) and exists(select 1 from public.vessels v where v.id=vessel_id and v.company_id=organigramme_watches.company_id and v.asset_kind='vessel'));
create policy org_watches_delete on public.organigramme_watches for delete to authenticated using(public.organigramme_has_access(company_id));
create policy org_watch_members_read on public.organigramme_watch_members for select to authenticated using(public.organigramme_has_access(company_id));
create policy org_watch_members_insert on public.organigramme_watch_members for insert to authenticated with check(
  public.organigramme_has_access(company_id) and exists(select 1 from public.people p where p.id=person_id and p.company_id=organigramme_watch_members.company_id));
create policy org_watch_members_update on public.organigramme_watch_members for update to authenticated using(public.organigramme_has_access(company_id)) with check(
  public.organigramme_has_access(company_id) and exists(select 1 from public.people p where p.id=person_id and p.company_id=organigramme_watch_members.company_id));
create policy org_watch_members_delete on public.organigramme_watch_members for delete to authenticated using(public.organigramme_has_access(company_id));

-- No assignments or members are imported from the Planning. Each watch is deliberately empty.
insert into public.organigramme_watches(company_id,vessel_id,name)
select v.company_id,v.id,b.name from public.vessels v cross join (values ('Bordée 1'),('Bordée 2')) b(name)
where v.asset_kind='vessel' and v.active and (v.fleet_exit_on is null or v.fleet_exit_on>current_date);

create function public.save_organigramme_watch(p_id bigint,p_vessel_id bigint,p_name text,p_members jsonb)
returns bigint language plpgsql security invoker set search_path='' as $$
declare company bigint:=public.current_planning_company_id(); saved bigint;
begin
  if not public.organigramme_has_access(company) then raise exception 'Accès refusé à l’organigramme.' using errcode='42501'; end if;
  if p_members is null or jsonb_typeof(p_members)<>'array' then raise exception 'Composition invalide.' using errcode='22023'; end if;
  if not exists(select 1 from public.vessels where id=p_vessel_id and company_id=company and asset_kind='vessel' and active) then
    raise exception 'Navire indisponible.' using errcode='42501'; end if;
  if exists(select 1 from jsonb_to_recordset(p_members) as m("personId" bigint,"functionLabel" text)
    where not exists(select 1 from public.people p where p.id=m."personId" and p.company_id=company and p.active and (p.departed_on is null or p.departed_on>current_date))) then
    raise exception 'Personne indisponible dans cette société.' using errcode='42501'; end if;
  if p_id is null then
    insert into public.organigramme_watches(company_id,vessel_id,name) values(company,p_vessel_id,trim(p_name)) returning id into saved;
  else
    update public.organigramme_watches set vessel_id=p_vessel_id,name=trim(p_name) where id=p_id and company_id=company returning id into saved;
    if saved is null then raise exception 'Bordée introuvable.' using errcode='P0002'; end if;
  end if;
  delete from public.organigramme_watch_members where watch_id=saved and company_id=company;
  insert into public.organigramme_watch_members(company_id,watch_id,person_id,function_label)
  select company,saved,m."personId",coalesce(trim(m."functionLabel"),'') from jsonb_to_recordset(p_members) as m("personId" bigint,"functionLabel" text);
  return saved;
end;
$$;
revoke all on function public.save_organigramme_watch(bigint,bigint,text,jsonb) from public,anon;
grant execute on function public.save_organigramme_watch(bigint,bigint,text,jsonb) to authenticated;

create or replace function public.organigramme_snapshot_v2(p_as_of date default current_date)
returns jsonb language plpgsql stable security invoker set search_path = '' as $$
declare company bigint := public.current_planning_company_id(); result jsonb;
begin
  if not public.organigramme_has_access(company) then raise exception 'Accès refusé à l’organigramme.' using errcode='42501'; end if;
  if p_as_of is null then raise exception 'Date de situation obligatoire.' using errcode='22023'; end if;
  with staff as (
    select p.id, concat_ws(' ',p.first_name,p.last_name) as name,
      coalesce(nullif(trim(p.function_label),''),p.grade_label,'') as function_label, p.employment_population, p.email, p.phone
    from public.people p where p.company_id=company
      and (p.hired_on<=p_as_of or (p.hired_on is null and p.active))
      and (p.departed_on is null or p.departed_on>p_as_of)
      and (p.active or p.departed_on>p_as_of)
  ), ships as (
    select v.id,v.name,v.length_overall from public.vessels v where v.company_id=company
      and v.asset_kind='vessel' and (v.active or v.fleet_exit_on>p_as_of)
      and (v.fleet_exit_on is null or v.fleet_exit_on>p_as_of)
  ), membership as (
    select m.person_id,w.vessel_id,w.name as watch_group,m.function_label,'manual'::text as source
    from public.organigramme_watch_members m join public.organigramme_watches w on w.id=m.watch_id and w.company_id=m.company_id
    where m.company_id=company
  )
  select jsonb_build_object(
    'people',coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'name',s.name,'functionLabel',s.function_label,'population',s.employment_population,'email',s.email,'phone',s.phone) order by s.name) from staff s),'[]'::jsonb),
    'vessels',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'name',v.name,'lengthOverall',v.length_overall) order by v.id) from ships v),'[]'::jsonb),
    'memberships',coalesce((select jsonb_agg(jsonb_build_object('personId',m.person_id,'vesselId',m.vessel_id,'watchGroup',coalesce(m.watch_group,''),'functionLabel',coalesce(nullif(trim(m.function_label),''),s.function_label),'source',m.source) order by m.person_id,m.vessel_id,m.watch_group,m.function_label) from membership m join staff s on s.id=m.person_id join ships v on v.id=m.vessel_id),'[]'::jsonb),
    'support',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'personId',e.person_id,'name',coalesce(s.name,e.name),'functionLabel',e.function_label,'category',e.category,'position',e.position,'rank',e.hierarchy_rank) order by e.position,e.id) from public.organigramme_support e left join staff s on s.id=e.person_id where e.company_id=company and (e.person_id is null or s.id is not null)),'[]'::jsonb)
  ) into result;
  return result || jsonb_build_object(
    'watches',coalesce((select jsonb_agg(jsonb_build_object('id',w.id,'vesselId',w.vessel_id,'name',w.name) order by w.name,w.id) from public.organigramme_watches w join public.vessels v on v.id=w.vessel_id and v.company_id=company and v.asset_kind='vessel' and (v.active or v.fleet_exit_on>p_as_of) and (v.fleet_exit_on is null or v.fleet_exit_on>p_as_of) where w.company_id=company),'[]'::jsonb),
    'categoryLabels',coalesce((select jsonb_object_agg(c.key,c.label) from public.organigramme_categories c where c.company_id=company),'{}'::jsonb),
    'links',coalesce((select jsonb_agg(jsonb_build_object('id',l.id,'sourceCategory',l.source_category,'targetKind',l.target_kind,'targetKey',l.target_key,'targetSection',l.target_section,'label',l.label) order by l.id) from public.organigramme_links l where l.company_id=company),'[]'::jsonb)
  );
end;
$$;
revoke all on function public.organigramme_snapshot_v2(date) from public, anon;
grant execute on function public.organigramme_snapshot_v2(date) to authenticated;
comment on function public.organigramme_snapshot_v2(date) is 'Admin/Direction only. Manual default watches and hierarchical responsibilities, independent of Planning. Date filters HR/fleet eligibility, not the saved composition.';
