create table public.fleet_certificate_findings (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete restrict,
  certificate_id bigint not null references public.fleet_certificates(id) on delete cascade,
  reference text not null,
  finding_type text not null check (finding_type in (
    'major_non_conformity',
    'minor_non_conformity',
    'class_condition',
    'remark',
    'prescription'
  )),
  title text not null check (length(btrim(title)) between 3 and 240),
  description text not null default '',
  detected_on date not null default current_date,
  treatment_delay_days integer check (treatment_delay_days is null or treatment_delay_days >= 0),
  treatment_due_on date,
  status text not null default 'declared' check (status in (
    'declared', 'assigned', 'in_progress', 'pending_validation', 'closed'
  )),
  progress smallint not null default 0 check (progress between 0 and 100),
  responsible_person_id bigint references public.people(id) on delete set null,
  responsible_name text not null default '',
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  validated_by uuid references public.profiles(id) on delete set null,
  validated_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, reference),
  unique (id, company_id)
);

create table public.fleet_certificate_finding_attachments (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete restrict,
  finding_id bigint not null,
  attachment_kind text not null check (attachment_kind in ('finding', 'treatment')),
  original_file_name text not null,
  storage_bucket text not null default 'fleet-certificates',
  storage_path text not null,
  mime_type text,
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes >= 0),
  caption text not null default '',
  uploaded_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (storage_bucket, storage_path),
  constraint fleet_certificate_finding_attachments_finding_company_fk
    foreign key (finding_id, company_id)
    references public.fleet_certificate_findings(id, company_id)
    on delete cascade
);

create table public.fleet_certificate_finding_events (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete restrict,
  finding_id bigint not null,
  event_type text not null check (event_type in (
    'created', 'assigned', 'status_changed', 'progress_updated',
    'evidence_added', 'commented', 'validated'
  )),
  from_status text,
  to_status text,
  note text not null default '',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint fleet_certificate_finding_events_finding_company_fk
    foreign key (finding_id, company_id)
    references public.fleet_certificate_findings(id, company_id)
    on delete cascade
);

create index fleet_certificate_findings_company_certificate_idx
  on public.fleet_certificate_findings (company_id, certificate_id, status, treatment_due_on);
create index fleet_certificate_findings_responsible_idx
  on public.fleet_certificate_findings (company_id, responsible_person_id, status)
  where responsible_person_id is not null;
create index fleet_certificate_findings_due_idx
  on public.fleet_certificate_findings (company_id, treatment_due_on, status)
  where treatment_due_on is not null and status <> 'closed';
create index fleet_certificate_finding_attachments_finding_idx
  on public.fleet_certificate_finding_attachments (company_id, finding_id, attachment_kind, created_at);
create index fleet_certificate_finding_attachments_uploaded_by_idx
  on public.fleet_certificate_finding_attachments (uploaded_by)
  where uploaded_by is not null;
create index fleet_certificate_finding_events_history_idx
  on public.fleet_certificate_finding_events (company_id, finding_id, created_at desc);
create index fleet_certificate_finding_events_created_by_idx
  on public.fleet_certificate_finding_events (created_by)
  where created_by is not null;

create or replace function public.prepare_fleet_certificate_finding()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  target_company_id bigint;
begin
  select certificate.company_id
  into target_company_id
  from public.fleet_certificates certificate
  where certificate.id = new.certificate_id
    and certificate.company_id = public.current_planning_company_id();

  if target_company_id is null then
    raise exception using errcode = '42501', message = 'Certificat inaccessible.';
  end if;

  new.company_id := target_company_id;
  new.created_by := coalesce(new.created_by, auth.uid());
  new.updated_by := auth.uid();
  new.updated_at := now();
  new.reference := coalesce(
    nullif(btrim(new.reference), ''),
    'EC-' || extract(year from new.detected_on)::integer::text || '-' || lpad(new.id::text, 4, '0')
  );
  new.responsible_name := coalesce((
    select btrim(concat(person.first_name, ' ', person.last_name))
    from public.people person
    where person.id = new.responsible_person_id
      and person.company_id = target_company_id
  ), nullif(btrim(new.responsible_name), ''), 'Non assigné');

  if new.status = 'closed' then
    new.progress := 100;
    new.closed_at := coalesce(new.closed_at, now());
  elsif new.progress = 100 and new.status <> 'pending_validation' then
    new.status := 'pending_validation';
  end if;

  return new;
end;
$$;

revoke all on function public.prepare_fleet_certificate_finding() from public, anon, authenticated;

create trigger fleet_certificate_findings_prepare
before insert or update on public.fleet_certificate_findings
for each row execute function public.prepare_fleet_certificate_finding();

create or replace function public.audit_fleet_certificate_finding()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.fleet_certificate_finding_events (
      company_id, finding_id, event_type, to_status, note, created_by
    ) values (
      new.company_id, new.id, 'created', new.status, 'Écart créé', auth.uid()
    );
    return new;
  end if;

  if old.responsible_person_id is distinct from new.responsible_person_id
    or old.responsible_name is distinct from new.responsible_name then
    insert into public.fleet_certificate_finding_events (
      company_id, finding_id, event_type, from_status, to_status, note, created_by
    ) values (
      new.company_id, new.id, 'assigned', old.status, new.status,
      'Responsable : ' || new.responsible_name, auth.uid()
    );
  end if;

  if old.status is distinct from new.status then
    insert into public.fleet_certificate_finding_events (
      company_id, finding_id, event_type, from_status, to_status, note, created_by
    ) values (
      new.company_id, new.id,
      case when new.status = 'closed' then 'validated' else 'status_changed' end,
      old.status, new.status, 'État mis à jour', auth.uid()
    );
  elsif old.progress is distinct from new.progress then
    insert into public.fleet_certificate_finding_events (
      company_id, finding_id, event_type, from_status, to_status, note, created_by
    ) values (
      new.company_id, new.id, 'progress_updated', old.status, new.status,
      'Avancement : ' || new.progress::text || ' %', auth.uid()
    );
  end if;

  return new;
end;
$$;

revoke all on function public.audit_fleet_certificate_finding() from public, anon, authenticated;

create trigger fleet_certificate_findings_audit
after insert or update on public.fleet_certificate_findings
for each row execute function public.audit_fleet_certificate_finding();

create or replace function public.audit_fleet_certificate_finding_attachment()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  insert into public.fleet_certificate_finding_events (
    company_id, finding_id, event_type, note, created_by
  ) values (
    new.company_id,
    new.finding_id,
    'evidence_added',
    case when new.attachment_kind = 'finding'
      then 'Pièce du constat ajoutée : '
      else 'Preuve de traitement ajoutée : '
    end || new.original_file_name,
    auth.uid()
  );
  return new;
end;
$$;

revoke all on function public.audit_fleet_certificate_finding_attachment() from public, anon, authenticated;

create trigger fleet_certificate_finding_attachments_audit
after insert on public.fleet_certificate_finding_attachments
for each row execute function public.audit_fleet_certificate_finding_attachment();

alter table public.fleet_certificate_findings enable row level security;
alter table public.fleet_certificate_finding_attachments enable row level security;
alter table public.fleet_certificate_finding_events enable row level security;

create policy fleet_certificate_findings_company_read
on public.fleet_certificate_findings for select to authenticated
using (
  company_id = (select public.current_planning_company_id())
  and (select public.has_any_role(array['admin', 'direction', 'armement', 'capitaine', 'marin']))
);

create policy fleet_certificate_findings_office_insert
on public.fleet_certificate_findings for insert to authenticated
with check (
  company_id = (select public.current_planning_company_id())
  and (select public.has_any_role(array['admin', 'direction', 'armement']))
);

create policy fleet_certificate_findings_treatment_update
on public.fleet_certificate_findings for update to authenticated
using (
  company_id = (select public.current_planning_company_id())
  and (
    (select public.has_any_role(array['admin', 'direction', 'armement']))
    or exists (
      select 1
      from public.people person
      where person.id = responsible_person_id
        and person.company_id = fleet_certificate_findings.company_id
        and person.user_id = (select auth.uid())
    )
  )
)
with check (
  company_id = (select public.current_planning_company_id())
  and (
    (select public.has_any_role(array['admin', 'direction', 'armement']))
    or exists (
      select 1
      from public.people person
      where person.id = responsible_person_id
        and person.company_id = fleet_certificate_findings.company_id
        and person.user_id = (select auth.uid())
    )
  )
);

create policy fleet_certificate_findings_office_delete
on public.fleet_certificate_findings for delete to authenticated
using (
  company_id = (select public.current_planning_company_id())
  and (select public.has_any_role(array['admin', 'direction', 'armement']))
);

create policy fleet_certificate_finding_attachments_company_read
on public.fleet_certificate_finding_attachments for select to authenticated
using (
  company_id = (select public.current_planning_company_id())
  and (select public.has_any_role(array['admin', 'direction', 'armement', 'capitaine', 'marin']))
);

create policy fleet_certificate_finding_attachments_contributor_insert
on public.fleet_certificate_finding_attachments for insert to authenticated
with check (
  company_id = (select public.current_planning_company_id())
  and exists (
    select 1
    from public.fleet_certificate_findings finding
    left join public.people person on person.id = finding.responsible_person_id
    where finding.id = finding_id
      and finding.company_id = fleet_certificate_finding_attachments.company_id
      and (
        (select public.has_any_role(array['admin', 'direction', 'armement']))
        or person.user_id = (select auth.uid())
      )
  )
);

create policy fleet_certificate_finding_attachments_contributor_delete
on public.fleet_certificate_finding_attachments for delete to authenticated
using (
  company_id = (select public.current_planning_company_id())
  and exists (
    select 1
    from public.fleet_certificate_findings finding
    left join public.people person on person.id = finding.responsible_person_id
    where finding.id = finding_id
      and finding.company_id = fleet_certificate_finding_attachments.company_id
      and (
        (select public.has_any_role(array['admin', 'direction', 'armement']))
        or person.user_id = (select auth.uid())
      )
  )
);

create policy fleet_certificate_finding_events_company_read
on public.fleet_certificate_finding_events for select to authenticated
using (
  company_id = (select public.current_planning_company_id())
  and (select public.has_any_role(array['admin', 'direction', 'armement', 'capitaine', 'marin']))
);

create policy fleet_certificate_finding_events_contributor_insert
on public.fleet_certificate_finding_events for insert to authenticated
with check (
  company_id = (select public.current_planning_company_id())
  and exists (
    select 1
    from public.fleet_certificate_findings finding
    left join public.people person on person.id = finding.responsible_person_id
    where finding.id = finding_id
      and finding.company_id = fleet_certificate_finding_events.company_id
      and (
        (select public.has_any_role(array['admin', 'direction', 'armement']))
        or person.user_id = (select auth.uid())
      )
  )
);

revoke all on table public.fleet_certificate_findings from public, anon, authenticated;
revoke all on table public.fleet_certificate_finding_attachments from public, anon, authenticated;
revoke all on table public.fleet_certificate_finding_events from public, anon, authenticated;
grant select, insert, update, delete on table public.fleet_certificate_findings to authenticated;
grant select, insert, delete on table public.fleet_certificate_finding_attachments to authenticated;
grant select, insert on table public.fleet_certificate_finding_events to authenticated;
grant usage, select on sequence public.fleet_certificate_findings_id_seq to authenticated;
grant usage, select on sequence public.fleet_certificate_finding_attachments_id_seq to authenticated;
grant usage, select on sequence public.fleet_certificate_finding_events_id_seq to authenticated;

update storage.buckets
set allowed_mime_types = array[
  'application/pdf',
  'image/png',
  'image/jpeg',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
]::text[]
where id = 'fleet-certificates';

create or replace function public.can_manage_fleet_certificate_finding_storage(object_name text)
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select
    split_part(object_name, '/', 1) = public.current_planning_company_id()::text
    and split_part(object_name, '/', 3) = 'findings'
    and exists (
      select 1
      from public.fleet_certificate_findings finding
      left join public.people person on person.id = finding.responsible_person_id
      where finding.company_id = public.current_planning_company_id()
        and finding.id::text = split_part(object_name, '/', 4)
        and (
          public.has_any_role(array['admin', 'direction', 'armement'])
          or person.user_id = auth.uid()
        )
    );
$$;

revoke all on function public.can_manage_fleet_certificate_finding_storage(text) from public, anon;
grant execute on function public.can_manage_fleet_certificate_finding_storage(text) to authenticated;

drop policy if exists fleet_certificates_storage_insert on storage.objects;
create policy fleet_certificates_storage_insert
on storage.objects for insert to authenticated
with check (
  bucket_id = 'fleet-certificates'
  and split_part(name, '/', 1) = (select public.current_planning_company_id())::text
  and (
    (select public.has_any_role(array['admin', 'direction', 'armement']))
    or (select public.can_manage_fleet_certificate_finding_storage(name))
  )
);

drop policy if exists fleet_certificates_storage_update on storage.objects;
create policy fleet_certificates_storage_update
on storage.objects for update to authenticated
using (
  bucket_id = 'fleet-certificates'
  and split_part(name, '/', 1) = (select public.current_planning_company_id())::text
  and (
    (select public.has_any_role(array['admin', 'direction', 'armement']))
    or (select public.can_manage_fleet_certificate_finding_storage(name))
  )
)
with check (
  bucket_id = 'fleet-certificates'
  and split_part(name, '/', 1) = (select public.current_planning_company_id())::text
  and (
    (select public.has_any_role(array['admin', 'direction', 'armement']))
    or (select public.can_manage_fleet_certificate_finding_storage(name))
  )
);

drop policy if exists fleet_certificates_storage_delete on storage.objects;
create policy fleet_certificates_storage_delete
on storage.objects for delete to authenticated
using (
  bucket_id = 'fleet-certificates'
  and split_part(name, '/', 1) = (select public.current_planning_company_id())::text
  and (
    (select public.has_any_role(array['admin', 'direction', 'armement']))
    or (select public.can_manage_fleet_certificate_finding_storage(name))
  )
);

create or replace function public.delete_fleet_certificate_findings(p_finding_ids bigint[])
returns table (storage_bucket text, storage_path text)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  target_company_id bigint := public.current_planning_company_id();
begin
  if target_company_id is null
    or not public.has_any_role(array['admin', 'direction', 'armement']) then
    raise exception using errcode = '42501', message = 'Accès refusé.';
  end if;

  if coalesce(cardinality(p_finding_ids), 0) = 0 then
    return;
  end if;

  return query
  select distinct attachment.storage_bucket, attachment.storage_path
  from public.fleet_certificate_finding_attachments attachment
  join public.fleet_certificate_findings finding on finding.id = attachment.finding_id
  where finding.company_id = target_company_id
    and finding.id = any(p_finding_ids);

  delete from public.fleet_certificate_findings finding
  where finding.company_id = target_company_id
    and finding.id = any(p_finding_ids);
end;
$$;

revoke all on function public.delete_fleet_certificate_findings(bigint[]) from public, anon;
grant execute on function public.delete_fleet_certificate_findings(bigint[]) to authenticated;

create or replace function public.delete_fleet_certificate_documents(p_certificate_ids bigint[])
returns table (storage_bucket text, storage_path text)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  target_company_id bigint := public.current_planning_company_id();
begin
  if target_company_id is null
    or not public.has_any_role(array['admin', 'direction', 'armement']) then
    raise exception using errcode = '42501', message = 'Accès refusé.';
  end if;

  if coalesce(cardinality(p_certificate_ids), 0) = 0 then
    return;
  end if;

  return query
  select distinct document.storage_bucket, document.storage_path
  from (
    select version.storage_bucket, version.storage_path
    from public.fleet_certificate_versions version
    join public.fleet_certificates certificate on certificate.id = version.certificate_id
    where certificate.company_id = target_company_id
      and certificate.id = any(p_certificate_ids)
    union all
    select certificate.storage_bucket, certificate.storage_path
    from public.fleet_certificates certificate
    where certificate.company_id = target_company_id
      and certificate.id = any(p_certificate_ids)
    union all
    select attachment.storage_bucket, attachment.storage_path
    from public.fleet_certificate_finding_attachments attachment
    join public.fleet_certificate_findings finding on finding.id = attachment.finding_id
    where finding.company_id = target_company_id
      and finding.certificate_id = any(p_certificate_ids)
  ) document
  where nullif(document.storage_bucket, '') is not null
    and nullif(document.storage_path, '') is not null;

  delete from public.fleet_certificates certificate
  where certificate.company_id = target_company_id
    and certificate.id = any(p_certificate_ids);
end;
$$;

revoke all on function public.delete_fleet_certificate_documents(bigint[]) from public, anon;
grant execute on function public.delete_fleet_certificate_documents(bigint[]) to authenticated;

comment on table public.fleet_certificate_findings is
  'Actions et écarts de conformité suivis pour les certificats de la flotte.';
comment on table public.fleet_certificate_finding_attachments is
  'Pièces du constat initial et preuves de traitement des écarts flotte.';
comment on table public.fleet_certificate_finding_events is
  'Historique immuable des changements et preuves liés aux écarts flotte.';
